const listOfWords = [
{german:"der Abend, am Abend",slovak:"vecer"},
{german:"das Abendessen,",slovak:"vecera"},
{german:"alle",slovak:"vsetci"},
{german:"also",slovak:"teda"},
{german:"anziehen",slovak:"obliect"},
{german:"arbeiten",slovak:"pracovat"},
{german:"der Arbeitstag, -e",slovak:"pracovny den"},
{german:"aufräumen",slovak:"upratovat"},
{german:"aufstehen",slovak:"vstávat (napr. ráno z postele)"},
{german:"ausgehen",slovak:"ist sa zabavit"},
{german:"Wollen wir ausgehen?",slovak:"Ideme von? (vo vyzname: zabavit sa)"},
{german:"Am Freitag gehe ich aus.",slovak:"V piatok idem von. (vo vyzname: zabavitt sa)"},
{german:"backen",slovak:"piect"},
{german:"beginnen",slovak:"zacat"},
{german:"das Bein, -e",slovak:"noha"},
{german:"das Bett, -en (ins Bett gehen)",slovak:"postel (ist do postele)"},
{german:"bleiben",slovak:"zostat"},
{german:"der Boden, Pl. Böden",slovak:"zem, podlaha"},
{german:"brauchen",slovak:"potrebovat"},
{german:"bringen",slovak:"priniest"},
{german:"das Brot, -e",slovak:"chlieb"},
{german:"bügeln",slovak:"zehlit"},
{german:"das Buch, Pl. Bücher",slovak:"kniha"},
{german:"der Bus, Pl. Busse",slovak:"autobus"},
{german:"die Butter, -",slovak:"maslo"},
{german:"das Croissant, -s",slovak:"croissant"},
{german:"danach",slovak:"potom"},
{german:"dann",slovak:"neskôr, potom"},
{german:"Das ist mir egal.",slovak:"To je mi jedno."},
{german:"decken (den Tisch decken)",slovak:"prestriet (prestriet stôl)"},
{german:"das Dokument,-e",slovak:"dokument"},
{german:"dort",slovak:"tam"},
{german:"duschen",slovak:"sprchovat sa"},
{german:"einkaufen",slovak:"nakupovat"},
{german:"essen",slovak:"jest"},
{german:"fahren",slovak:"ist (autom, autobuson)"},
{german:"fallen",slovak:"padnút"},
{german:"fast immer",slovak:"skoro vidy"},
{german:"fast nie",slovak:"skoro nikdy"},
{german:"der Feierabend",slovak:"fajront"},
{german:"die Ferien (in den Ferien)",slovak:"prázdniny (cez prázdniny)"},
{german:"fernsehen",slovak:"dívat sa na TV"},
{german:"frei",slovak:"volny"},
{german:"die Freundin, -nen",slovak:"kamarátka"},
{german:"das Frühstück, -",slovak:"ranajky"},
{german:"fühlen",slovak:"cítit"},
{german:"geben",slovak:"dat"},
{german:"der Geburtstag, -e (am Geburtstag)",slovak:"narodeniny (na narodeniny)"},
{german:"gemeinsam",slovak:"spolocne"},
{german:"die Gurke, -n",slovak:"uhorka"},
{german:"gut",slovak:"dobre"},
{german:"helfen",slovak:"pomôct"},
{german:"heute",slovak:"dnes"},
{german:"immer",slovak:"vzdy"},
{german:"der Kaffee",slovak:"káva"},
{german:"Karten spielen",slovak:"hrat karty"},
{german:"der Käse, Pl. Käsesorten",slovak:"syr"},
{german:"kennenlernen",slovak:"spoznat (niekoho, nieco)"},
{german:"klein",slovak:"maly/á/é"},
{german:"kochen",slovak:"varit"},
{german:"das Konzert, -e (ins Konzert gehen)",slovak:"koncert (ist na koncert)"},
{german:"krank",slovak:"chory"},
{german:"die Küche, -n",slovak:"kuchyña"},
{german:"der Laptop, -s",slovak:"laptop"},
{german:"laufen",slovak:"bezat"},
{german:"lesen",slovak:"cítat"},
{german:"manchmal",slovak:"niekedy"},
{german:"mein",slovak:"môj"},
{german:"meistens",slovak:"väcsinou"},
{german:"die Milch, O",slovak:"mlieko"},
{german:"der Mittag, zu Mittag",slovak:"obed, na obed"},
{german:"das Mittagessen, nach dem Mittagessen",slovak:"obed, po obede"},
{german:"der Morgen, am Morgen",slovak:"rano, rano"},
{german:"der Nachmittag, am Nachmittag",slovak:"popoludnie, popoludni"},
{german:"die Nacht, PI. Nächte",slovak:"noc"},
{german:"nehmen",slovak:"vziat"},
{german:"nie",slovak:"nikdy"},
{german:"normalerweise",slovak:"zvycajne"},
{german:"das Obst, PI. Obstsorten",slovak:"ovocie"},
{german:"oft",slovak:"casto"},
{german:"der Orangensaft",slovak:"pomarancovy dzus"},
{german:"öfter",slovak:"castejie"},
{german:"die Pause, -n",slovak:"prestavka"},
{german:"putzen (Zähne putzen)",slovak:"cistit (cistit zuby)"},
{german:"rasieren",slovak:"holit"},
{german:"reden über etw.",slovak:"rozprávat o niecom"},
{german:"regelmäßig",slovak:"pravidelne"},
{german:"sehen",slovak:"vidiet"},
{german:"sehr",slovak:"velmi"},
{german:"sehr oft",slovak:"velmi casto"},
{german:"selten",slovak:"zriedka"},
{german:"schaffen",slovak:"zvládnut nieco"},
{german:"der Schinken",slovak:"sunka"},
{german:"schlafen",slovak:"spat"},
{german:"schwer",slovak:"tazky"},
{german:"sieben",slovak:"sedem"},
{german:"sitzen",slovak:"sediet"},
{german:"Soll ich mitkommen?",slovak:"Mam ist aj ja?"},
{german:"spazieren",slovak:"prechádzat sa"},
{german:"der Spaziergang, Pl. Spaziergänge",slovak:"prechádzka"},
{german:"später",slovak:"neskôr"},
{german:"sprechen",slovak:"hovorit"},
{german:"die Stunde, -n",slovak:"hodina"},
{german:"der Supermarkt, Pl. Supermärkte",slovak:"supermarket"},
{german:"täglich",slovak:"denne"},
{german:"der Tee, Pl. Teesorten",slovak:"caj"},
{german:"das Theater (ins Theater gehen)",slovak:"divadlo (íst do divadla)"},
{german:"der Tisch, -e",slovak:"stôl"},
{german:"die Tomate, -n",slovak:"paradajka"},
{german:"die Torte, -n",slovak:"torta"},
{german:"treffen",slovak:"stretnút"},
{german:"um",slovak:"o (tyka sa casovych údajov)"},
{german:"umziehen",slovak:"prezliect"},
{german:"unregelmäßig",slovak:"nepravidelne"},
{german:"unter der Woche",slovak:"cez tyzden"},
{german:"die Unterlagen",slovak:"podklady"},
{german:"verschlafen, Milan verschläft oft.",slovak:"zaspat, Milan casto zaspí."},
{german:"vorbereiten",slovak:"pripravit (napr. ranajky, postel...)"},
{german:"der Vormittag, am Vormittag",slovak:"doobedie, doobeda"},
{german:"vorstellen",slovak:"predstavit (niekoho)"},
{german:"Ich stelle dir Milan vor.",slovak:"Predstavím ti Milana."},
{german:"waschen",slovak:"umyvat"},
{german:"das Waschpulver,",slovak:"prások na pranie"},
{german:"wecken",slovak:"zobudit"},
{german:"weit",slovak:"daleko"},
{german:"die Wohnung, -en",slovak:"byt"},
{german:"Wie fühlen Sie sich?",slovak:"Ako sa cítite?"},
{german:"Wie haben Sie geschlafen?",slovak:"Ako ste sa vyspali?"},
{german:"zu Hause",slovak:"doma"},
{german:"zu Mittag essen",slovak:"obedovat"},
{german:"zuerst",slovak:"najprv"},
{german:"zurückkommen",slovak:"vrátit sa spät"},
{german:"blau",slovak:"modrá"},
{german:"rot",slovak:"cervená"},
{german:"gelb",slovak:"zltá"},
{german:"grün",slovak:"zelená"},
{german:"schwarz",slovak:"cierna"},
{german:"weiß",slovak:"biela"},
{german:"grau",slovak:"sedá"},
{german:"orange",slovak:"oranzová"},
{german:"braun",slovak:"hnedá"},
{german:"violett/lila",slovak:"fialová"},
{german:"dunkelblau",slovak:"tmavomodrá"},
{german:"hellblau",slovak:"svetlomodrá"},
{german:"die Hose, -n",slovak:"nohavice"},
{german:"die Jeans,",slovak:"rifle"},
{german:"der Rock, PI. Röcke",slovak:"sukna"},
{german:"das Kleid, -er",slovak:"saty"},
{german:"die Bluse, -n",slovak:"blúzka"},
{german:"das Hemd, -en",slovak:"kosela"},
{german:"die Krawatte, -n",slovak:"kravata"},
{german:"das T-Shirt, -S",slovak:"tricko"},
{german:"der Pullover,",slovak:"pulóver"},
{german:"die Unterwäsche, -",slovak:"spodná bielizen"},
{german:"der BH (Büstenhalter),-s",slovak:"podprsenka"},
{german:"die Unterhose, -n",slovak:"spodky,"},
{german:"spodná bielizen",slovak:"der Slip, -s"},
{german:"nohavicky",slovak:"die Jacke, -n"},
{german:"bunda",slovak:"der Mantel, PI. Mäntel"},
{german:"kabat",slovak:"der Anzug, Pl. Anzige"},
{german:"oblek",slovak:"der Sakko, -s"},
{german:"sako",slovak:"das Kostüm, Pl. Kostüm"},
{german:"kostym",slovak:"der Schuh, -e"},
{german:"topánka",slovak:"der Stiefel,"},
{german:"cizma",slovak:"die Socke, -n"},
{german:"ponozka",slovak:"die Strumpfhose, -n"},
{german:"pancuchové",slovak:"nohavicky"},
{german:"der Badeanzug, Pl. Badeanzüge",slovak:"plavky (pre Zeny)"},
{german:"die Badehose, -n",slovak:"plavky (pre muzov)"},
{german:"der Pyjama, -S",slovak:"Pyzama"},
{german:"das Nachthemd, -en",slovak:"nocná kosela"},
{german:"der Handschuh, -e",slovak:"rukavica"},
{german:"die Mütze, -n",slovak:"ciapka"},
{german:"der Schal, -s",slovak:"sál"},
{german:"das Tuch, Pl. Tücher",slovak:"Satka"},
{german:"Das ist",slovak:"To je"},
{german:"mein Sohn",slovak:"môj syn"},
{german:"meine Tochter",slovak:"moja dcéra"},
{german:"mein Mann",slovak:"môj muz"},
{german:"meine Mutter",slovak:"moja mama"},
{german:"mein Vater",slovak:"môj otec"},
{german:"meine Freundin",slovak:"moja priatelka"},
{german:"mein Freund",slovak:"moj priatel"},
{german:"Ich bin ledig.",slovak:"Som slobodny/a."},
{german:"Ich bin Single.",slovak:"Som single."},
{german:"Ich bin geschieden.",slovak:"Som rozvedeny."},
];