const listOfWords = [
{german:"aber",slovak:"ale"},
{german:"der Abteilungsleiter, -",slovak:"vedúci oddelenia"},
{german:"die Adresse, -n",slovak:"adresa"},
{german:"Ach so.",slovak:"Ach tak."},
{german:"alt",slovak:"stary"},
{german:"arbeiten",slovak:"pracovat"},
{german:"der Arbeitsplatz, Pl. Arbeitsplätze",slovak:"pracovisko"},
{german:"die Assistentin, -nen",slovak:"asistentka"},
{german:"ausfüllen (ein Formular ausfüllen)",slovak:"vyplnit (vyplnit formulár)"},
{german:"das Auto, -S",slovak:"auto"},
{german:"der Bahnhof, Pl. Bahnhöfe (am Bahnhof)",slovak:"stanica (na stanici)"},
{german:"beginnen",slovak:"zacat"},
{german:"der Beruf, -e",slovak:"povolanie"},
{german:"das Bett, -en (ins Bett, im Bett)",slovak:"postel (do postele, v posteli)"},
{german:"das Bild, P1. Bilder",slovak:"obraz"},
{german:"bis jetzt",slovak:"doteraz"},
{german:"die Blume, -n",slovak:"kvet"},
{german:"die Brille, -n",slovak:"okuliare"},
{german:"das Buch, Pl. Bücher",slovak:"kniha"},
{german:"bunt",slovak:"pestry"},
{german:"die Chipkarte, -n",slovak:"cipová karta"},
{german:"die Couch, -s",slovak:"sedacka"},
{german:"dann",slovak:"neskôr"},
{german:"Das freut mich.",slovak:"To ma tesi."},
{german:"Das ist...",slovak:"To je..."},
{german:"Deutschland",slovak:"Nemecko"},
{german:"die Disco, -s",slovak:"diskotéka"},
{german:"drei",slovak:"tri"},
{german:"dunkel",slovak:"tmavy"},
{german:"duzen",slovak:"tykat si"},
{german:"der DVD-Player,",slovak:"DVD-prehrávac"},
{german:"eckig",slovak:"hranaty"},
{german:"erst",slovak:"len"},
{german:"Es freut mich.",slovak:"Tesi ma (pri zoznamovani)."},
{german:"die Familie, -n",slovak:"rodina"},
{german:"das Fenster,",slovak:"okno"},
{german:"der Fernseher,",slovak:"televizor"},
{german:"die Firma, Pl. Firmen (in einer großen Firma)",slovak:"firma (vo velkej firme)"},
{german:"die Flasche, -n",slovak:"flasa"},
{german:"die Frau, -en",slovak:"pani"},
{german:"früher",slovak:"predtym"},
{german:"ganz gut",slovak:"celkom dobre"},
{german:"die Gardine, -n",slovak:"záclona"},
{german:"der Garten, Pl. Gärten",slovak:"záhrada"},
{german:"gefallen (Wie gefällt Ihnen Graz?)",slovak:"pácit sa (Ako sa Vám páci Graz?)"},
{german:"das Geburtsdatum, Pl. Geburtsdaten",slovak:"dátum narodenia"},
{german:"der Geburtsort, -e",slovak:"miesto narodenia"},
{german:"gesund",slovak:"zdravy"},
{german:"das Glas, Pl. Gläser",slovak:"pohár"},
{german:"Griechenland",slovak:"Grécko"},
{german:"groß",slovak:"velky"},
{german:"das Haus, Pl. Häuser",slovak:"dom"},
{german:"helfen",slovak:"pomôct"},
{german:"hell",slovak:"svetly"},
{german:"der Herr, -en",slovak:"pán"},
{german:"Herzlich willkommen.",slovak:"Srdecne Vás vitam."},
{german:"hier",slovak:"tu"},
{german:"hoch",slovak:"vysoky"},
{german:"der Hund, -e",slovak:"pes"},
{german:"hübsch",slovak:"pekná"},
{german:"der Ingenieur, -e",slovak:"inzinier"},
{german:"das Kind, -er",slovak:"dieta"},
{german:"das Kissen, -n",slovak:"vankús"},
{german:"klein",slovak:"maly"},
{german:"der Kollege, -n",slovak:"kolega"},
{german:"krank",slovak:"chory"},
{german:"die Küche, -n (in der Küche)",slovak:"kuchyña (v kuchyni)"},
{german:"die Lampe, -n",slovak:"lampa"},
{german:"lang",slovak:"dlhy"},
{german:"Lassen Sie sich Zeit.",slovak:"Neponáhlajte sa."},
{german:"leben",slovak:"zit"},
{german:"der Lehrer, -",slovak:"ucitel"},
{german:"die Lehrerin, -nen",slovak:"ucitelka"},
{german:"machen",slovak:"robit"},
{german:"der Mann, PI. Männer",slovak:"muz"},
{german:"mein",slovak:"môj"},
{german:"der Meldezettel,",slovak:"prihlasovaci lístok"},
{german:"Muss ich noch etwas machen?",slovak:"Musím este nieco urobit?"},
{german:"müde",slovak:"unaveny"},
{german:"die Nähe, -n (in der Nähe)",slovak:"blízkost (v blizkosti)"},
{german:"der Name, -n",slovak:"meno"},
{german:"nennen (Nennen Sie mich Milan.)",slovak:"volat (Volajte ma Milan.)"},
{german:"nett",slovak:"mily"},
{german:"neu",slovak:"novy"},
{german:"niedrig",slovak:"nizky"},
{german:"null",slovak:"nula"},
{german:"Österreich",slovak:"Rakúsko"},
{german:"Passt dort alles?",slovak:"tu: Je tam vetko poriadku?"},
{german:"die Personalabteilung,-en",slovak:"personálne oddelenie"},
{german:"Polen",slovak:"Polsko"},
{german:"das Radio, -s",slovak:"rádio"},
{german:"das Regal, -e",slovak:"polica/regál"},
{german:"die Reise, -n",slovak:"cesta"},
{german:"richtig",slovak:"správne"},
{german:"ruhig",slovak:"pokojny"},
{german:"rund",slovak:"okrúhly"},
{german:"sauber",slovak:"cisty"},
{german:"sehr (sehr klein, sehr viel...)",slovak:"velmi (velmi maly, velmi vela...)"},
{german:"das Sekretariat, -e",slovak:"sekretariát"},
{german:"die Sekretärin, -nen",slovak:"sekretarka"},
{german:"Setzen Sie sich bitte.",slovak:"Posadte sa, prosím."},
{german:"das Schlafzimmer,-",slovak:"spálña"},
{german:"schmutzig",slovak:"Spinavy"},
{german:"schön",slovak:"pekny"},
{german:"siezen",slovak:"vykat si"},
{german:"die Slowakei (in der Slowakei)",slovak:"Slovensko (na Slovensku)"},
{german:"der Software-Entwickler, -",slovak:"softvérovy vyvojar"},
{german:"die Stadt, Pl. Städte",slovak:"mesto"},
{german:"der Stadtteil, -e",slovak:"mestská cast"},
{german:"studieren",slovak:"Studovat"},
{german:"der Stuhl, PI. Stühle",slovak:"stolicka"},
{german:"suchen (Wen suchen Sie?)",slovak:"hladat (Koho hiadáte?)"},
{german:"der Tag, -e (der erste Tag)",slovak:"den (prvy den)"},
{german:"die Tasse, -n",slovak:"sálka"},
{german:"tausend",slovak:"tisic"},
{german:"die Telefonnummer, -n (Wie ist Ihre Telefonnummer?)",slovak:"telefónne cislo (Aké je Vase telefónne dislo?)"},
{german:"der Teppich, -e",slovak:"koberec"},
{german:"der Tisch, -e",slovak:"stôl"},
{german:"die Tochter, PI. Töchter",slovak:"dcéra"},
{german:"Tschechien",slovak:"Cesko"},
{german:"die Türkei (in der Türkei)",slovak:"Turecko (v Turecku)"},
{german:"die Vase, -n",slovak:"váza"},
{german:"das Viertel,",slovak:"stvrt"},
{german:"die Vorwahl, -en",slovak:"predvolba"},
{german:"warten (auf jemanden)",slovak:"cakat (na niekoho)"},
{german:"weit",slovak:"daleko"},
{german:"wichtig",slovak:"dôlezity"},
{german:"Wie alt bist du?",slovak:"Kolko más rokov?"},
{german:"Wie geht es Ihnen?",slovak:"Ako sa mâte?"},
{german:"Wie ist die Adresse von...?",slovak:"Akú adresu má...?"},
{german:"Wie ist Ire Telefonnummer?",slovak:"Aké je Vase telefónne cislo?"},
{german:"Wie war die Reise?",slovak:"Aká bola cesta?"},
{german:"Wir können uns gerne duzen.",slovak:"Môzeme si tykat."},
{german:"wissen",slovak:"vediet"},
{german:"das Wohnheim, -e",slovak:"ubytovna"},
{german:"wohnen",slovak:"byvat"},
{german:"wollen",slovak:"chciet"},
{german:"zeigen",slovak:"ukázat"},
{german:"die Zeitschrift, -en",slovak:"casopis"},
{german:"die Zeitung, -en",slovak:"noviny"},
{german:"das Zimmer, - (im Zimmer, ins Zimmer)",slovak:"izba (v izbe, do izby)"},
{german:"zu Hause",slovak:"doma"},
{german:"der Zug, Pl. Züge (mit dem Zug)",slovak:"vlak (vlakom)"},
];