const listOfWords = [
{german:"abbiegen + akuzatív",slovak:"ohnút"},
{german:"die Achselhöhle,-n",slovak:"podpazusie"},
{german:"also",slovak:"takze"},
{german:"alt",slovak:"stary"},
{german:"das Alter, O (für ihr Alter)",slovak:"vek (na jej vek)"},
{german:"die Ampel, -n",slovak:"semafor"},
{german:"antworten + dativ",slovak:"odpovedat"},
{german:"die Apotheke, -n",slovak:"lekáren"},
{german:"der Appetit, O",slovak:"chut do jedla"},
{german:"der Arm, -e",slovak:"rameno"},
{german:"aufstehen (ich stehe auf, du stehst auf, er steht auf)",slovak:"vstávat (napr. ráno z postele)"},
{german:"das Auge, -n",slovak:"oko"},
{german:"die Augenbraue, -n",slovak:"obocie"},
{german:"aussehen (ich sehe aus, du siehst aus, er/sie/es sieht aus)",slovak:"vyzerat"},
{german:"die Autopapiere, Pl.",slovak:"papiere od auta"},
{german:"die Bäckerei, -en",slovak:"pekáren"},
{german:"das Badezimmer, -",slovak:"kúpelña"},
{german:"der Bahnhof, Pl. Bahnhöfe",slovak:"stanica (zelezniéná)"},
{german:"die Bank, -en",slovak:"banka"},
{german:"der Bauch, Pl. Bäuche",slovak:"brucho"},
{german:"die Bauchschmerzen (Pl.)",slovak:"bolesti brucha"},
{german:"beginnen mit + datív",slovak:"zacat s niecím"},
{german:"begrüßen + akuzatív",slovak:"pozdravit"},
{german:"das Bein, -e",slovak:"noha"},
{german:"bemühen sich (ich bemühe mich, du bemühst dich)",slovak:"snazit sa"},
{german:"bequem",slovak:"pohodlny"},
{german:"die Beschwerden, Pl.",slovak:"obtiaze"},
{german:"die Besprechung,-en",slovak:"porada"},
{german:"betrachten (das Gesicht betrachten)",slovak:"pozorovat (pozorovat tvár)"},
{german:"die Bewegung, -en",slovak:"pohyb"},
{german:"die Bezeichnung, -en",slovak:"oznacenie"},
{german:"billig",slovak:"lacny"},
{german:"der Blinddarm, Pl. Blinddärme",slovak:"slepé crevo"},
{german:"der Blutdruck, O",slovak:"krvny tlak"},
{german:"brauchen + akuzatív",slovak:"potrebovat"},
{german:"die Brille, -n",slovak:"okuliare"},
{german:"bringen",slovak:"priniest"},
{german:"die Brücke, -n",slovak:"most"},
{german:"die Brust, Pl. Brüste",slovak:"hrud"},
{german:"die Brustwarze, -n",slovak:"bradavka"},
{german:"bücken sich",slovak:"zohnút' sa"},
{german:"die Buchhandlung,-en",slovak:"knihkupectvo"},
{german:"der Busbahnhof, -höfe",slovak:"stanica (autobusová)"},
{german:"der Busen, -",slovak:"prsia"},
{german:"danken + datív (Ich danke dir/ihm.)",slovak:"dakovat (Dakujem ti/jemu.)"},
{german:"Das tut dir gut.",slovak:"To ti urobi dobre."},
{german:"Das wird alles wieder besser.",slovak:"To za opät zlepsi."},
{german:"dein",slovak:"tvoj"},
{german:"denn",slovak:"teda"},
{german:"der Dickdarm, -därme",slovak:"hrubé crevo"},
{german:"doch",slovak:"predsa"},
{german:"das Dorf, Pl. Dörfer",slovak:"dedina"},
{german:"dunkel",slovak:"tmavy"},
{german:"der Dünndarm, -därme",slovak:"tenké crevo"},
{german:"eigentlich",slovak:"vlastne"},
{german:"die Einbahnstraße, -n",slovak:"jednosmerná ulica"},
{german:"das Eis, O",slovak:"zmrzlina"},
{german:"der Ellbogen, -",slovak:"laket"},
{german:"erklären",slovak:"vysvetlit"},
{german:"erschöpft",slovak:"vycerpany"},
{german:"erst",slovak:"az"},
{german:"erst seit Kurzem",slovak:"len kratko"},
{german:"Es geht mir gut.",slovak:"Mám sa dobre./ Cítim sa dobre."},
{german:"essen + akuzativ",slovak:"jest"},
{german:"die Falte, -n",slovak:"vráska"},
{german:"faltig",slovak:"vráskavy"},
{german:"fehlen + datív (Meine Familie fehlt mir.)",slovak:"chybat (Chyba mi moja rodina.)"},
{german:"die Ferse, -n",slovak:"päta"},
{german:"das Fieber, O",slovak:"horúcka"},
{german:"finden + akuzatív",slovak:"nájst/povazovat"},
{german:"fleißig",slovak:"usilovny"},
{german:"fragen + akuzatív",slovak:"pytat sa"},
{german:"Milan geht es noch nicht besser.",slovak:"Milan sa este nemá lepsie."},
{german:"freundlich",slovak:"priatelsky"},
{german:"früh",slovak:"skoro"},
{german:"früher",slovak:"predtym"},
{german:"fühlen sich",slovak:"cítit sa"},
{german:"furchtbar",slovak:"hrozne"},
{german:"der Fuß, Pl. Füße",slovak:"chodidlo"},
{german:"die Gasse, -n",slovak:"ulicka"},
{german:"geben",slovak:"dat"},
{german:"gefallen + datív (Es gefällt mir.)",slovak:"pácit sa (Páci sa mi to.)"},
{german:"geheilt",slovak:"vylieceny"},
{german:"gehören + datív (Es gehört uns.)",slovak:"patrit (Patrí to nám.)"},
{german:"das Gelenk, -e",slovak:"klb"},
{german:"gerade",slovak:"práve"},
{german:"gern",slovak:"rad"},
{german:"das Gesäß",slovak:"zadok"},
{german:"das Geschäft, -e",slovak:"obchod"},
{german:"das Geschenk, -e",slovak:"darcek"},
{german:"die Geschlechtsteile",slovak:"genitálie"},
{german:"das Gesicht, -er",slovak:"tvár"},
{german:"gestern",slovak:"vcera"},
{german:"gleich",slovak:"hned"},
{german:"gratulieren + datív (Frau Fischer gratuliertihm/ihr.)",slovak:"gratulovat (Pani Fischer mu/jej gratuluje.)"},
{german:"grau",slovak:"sedivy"},
{german:"groß",slovak:"velky"},
{german:"gut",slovak:"dobry"},
{german:"das Haar, -e",slovak:"vlas"},
{german:"haben + akuzatív",slovak:"mat"},
{german:"der Hals, P1. Hälse",slovak:"krk"},
{german:"die Haltestelle, -n",slovak:"zastávka"},
{german:"die Hand, Pl. Hände",slovak:"ruka"},
{german:"das Handgelenk, -e",slovak:"zápästie"},
{german:"heben + akuzatív (das Bein heben)",slovak:"zdvihnut (zdvihnút nohu)"},
{german:"der Heimweg, -e",slovak:"cesta domov"},
{german:"helfen + datív (Er hilft Ihnen.)",slovak:"pomôct (Pomôze Vám.)"},
{german:"das Herz, -en",slovak:"srdce"},
{german:"heute",slovak:"dnes"},
{german:"hoch",slovak:"vysoky"},
{german:"holen",slovak:"vyzdvihnút"},
{german:"hören + akuzatív",slovak:"pocut"},
{german:"das Hotel, -s",slovak:"hotel"},
{german:"hübsch",slovak:"pekny"},
{german:"die Hüfte, -n",slovak:"bok"},
{german:"ihr",slovak:"jej"},
{german:"Ihr",slovak:"Vás (vykanie)"},
{german:"ihr",slovak:"vás"},
{german:"In Ordnung.",slovak:"V poriadku."},
{german:"jetzt",slovak:"teraz"},
{german:"jung",slovak:"mlady"},
{german:"kalt",slovak:"studeny"},
{german:"kaufen (Ich kaufe ihm etwas.)",slovak:"kúpit (Kúpim mu nieco.)"},
{german:"der Kindergarten, -gärten",slovak:"skôlka"},
{german:"das Kinn, -e",slovak:"brada"},
{german:"das Kino, -s",slovak:"kino"},
{german:"die Kirche, -n",slovak:"kostol"},
{german:"klein",slovak:"maly"},
{german:"das Knie, -",slovak:"koleno"},
{german:"der Knöchel, -",slovak:"clenok"},
{german:"der Knochen, -",slovak:"kost"},
{german:"der Kopf, Pl. Köpfe",slovak:"hlava"},
{german:"das Kopfweh",slovak:"bolesti hlavy"},
{german:"können (ich kann, du kannst, er/sie/ es kann",slovak:"vediet (nejakú zrucnost), môct"},
{german:"Ich kann schwimmen.",slovak:"Viem plávat."},
{german:"Ich kann hier nicht bleiben.",slovak:"Nemôzem tu zostat."},
{german:"der Körper, -",slovak:"telo"},
{german:"der Krankenstand; in Krankenstand gehen",slovak:"PN; ist' na PN, nechat sa vypísat (kvôli chorobe)"},
{german:"das Kreuz, -e",slovak:"krize (chrbat)"},
{german:"die Kreuzung, -en",slovak:"krizovatka"},
{german:"das Kreuzweh",slovak:"bolesti krizov"},
{german:"das Kreuzworträtsel,",slovak:"krízovka"},
{german:"lacheln",slovak:"usmievat sa"},
{german:"lang",slovak:"dlhy"},
{german:"die Leber, -n",slovak:"pecen"},
{german:"lesen + akuzatív",slovak:"čítať"},
{german:"lieb",slovak:"mily"},
{german:"die Lippe, -n",slovak:"pera"},
{german:"lösen",slovak:"riesit"},
{german:"die Lunge, -n",slovak:"plúca"},
{german:"die Lust, O",slovak:"chut"},
{german:"der Magen, PI. Mägen",slovak:"zalúdok"},
{german:"Mach dir keine Sorgen.",slovak:"Nerob si starosti."},
{german:"manchmal",slovak:"niekedy"},
{german:"der Marktplatz, -plätze",slovak:"trhovisko"},
{german:"das Medikament, -e",slovak:"liek"},
{german:"mein",slovak:"môj"},
{german:"der Mensch, -en",slovak:"clovek"},
{german:"das Mittagessen,-",slovak:"obed"},
{german:"der Mund, Pl. Münder",slovak:"ústa"},
{german:"müssen (ich muss, du musst, er/sie/es muss)",slovak:"musiet"},
{german:"der Nabel,",slovak:"pupok"},
{german:"der Nacken,",slovak:"zátylok"},
{german:"nah",slovak:"blizky"},
{german:"die Nase, -n",slovak:"nos"},
{german:"nehmen + akuzatív",slovak:"vziat"},
{german:"nie",slovak:"nikdy"},
{german:"die Niere, -n",slovak:"oblicka"},
{german:"nicht mehr",slovak:"uz nie"},
{german:"noch nicht",slovak:"este nie"},
{german:"normalerweise",slovak:"obycajne/zvycajne"},
{german:"der Oberschenkel,",slovak:"stehno"},
{german:"das Ohr,-en",slovak:"ucho"},
{german:"die Oper, -n",slovak:"opera"},
{german:"die Operation, -en",slovak:"operácia"},
{german:"die Ordnung, -en",slovak:"poriadok"},
{german:"der Park, -s",slovak:"park"},
{german:"pflegen + akuzatív",slovak:"starat sa o"},
{german:"der Platz, Pl. Plätze",slovak:"namestie"},
{german:"das Possessivpronomen,",slovak:"privlastnovacie zámeno"},
{german:"die Post, O",slovak:"posta"},
{german:"die Präsentation, -en",slovak:"prezentácia"},
{german:"das Rathaus, -häuser",slovak:"radnica"},
{german:"Red keinen Unsinn!",slovak:"Nehovor nezmysly!"},
{german:"reden",slovak:"hovorit"},
{german:"das Restaurant, -s",slovak:"restaurácia"},
{german:"rot",slovak:"cerveny"},
{german:"der Rücken, -",slovak:"chrbat"},
{german:"rufen + akuzativ",slovak:"volat"},
{german:"rund um",slovak:"okolo"},
{german:"die Sackgasse,-n",slovak:"slepá ulica"},
{german:"sagen",slovak:"povedat"},
{german:"die Sache, -n",slovak:"vec"},
{german:"sehen + akuzatív",slovak:"vidiet"},
{german:"sein",slovak:"jeho"},
{german:"seit einigen Tagen",slovak:"uz niekolko dni"},
{german:"seitdem",slovak:"odvtedy"},
{german:"selbst",slovak:"sám/ sama"},
{german:"schaffen",slovak:"zvládnut"},
{german:"schenken (Ich schenke dir in Buch.)",slovak:"darovat (Darujem ti knihu.)"},
{german:"das Schienbein, -e",slovak:"pistala"},
{german:"schlimm",slovak:"zly"},
{german:"schmecken + datív (Die Suppe schmeckt mir.)",slovak:"chutit (Polievka mi chuti.)"},
{german:"schmerzen",slovak:"boliet"},
{german:"schminken",slovak:"lícit (makeup)"},
{german:"schnell",slovak:"rychly"},
{german:"schön",slovak:"pekny"},
{german:"die Schule, -n",slovak:"skola"},
{german:"die Schulter, -n",slovak:"plece"},
{german:"schwarz",slovak:"cierny"},
{german:"schwierig",slovak:"tazky"},
{german:"sicher",slovak:"isty"},
{german:"sonnig",slovak:"slnecny"},
{german:"sonst",slovak:"ináč"},
{german:"später",slovak:"neskôr"},
{german:"der Spiegel, -",slovak:"zrkadlo"},
{german:"die Stadt, Pl. Städte",slovak:"mesto"},
{german:"das Stadtzentrum,-zentren",slovak:"centrum mesta"},
{german:"die Stirn, -en",slovak:"celo"},
{german:"die Straße, -n",slovak:"ulica"},
{german:"die Strecke, -n",slovak:"cesta"},
{german:"suchen + akuzatív",slovak:"hladat"},
{german:"der Supermarkt, -märkte",slovak:"supermarket"},
{german:"die Suppe, -n",slovak:"polievka"},
{german:"die Taille, -n",slovak:"driek, pás"},
{german:"teuer",slovak:"drahy"},
{german:"das Theater, -",slovak:"divadlo"},
{german:"der Tisch, -e",slovak:"stôl"},
{german:"trinken + akuzatív",slovak:"pit"},
{german:"trotzdem",slovak:"napriek tomu"},
{german:"unangenehm",slovak:"neprijemny"},
{german:"der Unfall, Pl. Unfälle",slovak:"nehoda"},
{german:"unser",slovak:"nás"},
{german:"der Unsinn, O",slovak:"nezmysel"},
{german:"der Unterarm, -e",slovak:"predlaktie"},
{german:"der Unterschenkel,",slovak:"predkolenie"},
{german:"unterwegs",slovak:"po/na ceste"},
{german:"die Verletzung, -en",slovak:"zranenie"},
{german:"verrückt",slovak:"bláznivy"},
{german:"verstehen",slovak:"rozumiet"},
{german:"viel",slovak:"vela"},
{german:"die Wade, -n",slovak:"lytko"},
{german:"die Wange, -n",slovak:"lice"},
{german:"warm",slovak:"teply"},
{german:"waschen (ich wasche, du wäschst, er/sie/es wäscht)",slovak:"umyvat"},
{german:"waschen + akuzativ",slovak:"umyvat"},
{german:"der Weg, -e",slovak:"cesta"},
{german:"weh tun (Die Beine tun mir weh.)",slovak:"boliet (Bolia ma nohy.)"},
{german:"weit",slovak:"daleko"},
{german:"weiter",slovak:"dalej"},
{german:"wenigstens",slovak:"aspon"},
{german:"wenn",slovak:"ked"},
{german:"werden (ich werde, du wirst, er/sie/ es wird)",slovak:"become/nastat"},
{german:"die Wimpern (Pl.)",slovak:"mihalnice"},
{german:"das Wochenende (am Wochenende)",slovak:"vikend (cez vikend)"},
{german:"der Zebrastreifen, -",slovak:"prechod pre chodcov"},
{german:"die Zeitung,-en",slovak:"noviny"},
{german:"die Zigarre,-n",slovak:"cigara"},
{german:"zuerst",slovak:"najprv"},
{german:"der Zug, Pl. Züge",slovak:"vlak"},
{german:"zurück",slovak:"spät"},
];