const listOfWords = [
{german:"die Abteilung, -en (in der Abteilung)",slovak:"oddelenie (na oddeleni)"},
{german:"alles",slovak:"vsetko"},
{german:"arbeiten",slovak:"pracovat"},
{german:"der Arzt, PI. Arzte",slovak:"lekar"},
{german:"auf Wiedersehen",slovak:"dovidenia"},
{german:"auch",slovak:"tiez"},
{german:"der Ausweis, -e",slovak:"preukaz (identifikacny)"},
{german:"die Arztin, Pl. Ärztinnen",slovak:"lekárka"},
{german:"der Bahnhof, Pl. Bahnhöfe (am Bahnhof)",slovak:"stanica (na stanici)"},
{german:"die Bäckerei, -en (in der Bäckerei)",slovak:"pekáren (v pekárni)"},
{german:"der Beruf, -e",slovak:"povolanie"},
{german:"das Bild, -er",slovak:"obrázok"},
{german:"bitte",slovak:"prosím"},
{german:"bitte schön",slovak:"nech sa páci"},
{german:"brauchen",slovak:"potrebovat"},
{german:"danke",slovak:"dakujem"},
{german:"Das ist alles.",slovak:"To je vsetko"},
{german:"Das sind dann 18,30 €.",slovak:"Spolu je to 18,30 €."},
{german:"Deutschland",slovak:"Nemecko"},
{german:"das Doppelzimmer",slovak:"dvojlözková izba"},
{german:"Ein Ticket nach Wien.",slovak:"Listok do Viedne."},
{german:"Entschuldigung",slovak:"prepácte"},
{german:"der Familienname",slovak:"priezvisko"},
{german:"das Formular, -e",slovak:"formulár"},
{german:"Gern geschehen.",slovak:"Rado sa stalo."},
{german:"gleich",slovak:"hned"},
{german:"Grüß Gott.",slovak:"Dobry den."},
{german:"gut",slovak:"dobre"},
{german:"Guten Morgen",slovak:"dobré ráno"},
{german:"Guten Tag",slovak:"dobry deñ"},
{german:"haben",slovak:"mat"},
{german:"Haben Sie eine Vorteilscard?",slovak:"Máte kartu vyhod?"},
{german:"Hallo",slovak:"dobry den/ahoj"},
{german:"heißen",slovak:"volat sa"},
{german:"der Herr",slovak:"pán"},
{german:"Herzlich willkommen in Graz.",slovak:"Srdecne Vás vítam v Grazi."},
{german:"hier",slovak:"tu"},
{german:"Hin und zurück?",slovak:"Spiatocny?"},
{german:"ich",slovak:"ja"},
{german:"Ich hätte gern.",slovak:"Chcel(a) by som.. (vobchode)"},
{german:"in (in Graz)",slovak:"v (v Grazi)"},
{german:"der Ingenieur, -e",slovak:"inzinier"},
{german:"ist",slovak:"je (3. osoba slovesa byt)"},
{german:"ja",slovak:"ano"},
{german:"jetzt",slovak:"teraz"},
{german:"Keine Ursache.",slovak:"Niet zac."},
{german:"der Kellner,",slovak:"casnik"},
{german:"das Kind, -er",slovak:"dieta"},
{german:"kommen aus",slovak:"pochádzat z (napr. mesta/státu)"},
{german:"der Lehrer,",slovak:"ucitel"},
{german:"links",slovak:"vlavo"},
{german:"der Mann, Pl. Männer",slovak:"muz"},
{german:"müde",slovak:"unaveny"},
{german:"nach Hause",slovak:"domov"},
{german:"der Name, -n",slovak:"meno"},
{german:"nein",slovak:"nie"},
{german:"Nur hin.",slovak:"Len jednosmerny."},
{german:"OK",slovak:"v poriadku"},
{german:"Österreich",slovak:"Rakúsko"},
{german:"der Prozesstechniker",slovak:"procesny technik"},
{german:"der Schlüssel, -",slovak:"klúc"},
{german:"sagen",slovak:"povedat"},
{german:"sein",slovak:"byt"},
{german:"die Semmel, -n",slovak:"Zemla"},
{german:"die Slowakei (in der Slowakei; aus der Slowakei)",slovak:"Slovensko (na Slovensku; zo Slovenska)"},
{german:"So",slovak:"tak"},
{german:"der Software-Entwickler, -",slovak:"softvérovy vyvojár"},
{german:"das Ticket, -s",slovak:"cestovny lístok"},
{german:"der Ticketverkäufer",slovak:"predavac listkov"},
{german:"Und sonst noch was?",slovak:"A este nieco?"},
{german:"die Verkäuferin, -nen",slovak:"predavacka"},
{german:"das Vollkornbrot, -e",slovak:"celozrnny chlieb"},
{german:"der Vorname, -n",slovak:"krstné meno"},
{german:"wann",slovak:"kedy"},
{german:"warum",slovak:"preco"},
{german:"was",slovak:"co"},
{german:"Was darf's denn sein?",slovak:"Co to bude? (v obchode)"},
{german:"Was kann ich für Sie tun?",slovak:"Co mozem pre Vás urobit?"},
{german:"Was sind Sie von Beruf?",slovak:"Aké je Vase zamestnanie?"},
{german:"welche",slovak:"aké"},
{german:"wer",slovak:"kto"},
{german:"wie",slovak:"aky/aká/aké"},
{german:"Wie geht es Ihnen?",slovak:"Ako sa máte?"},
{german:"Wie ist Ihr Familienname?",slovak:"Aké je Vase priezvisko?"},
{german:"Wie ist Ihr Vorname?",slovak:"Aké je Vase meno?"},
{german:"wie lange",slovak:"ako dlho"},
{german:"Wie sagt man das auf Deutsch?",slovak:"Ako sa to povie po nemecky?"},
{german:"wo",slovak:"kde"},
{german:"woher",slovak:"odkial"},
{german:"Woher kommen Sie?",slovak:"Odkial pochadzate?"},
{german:"wohin",slovak:"kam"},
{german:"wohnen",slovak:"byvat"},
{german:"das Wohnheim, -e (im Wohnheim)",slovak:"ubytovna (v ubytovni)"},
{german:"zehn",slovak:"desat"},
{german:"die Zimmernummer, -n",slovak:"cislo izby"},
{german:"zu Hause",slovak:"doma"},
{german:"zurück",slovak:"(na)spät"},
];