const listOfWords = [
{german:"abbiegen",slovak:"pokrcit (napr. kolená)"},
{german:"alle",slovak:"vsetky"},
{german:"als",slovak:"ako"},
{german:"die Angst, Pl. Ängste",slovak:"strach"},
{german:"anstrengend",slovak:"namáhavy"},
{german:"das Anziehen, O",slovak:"obliekanie"},
{german:"anziehen (sich), (ich ziehe mich an, du ziehst dich an)",slovak:"obliect sa"},
{german:"der Apfelstrudel,",slovak:"jablková strúdla"},
{german:"die Apotheke, -n",slovak:"lekáren"},
{german:"arm",slovak:"úbohy"},
{german:"der Arm, -e",slovak:"rameno"},
{german:"atmen",slovak:"dychat"},
{german:"aufregend",slovak:"vzrusujúci"},
{german:"aufstehen (ich stehe auf, du stehst auf)",slovak:"vstat (napr. z postele)"},
{german:"ausziehen (sich), (ich ziehe mich aus, du ziehst dich aus)",slovak:"vyzliect sa"},
{german:"backen",slovak:"piect"},
{german:"der Bademeister, O",slovak:"plavcik"},
{german:"das Badezimmer,-",slovak:"kúpelna"},
{german:"die Bar, -S",slovak:"bar"},
{german:"bauen",slovak:"stavat"},
{german:"der Bauch, Pl. Bäuche",slovak:"brucho"},
{german:"bedienen",slovak:"obsluhovat"},
{german:"beginnen",slovak:"zacat"},
{german:"bekommen",slovak:"dostat"},
{german:"besonders",slovak:"obzvlást"},
{german:"der Besuch, -e",slovak:"návsteva"},
{german:"besuchen",slovak:"navstívit"},
{german:"die Beschwerde, -n",slovak:"problémy (zdravotné)"},
{german:"das Bett, -en",slovak:"postel"},
{german:"bevor",slovak:"skôr nez"},
{german:"bewegen (sich), (ich bewege mich, du bewegst dich)",slovak:"hybat sa/pohybovat sa"},
{german:"bitten",slovak:"prosit"},
{german:"bleiben",slovak:"zostat"},
{german:"der Braune, -n",slovak:"káva s mliekom (v Rakúsku)"},
{german:"brechen (sich), (ich breche mir...; du brichst dir.., )",slovak:"zlomit si"},
{german:"brennen",slovak:"stípat/pálit"},
{german:"das Brot, -e",slovak:"chlieb"},
{german:"bücken (sich), (ich bücke mich, du bückst dich)",slovak:"zohnút sa"},
{german:"das Büro, -S",slovak:"kancelária"},
{german:"die Butter, O",slovak:"maslo"},
{german:"die Couch, -s",slovak:"gauc"},
{german:"das heißt",slovak:"to znamená"},
{german:"dazu",slovak:"k tomu"},
{german:"deshalb",slovak:"preto"},
{german:"draußen",slovak:"vonku"},
{german:"(um)drehen (sich)",slovak:"otocit sa"},
{german:"der Durst, O",slovak:"smäd"},
{german:"dürfen (ich darf, du darfst)",slovak:"smiet"},
{german:"duschen (sich)",slovak:"osprchovat' sa"},
{german:"eigentlich",slovak:"vlastne"},
{german:"ein paar",slovak:"niekolko"},
{german:"einfach",slovak:"jednoducho"},
{german:"eingeschaltet",slovak:"zapnuty"},
{german:"einige",slovak:"niekolki"},
{german:"das Einkaufen, O",slovak:"nakupovanie"},
{german:"erhöht",slovak:"zvyseny"},
{german:"erholen (sich)",slovak:"oddychnut' si"},
{german:"erinnern (sich) (an + akuzatív), ich erinnere mich an den Sommer",slovak:"spomenút si (na), spomínam si na leto"},
{german:"erst",slovak:"az"},
{german:"erzählen",slovak:"rozprávat"},
{german:"essen (ich esse, du isst)",slovak:"jest"},
{german:"fahren",slovak:"íst (autom, vlakom, autobusom)"},
{german:"die Familie, -n",slovak:"rodina"},
{german:"das Fenster, -",slovak:"okno"},
{german:"der Fernseher, -",slovak:"televizor"},
{german:"das Fernstudium, O",slovak:"externé stúdium"},
{german:"finden",slovak:"najst"},
{german:"fleckig",slovak:"flakaty"},
{german:"die Frage, -n",slovak:"otázka"},
{german:"frei",slovak:"volny"},
{german:"das Freibad, Pl. Freibäder",slovak:"kúpalisko"},
{german:"die Freundin, -nen",slovak:"kamarátka"},
{german:"die Früh (in der Früh)",slovak:"ráno (ráno)"},
{german:"früher",slovak:"minulost"},
{german:"fühlen (sich), ich fühle mich gut",slovak:"cítit (sa), cítim sa dobre"},
{german:"furchtbar",slovak:"hrozne"},
{german:"gar nicht",slovak:"vôbec nie"},
{german:"der Garten, Pl. Gärten",slovak:"záhrada"},
{german:"der Gast, Pl. Gäste",slovak:"host"},
{german:"das Gästebadezimmer,",slovak:"hostovska kúpelña"},
{german:"das Gehen, O",slovak:"chodenie"},
{german:"gelb",slovak:"zlty"},
{german:"genug",slovak:"dost"},
{german:"die Gemüsesuppe, -n",slovak:"zeleninová polievka"},
{german:"das Gesicht, -er",slovak:"tvár"},
{german:"gestern",slovak:"vcera"},
{german:"das Gewicht, O",slovak:"hmotnost"},
{german:"gießen",slovak:"polievat"},
{german:"glauben",slovak:"mysliet"},
{german:"grün",slovak:"zeleny"},
{german:"hässlich",slovak:"nepekny/otrasny"},
{german:"heben",slovak:"zdvihnút"},
{german:"heilen",slovak:"hojit sa"},
{german:"heiser",slovak:"zachripnuty"},
{german:"hinzukommen (etwas kommt hinzu)",slovak:"pridat sa (nieco sa pridá)"},
{german:"das Holz, O",slovak:"drevo"},
{german:"hübsch",slovak:"pekny"},
{german:"der Hunger, O",slovak:"hlad"},
{german:"immer",slovak:"vzdy"},
{german:"jetzt",slovak:"teraz"},
{german:"der Job, -s",slovak:"práca"},
{german:"jucken",slovak:"svrbiet"},
{german:"der Jugendliche, -n",slovak:"mladistvy"},
{german:"das Kindercamp,-S",slovak:"detsky tábor"},
{german:"die Kirsche, -n",slovak:"ceresna"},
{german:"die Klimaanlage,-n",slovak:"klimatizacia"},
{german:"die Köchin, -nen",slovak:"kucharka"},
{german:"kommen",slovak:"príst"},
{german:"konnte (minuly cas od slovesa können)",slovak:"mohol"},
{german:"die Kopfschmerzen (Pl.)",slovak:"bolesti hlavy"},
{german:"krank",slovak:"chory"},
{german:"kümmern (sich) um + akuzativ (Sie kümmert sich um den kranken Mann.)",slovak:"starat sa o niekoho (Stará sa o chorého muza.)"},
{german:"legen (sich), wir legen uns ins Bett",slovak:"lahnut si, lahneme si do postele"},
{german:"leiden unter",slovak:"trpiet niecim"},
{german:"das Lernen, O",slovak:"ucenie"},
{german:"lesen",slovak:"citat"},
{german:"letzte Woche",slovak:"minuly tyzden"},
{german:"das Lieblingscafé, -s",slovak:"oblúbená kaviaren"},
{german:"die Lieblingsmehlspeise,-n",slovak:"oblübeny mucnik"},
{german:"liegen",slovak:"lezat"},
{german:"das Mädchen, O",slovak:"dievca"},
{german:"der Mann, Pl. Männer",slovak:"muz"},
{german:"der Maurer, O",slovak:"murár"},
{german:"mehrmals",slovak:"viackrat"},
{german:"merken (sich), (ich merke mir, ...)",slovak:"zapamätat si"},
{german:"mit",slovak:"s(so)"},
{german:"das Mittagessen,",slovak:"obed"},
{german:"möglich",slovak:"mozny"},
{german:"der Mohn, O",slovak:"mak"},
{german:"nach oben",slovak:"hore"},
{german:"das Nachthemd,-en",slovak:"nocná kosela"},
{german:"das Nasenbluten, O",slovak:"krvacanie z nosa"},
{german:"nämlich",slovak:"totiz"},
{german:"nehmen",slovak:"vziat"},
{german:"nett",slovak:"mily"},
{german:"oben",slovak:"hore"},
{german:"die Ohrenschmerzen (PL.)",slovak:"bolesti usi"},
{german:"der Patient, -en",slovak:"pacient"},
{german:"Pro Nacht",slovak:"za noc"},
{german:"putzen",slovak:"cistit"},
{german:"der Rauch, O",slovak:"dym"},
{german:"das Rauchverbot, -e",slovak:"zákaz fajcit"},
{german:"rausschmeißen jn./etw.",slovak:"vyhodit niekoho/niedo"},
{german:"reden",slovak:"rozprávat"},
{german:"regeln",slovak:"riadit"},
{german:"richtig (richtige Arbeit)",slovak:"poriadny (poriadna práca)"},
{german:"schmuggeln",slovak:"prepasovat"},
{german:"seit längerer Zeit",slovak:"dlhsi cas"},
{german:"seitdem",slovak:"odvtedy"},
{german:"selbstständig",slovak:"samostatne zárobkovo cinny"},
{german:"setzen (sich)",slovak:"sadnút' si"},
{german:"schaffen",slovak:"zvládnut"},
{german:"schämen (sich)",slovak:"hanbit sa"},
{german:"schlafen",slovak:"spat"},
{german:"schlagen (ich schlage; du schlägst;)",slovak:"tlct"},
{german:"der Schlagobers, O",slovak:"slahacka"},
{german:"schlecht",slovak:"zly"},
{german:"schneiden",slovak:"krajat/rezat"},
{german:"schnell",slovak:"rychlo"},
{german:"schwer",slovak:"fazky"},
{german:"Sie hatte viel zu tun.",slovak:"Mala vela roboty."},
{german:"der Spaß, O",slovak:"zábava"},
{german:"spät",slovak:"neskoro"},
{german:"spazieren gehen",slovak:"íst na prechádzku"},
{german:"sprechen über + akuzativ (ich spreche, du sprichst)",slovak:"hovorit o niecom/niekom"},
{german:"die Stelle, -n",slovak:"miesto (pracovné)"},
{german:"stellen (sich)",slovak:"postavit sa"},
{german:"stören",slovak:"vadit"},
{german:"Und der Rauch von den Zigaretten hat dich nicht gestört?",slovak:"A cigaretovy dym ti nevadil?"},
{german:"die Streife, -n",slovak:"hliadka (policajná)"},
{german:"stresovy",slovak:"stressig"},
{german:"der Stuhl, PI. Stühle",slovak:"stolicka"},
{german:"die Stunde, -n",slovak:"hodina"},
{german:"stur",slovak:"tvrdohlavy"},
{german:"stützen",slovak:"podopierat"},
{german:"täglich",slovak:"denne"},
{german:"der Tee, Pl. Teesorten",slovak:"caj"},
{german:"der Tisch, -e",slovak:"stôl"},
{german:"treffen (sich) mit jemandem, (ich treffe mich mit.., du triffst dich mit.…;)",slovak:"stretnut sa s niekym"},
{german:"das Trinkgeld, -er",slovak:"prepitné"},
{german:"trotzdem",slovak:"napriek tomu"},
{german:"übel (Mir ist übel.)",slovak:"zle (Je mi zle.)"},
{german:"überall",slovak:"vsade"},
{german:"die Überstunden (Pl.)",slovak:"nadcasy"},
{german:"umziehen (sich), (ich ziehe mich um, du ziehst dich um)",slovak:"prezliect sa"},
{german:"unangenehm",slovak:"neprijemny"},
{german:"unklar",slovak:"nejasny"},
{german:"unterhalten (sich) mit jemandem, (ich unterhalte mich mit..; du unterhältst dich mit..;)",slovak:"s niekym bavit sa"},
{german:"die Vase, -n",slovak:"váza"},
{german:"verbringen",slovak:"strávit (napr. cas)"},
{german:"verfolgen",slovak:"prenasledovat"},
{german:"vergessen",slovak:"zabudnút"},
{german:"der Verkehr, O",slovak:"premávka"},
{german:"verschieden",slovak:"rozlicny"},
{german:"verschreiben",slovak:"predpísat (napr. liek)"},
{german:"verwirrt",slovak:"zmäteny"},
{german:"viel",slovak:"vela"},
{german:"vielleicht",slovak:"mozno"},
{german:"vor",slovak:"pred"},
{german:"vor ein paar Wochen",slovak:"pred pár tyzdnami"},
{german:"Was felt Ihnen?",slovak:"Co Vam je?"},
{german:"Was ist los?",slovak:"Co sa deje?"},
{german:"waschen (sich), (ich wasche mich, du wäschst dich)",slovak:"umyt sa"},
{german:"das Wasser, O",slovak:"voda"},
{german:"wegnehmen",slovak:"vziat nieco (niekomu)"},
{german:"wechseln",slovak:"vymienat"},
{german:"wieder",slovak:"opät"},
{german:"wieso",slovak:"ako to"},
{german:"wirklich",slovak:"skutocne"},
{german:"die Woche, -n",slovak:"tyzden"},
{german:"wollen (ich will, du willst)",slovak:"chciet"},
{german:"wollten (ich wollte, du wolltest)",slovak:"chcel som (minuly cas)"},
{german:"zubereiten (ich bereite zu, du bereitest zu)",slovak:"pripravit"},
];