const listOfWords = [
{german:"der Abstellraum, Pl. Abstellräume",slovak:"sklad, komora"},
{german:"das Altpapier, -e",slovak:"stary papier"},
{german:"an",slovak:"pri, k"},
{german:"ansehen sich; sich die Nachrichten ansehen",slovak:"pozriet si; pozriet' si spravy"},
{german:"das Arbeitszimmer,-",slovak:"pracovna"},
{german:"auf",slovak:"na"},
{german:"aufräumen",slovak:"upratovat"},
{german:"das Aufräumen, O",slovak:"upratovanie"},
{german:"der Ausflug, Pl. Ausflüge",slovak:"vylet"},
{german:"der Autoabstellplatz, Pl. Autoabstellplätze",slovak:"parkovacie miesto"},
{german:"das Badezimmer,-",slovak:"kúpelna"},
{german:"der Bahnhof, Pl. Bahnhöfe (am Bahnhof)",slovak:"stanica (na stanici)"},
{german:"beginnen",slovak:"zacat"},
{german:"beide",slovak:"obidvaja"},
{german:"das Bett, -en",slovak:"postel"},
{german:"der Bildschirm, -e",slovak:"monitor"},
{german:"bleiben",slovak:"zostat"},
{german:"die Blume, -n",slovak:"kvet"},
{german:"der Boden, Pl. Böden",slovak:"podlaha"},
{german:"der Computer, -",slovak:"pocitac"},
{german:"der Couchtisch, -e",slovak:"konferenny stolik"},
{german:"der Dachboden, PI. Dachböden",slovak:"povala"},
{german:"dazu",slovak:"k tomu"},
{german:"dekorieren",slovak:"zdobit"},
{german:"den ganzen Tag",slovak:"cely den"},
{german:"das Ding, -e",slovak:"vec"},
{german:"der Drucker, -",slovak:"tlaciaren"},
{german:"duschen",slovak:"sprchovat' sa"},
{german:"die Ecke, -n",slovak:"roh"},
{german:"ein bisschen",slovak:"trocha"},
{german:"einkaufen",slovak:"nakupovat"},
{german:"das Erdgeschoss,-e",slovak:"prízemie"},
{german:"Es gibt + akuzativ (4. pád)...; Napr. Es gibt dort einen Tisch, eine Lampe, ein Buch",slovak:"Je tam... (Napr. Je tam stôl, lampa, kniha)"},
{german:"essen",slovak:"jest"},
{german:"der Esstisch, -e",slovak:"jedálensky stôl"},
{german:"das Esszimmer,",slovak:"jedálen"},
{german:"der Fernseher, -",slovak:"televízor"},
{german:"fertig",slovak:"hotovy"},
{german:"der Flur, -e",slovak:"chodba"},
{german:"freuen - sich freuen (ich freue mich, du freust dich)",slovak:"tesit sa"},
{german:"frisch",slovak:"cerstvy"},
{german:"die Früh, in der Früh",slovak:"rano"},
{german:"früher",slovak:"minulosti"},
{german:"das Frühstück, O",slovak:"ranajky"},
{german:"die Garderobe, -n",slovak:"satnik"},
{german:"der Garten, Pl. Gärten",slovak:"záhrada"},
{german:"das Gästezimmer,",slovak:"hostovská izba"},
{german:"gestern",slovak:"vcera"},
{german:"das Haus, Pl. Häuser",slovak:"dom"},
{german:"das Haustier, -e",slovak:"domáce zviera"},
{german:"hängen",slovak:"visiet"},
{german:"helfen",slovak:"pomôct"},
{german:"herrschen",slovak:"vládnut"},
{german:"heute",slovak:"dnes"},
{german:"hinstellen (ich stelle hin, du stellst hin)",slovak:"postavit"},
{german:"hinter",slovak:"za"},
{german:"der Hund, -e",slovak:"pes"},
{german:"die Hundehütte, -n",slovak:"búda pre psa"},
{german:"der Hunger, O",slovak:"hlad"},
{german:"in",slovak:"v, do"},
{german:"sich interessieren für etw.",slovak:"zaujímat sa o nieco"},
{german:"die Katze, -n",slovak:"macka"},
{german:"der Keller,",slovak:"pivnica"},
{german:"das Kissen,",slovak:"vankús"},
{german:"kochen",slovak:"varit"},
{german:"kommen",slovak:"prist, pochádzat"},
{german:"die Kopfschmerzen (PL.)",slovak:"bolesti hlavy"},
{german:"die Küche, -n",slovak:"kuchyna"},
{german:"legen",slovak:"polozit"},
{german:"lesen (ich lese, du liest)",slovak:"citat"},
{german:"liegen",slovak:"lezat"},
{german:"der Mantel, Pl. Mäntel",slovak:"kabat"},
{german:"mögen (ich mag, du magst)",slovak:"mat rad"},
{german:"müde",slovak:"unaveny"},
{german:"nach oben",slovak:"hore"},
{german:"die Nachrichten (PL.)",slovak:"správy"},
{german:"neben",slovak:"vedla"},
{german:"nervös",slovak:"nervózny"},
{german:"nett",slovak:"mily"},
{german:"ordentlich",slovak:"upratany"},
{german:"der Ordner, -",slovak:"zakladac"},
{german:"putzen",slovak:"upratovat, cistit"},
{german:"reden über + 4. pad",slovak:"hovorit o niecom"},
{german:"das Regal, -e",slovak:"polica/regál"},
{german:"riesig",slovak:"obrovsky"},
{german:"rund",slovak:"okolo"},
{german:"sehen (ich sehe, du siehst)",slovak:"vidiet"},
{german:"sehr",slovak:"velmi"},
{german:"das Schlafzimmer,-",slovak:"spálña"},
{german:"sitzen",slovak:"sediet"},
{german:"das Sofa, -s",slovak:"sedacka"},
{german:"der Spaß, Pl. Späße",slovak:"zábava"},
{german:"die Speisekammer, -n",slovak:"spajza"},
{german:"der Spiegel, -",slovak:"zrkadlo"},
{german:"die Spielsachen (PL.)",slovak:"hracka"},
{german:"der Stadtrand, O",slovak:"okraj mesta"},
{german:"staubig",slovak:"prasno"},
{german:"stehen",slovak:"stat"},
{german:"stellen",slovak:"postavit"},
{german:"der Stock (Wir wohnen im 3. Stock.)",slovak:"poschodie (Byvame na 3. poschodí.)"},
{german:"das Stockwerk, -e",slovak:"poschodie"},
{german:"stören",slovak:"vyrusovat"},
{german:"der Stuhl, PI. Stühle",slovak:"stolicka"},
{german:"die Tastatur,-en",slovak:"klávesnica"},
{german:"die Terrasse, -n",slovak:"terasa"},
{german:"der Tisch, -e",slovak:"stôl"},
{german:"die Toilette, -n",slovak:"toaleta"},
{german:"trinken",slovak:"pit"},
{german:"tun (ich tue, du tust, er/sie/es tut)",slovak:"robit"},
{german:"über",slovak:"nad"},
{german:"die Unordnung, O",slovak:"neporiadok"},
{german:"unter",slovak:"pod"},
{german:"sich unterhalten mit jm./über etw.",slovak:"bavit' sa s niekym/o niecom"},
{german:"Sophie unterhält sich mit Milan über die Arbeit.",slovak:"Sophie sa bavi s Milanom o práci."},
{german:"die Unterlagen (PL.)",slovak:"podklady"},
{german:"die Vase, -n",slovak:"váza"},
{german:"verschieden",slovak:"rozlicny"},
{german:"viel zu tun haben (Ich habe viel zu tun.)",slovak:"mat vela roboty (Mám vela roboty.)"},
{german:"der Vogel, Pl. Vögel",slovak:"vták"},
{german:"vor",slovak:"pred"},
{german:"der Vorgarten, Pl. Vorgärten",slovak:"predzahrádka"},
{german:"der Vorraum, Pl. Vorräume",slovak:"predsien"},
{german:"die Wand, Pl. Wände",slovak:"stena"},
{german:"das Haus, Pl. Häuser",slovak:"dom"},
{german:"die Wohnung, -en",slovak:"byt"},
{german:"das Dach, Pl. Dächer",slovak:"strecha"},
{german:"die Mauer, -n",slovak:"múr"},
{german:"das Fenster,",slovak:"okno"},
{german:"die Haustür, -en",slovak:"vstupné dvere"},
{german:"das Einfamilienhaus, Pl. -häuser",slovak:"rodinny dom"},
{german:"die Garage, -n",slovak:"garáz"},
{german:"das Stockwerk, -e",slovak:"poschodie"},
{german:"Das Bad ist im ersten Stock.",slovak:"Kúpelña je na prvom poschodí."},
{german:"das Erdgeschoss, -e",slovak:"prizemie"},
{german:"Das Esszimmer ist im Erdgeschoss.",slovak:"Jedálen je na prízemí."},
{german:"der Dachboden, Pl. -böden",slovak:"podkrovie"},
{german:"waren (minuly cas od slovesa sein)",slovak:"boli (minuly cas od slovesa byt)"},
{german:"das WC, -s",slovak:"WC"},
{german:"weglaufen (ich laufe weg, du läufst weg, er/sie/es läuft weg)",slovak:"utiect"},
{german:"weil",slovak:"pretoze"},
{german:"wenn",slovak:"ked"},
{german:"das Wetter, O",slovak:"pocasie"},
{german:"das Wohngebiet, -e",slovak:"obytná zóna"},
{german:"das Wohnzimmer,-",slovak:"obyvacka"},
{german:"zeigen",slovak:"ukazovat"},
{german:"die Zeitung, -en",slovak:"noviny"},
{german:"ziemlich",slovak:"dost"},
{german:"zuerst",slovak:"najprv"},
{german:"zufrieden",slovak:"spokojny"},
{german:"die Zugfahrt, -en",slovak:"cesta vlakom"},
{german:"zwischen",slovak:"medzi"},
{german:"der Briefkasten, Pl. -kästen",slovak:"postová schránka"},
{german:"die Terrasse, -n",slovak:"terasa"},
{german:"der Balkon, -e",slovak:"balkón"},
{german:"der Keller, -",slovak:"pivnica"},
{german:"das Zimmer,",slovak:"izba"},
{german:"der Garten, Pl. Gärten",slovak:"záhrada"},
{german:"der Eingang, Pl. Eingänge",slovak:"vchod"},
{german:"die Treppe, -n",slovak:"schodisko"},
{german:"die Türklingel, -n",slovak:"zvoncek"},
{german:"die Fußmatte, -n",slovak:"rohozka"},
{german:"das Schloss, Pl. Schlösser",slovak:"zámok"},
{german:"der Schlüssel,",slovak:"klüc"},
{german:"der Lift, -e",slovak:"vytah"},
{german:"der Vorraum, Pl. Vorräume",slovak:"predsien"},
{german:"das Wohnzimmer, -",slovak:"obyvacka"},
{german:"das Schlafzimmer,",slovak:"spálña"},
{german:"das Badezimmer,",slovak:"kúpelña"},
{german:"das Kinderzimmer,-",slovak:"detska izba"},
{german:"das Gästezimmer,",slovak:"hostovská izba"},
{german:"das Arbeitszimmer,",slovak:"pracovna"},
{german:"die Speisekammer,-n",slovak:"Spajza"},
{german:"das WC, -s / das Klo, -s",slovak:"záchod"},
{german:"die Heizung, -en",slovak:"kúrenie"},
{german:"die Glühbirne, -n",slovak:"ziarovka"},
{german:"die Steckdose, -n",slovak:"zásuvka"},
{german:"der Schalter, -",slovak:"vypínad"},
{german:"der Staubsauger,",slovak:"vysávac"},
{german:"der Besen,",slovak:"metla"},
{german:"der Eimer, - (Ö: der Kübel, - )",slovak:"vedro"},
{german:"beeindruckt",slovak:"ohromeny"},
{german:"überall",slovak:"all over"},
];