const listOfWords = [
{german:"als",slovak:"ked (jednorazovy dej v minulosti)"},
{german:"am Wochenende",slovak:"cez víkend"},
{german:"anstrengend",slovak:"namáhavy"},
{german:"ausborgen (sich) (ich borge mir aus, du borgst dir aus, er/sie/es borgt sich aus)",slovak:"pozicat si nieco"},
{german:"der Ausflug, Pl. Ausflüge",slovak:"vylet"},
{german:"die Ballsportart, -en",slovak:"loptovy sport"},
{german:"der Basketball, Pl. -bälle (Basketball spielen)",slovak:"basketbal"},
{german:"das Bauernhaus, Pl. - häuser",slovak:"gazdovsky dom"},
{german:"behalten",slovak:"udrzat (si)"},
{german:"besichtigen",slovak:"pozriet si"},
{german:"die Besonderheit, -en",slovak:"zvlástnost"},
{german:"der Besuch, -e",slovak:"návsteva"},
{german:"die Bewegung, -en",slovak:"pohyb"},
{german:"brav",slovak:"poslusny"},
{german:"cool",slovak:"perfektny, úzasny"},
{german:"dazwischen kommen (etwas kommt dazwischen)",slovak:"tu: niedo mi príde do toho"},
{german:"deshalb",slovak:"preto"},
{german:"dunkel",slovak:"tmavy"},
{german:"das Eis, O",slovak:"zmrzlina"},
{german:"die Eltern (PI.)",slovak:"rodicia"},
{german:"Federball spielen",slovak:"hrat bedminton"},
{german:"fertig machen + akuzativ (ich muss etwas fertig machen)",slovak:"dokoncit"},
{german:"die Figur, -en",slovak:"postava"},
{german:"die Firma, Pl. Firmen",slovak:"firma"},
{german:"das Fitnesscenter, -",slovak:"fitnescentrum"},
{german:"das Freilichtmuseum, PI. - museen",slovak:"skanzen"},
{german:"freinehmen (sich) (ich nehme mir frei, du nimmst dir frei, er/siel es nimmt sich freii)",slovak:"zobrat si volno"},
{german:"die Freizeit, O",slovak:"volny"},
{german:"das freuen (sich), (ich freue mich, du freust dich, er freut sich)",slovak:"tesit sa"},
{german:"der Garten, Pl. Gärten",slovak:"záhrada"},
{german:"gefallen (das gefällt mir)",slovak:"pácit sa (páci sa mi to)"},
{german:"gelungen",slovak:"vydareny"},
{german:"gemeinsam",slovak:"spolocny"},
{german:"genießen",slovak:"vychutnávat' si"},
{german:"gern",slovak:"rád"},
{german:"das Hallenbad, Pl. Hallenbäder",slovak:"krytá plaváren"},
{german:"Handball spielen",slovak:"hrat hádzanú"},
{german:"die Heimat, 0",slovak:"domov"},
{german:"das Hobby,-s",slovak:"konícek"},
{german:"in der Freizeit",slovak:"vo volnom case"},
{german:"in der Nacht",slovak:"v noci"},
{german:"joggen",slovak:"behat"},
{german:"die Jugendlichen (PI.)",slovak:"mladistvi"},
{german:"klappen (es klappt)",slovak:"podarit sa"},
{german:"krank",slovak:"chory"},
{german:"leiten (z.B. eine Firma)",slovak:"viest (napr. firmu)"},
{german:"die Luft, O",slovak:"vzduch"},
{german:"manchmal",slovak:"niekedy"},
{german:"meistens",slovak:"väcsinou"},
{german:"miteinander",slovak:"spolu"},
{german:"möglichst",slovak:"podla moznosti"},
{german:"nachdenken, über + akuzativ (ich denke über die Arbeit nach)",slovak:"premyslat o niecom"},
{german:"natürlich",slovak:"prirodzene"},
{german:"oft",slovak:"casto"},
{german:"pflegen",slovak:"starat sa (o niekoho)"},
{german:"plaudern",slovak:"rozprávat sa"},
{german:"Rad fahren",slovak:"jazdit na bicykli"},
{german:"der Radweg,-e",slovak:"cyklistická cesta"},
{german:"regelmäßig",slovak:"pravidelne"},
{german:"die Rutsche, -n",slovak:"smyklavka"},
{german:"das Schloss, Pl. Schlösser",slovak:"zamok"},
{german:"das Segeln, 0",slovak:"jachtanie"},
{german:"sehr oft",slovak:"casto"},
{german:"seit",slovak:"odkedy"},
{german:"Ski fahren",slovak:"lyzovat"},
{german:"der Spaß, 0",slovak:"zábava"},
{german:"spazieren gehen",slovak:"ist na prechádzku"},
{german:"der Spaziergang, Pl. Spaziergänge",slovak:"prechádzka"},
{german:"Sport machen",slovak:"Sportovat"},
{german:"sportlich",slovak:"sportovy"},
{german:"springen",slovak:"skákat"},
{german:"der Tag, -e",slovak:"den"},
{german:"täglich",slovak:"denne"},
{german:"die Tochter, Pl. Töchter",slovak:"dcéra"},
{german:"toll",slovak:"vynikajúci"},
{german:"trauen (sich)",slovak:"odvázit sa"},
{german:"unter der Woche",slovak:"cez tyzden"},
{german:"unternehmen",slovak:"podniknút (nieco)"},
{german:"unternehmen (wir unternehmen etwas)",slovak:"podniknút nieco (podnikneme nieco)"},
{german:"unterstützen",slovak:"podporovat (nieco/niekoho)"},
{german:"verbringen",slovak:"strávit (napr. cas)"},
{german:"vereinbaren + akuzatív",slovak:"dohodnút nieco"},
{german:"verlassen",slovak:"opustit (nieco/niekoho)"},
{german:"versuchen",slovak:"skusit"},
{german:"Volleyball spielen",slovak:"hrat volejbal"},
{german:"das Volleyball, D",slovak:"volejbal"},
{german:"der Vorschlag, PI. Vorschläge",slovak:"nápad"},
{german:"wandern",slovak:"robit turistiku"},
{german:"weil",slovak:"pretoze"},
{german:"wenig",slovak:"málo"},
{german:"wenn",slovak:"ked"},
{german:"das Wetter, D",slovak:"pocasie"},
{german:"wirklich",slovak:"skutocne"},
{german:"das Wochenende,-n",slovak:"víkend"},
];