const listOfWords = [
	{german:"die Lebenslinie, -n",slovak:"lifeline"},
{german:"die Schulzeit",slovak:"school years"},
{german:"die Kindheit",slovak:"childhood"},
{german:"das Erstaunen",slovak:"surprise"},
{german:"wissen, er/sie weiß, er/sie hat gewusst",slovak:"to know"},
{german:"ehemalig",slovak:"former"},
{german:"der Schüler, -",slovak:"student"},
{german:"die Schülerin, -nen",slovak:"female student"},
{german:"(sich) erinnern",slovak:"to remember"},
{german:"damals",slovak:"back then"},
{german:"streng",slovak:"strict"},
{german:"(sich) unterhalten, er/sie unterhält, er/sie hat unterhalten",slovak:"to converse"},
{german:"böse",slovak:"[here] difficult, misbehaving"},
{german:"die Ecke, -n",slovak:"corner"},
{german:"die Klasse, -n",slovak:"class"},
{german:"leihen, er/sie leiht, er/sie hat geliehen",slovak:"to lend"},
{german:"das Papier, -e",slovak:"paper"},
{german:"die Schreibtafel, -n",slovak:"blackboard"},
{german:"der Leser, -",slovak:"reader"},
{german:"die Leserin, -nen",slovak:"female reader"},
{german:"wahr",slovak:"TRUE"},
{german:"unglaublich",slovak:"unbelievable"},
{german:"die Ausbildung, -en",slovak:"education"},
{german:"die Biografie, -n",slovak:"biography"},
{german:"der Lebenslauf, -äu-e",slovak:"curriculum vitae"},
{german:"das Studium, Studien",slovak:"studies"},
{german:"der Zufall, -ä-e",slovak:"coincidence"},
{german:"die Leidenschaft, -en",slovak:"passion"},
{german:"der Kommissar, -e",slovak:"commissioner [police officer]"},
{german:"die Hauptrolle, -n",slovak:"main/leading role"},
{german:"der Einwanderer, -",slovak:"immigrant"},
{german:"die Einwanderin, -nen",slovak:"female immigrant"},
{german:"geboren (sein), er/sie ist geboren, er/sie wurde geboren",slovak:"to be born"},
{german:"der Muslim, -e",slovak:"Muslim"},
{german:"die Muslimin, -nen",slovak:"female Muslim"},
{german:"das Schwimmbad, -ä-er",slovak:"swimming pool"},
{german:"die Klassenfahrt, -en",slovak:"school trip"},
{german:"das Gymnasium, Gymnasien",slovak:"German secondary school"},
{german:"das Zeugnis, -se",slovak:"school report"},
{german:"die Realschule, -n",slovak:"six-year secondary school"},
{german:"der Sachbearbeiter, -",slovak:"specialist clerk"},
{german:"die Sachbearbeiterin, -nen",slovak:"specialist clerk"},
{german:"teil|nehmen, er/sie nimmt teil, er/sie hat teilgenommen",slovak:"to participate"},
{german:"der Komponist, -en",slovak:"composer"},
{german:"die Komponistin, -nen",slovak:"female composer"},
{german:"der Autor, -en",slovak:"author"},
{german:"die Autorin, -nen",slovak:"female author"},
{german:"die Hauptschule, -n",slovak:"five-year secondary school"},
{german:"der Dekorateur, -e",slovak:"decorator"},
{german:"die Dekorateurin, -nen",slovak:"female decorator"},
{german:"die Band, -s",slovak:"band"},
{german:"wechseln",slovak:"[here] to switch"},
{german:"die Schallplatte, -n",slovak:"record [music]"},
{german:"olympisch",slovak:"Olympic"},
{german:"die Note, -n",slovak:"[here] grade"},
{german:"ab|schließen, er/sie schließt ab, er/sie hat abgeschlossen",slovak:"to complete"},
{german:"der Abschluss, -ü-e",slovak:"diploma"},
{german:"die Grundschule, -n",slovak:"elementary school"},
{german:"das Filmfestival, -s",slovak:"film festival"},
{german:"der Filmemacher, -",slovak:"filmmaker"},
{german:"die Filmemacherin, -nen",slovak:"female filmmaker"},
{german:"der Stein, -e",slovak:"stone"},
{german:"magisch",slovak:"magical"},
{german:"möglich machen",slovak:"to make possible"},
{german:"österreichisch",slovak:"Austrian"},
{german:"die Hauptstadt, -ä-e",slovak:"capital city"},
{german:"virtuell",slovak:"virtual"},
{german:"die Star-Galerie, -n",slovak:"star gallery"},
{german:"recherchieren",slovak:"to research"},
{german:"sterben, er/sie stirbt, er/sie ist gestorben",slovak:"to die"},
{german:"das Kaufhaus, -äu-er",slovak:"department store"},
{german:"extra",slovak:"separately"},
{german:"die Stadtratte, -n",slovak:"friend of the city"},
{german:"die Landmaus, -äu-e",slovak:"friend of the countryside"},
]