const listOfWords = [
{german:"der Wind, -(e)",slovak:"wind"},
{german:"die Wolke, -n",slovak:"cloud"},
{german:"der Regen (sg.)",slovak:"rain"},
{german:"der Schnee (sg.)",slovak:"snow"},
{german:"die Sonne, -n",slovak:"sun"},
{german:"Die Sonne scheint.",slovak:"The sun’s shining."},
{german:"schneien, es schneit",slovak:"to snow"},
{german:"sonnig",slovak:"sunny"},
{german:"Es ist sonnig.",slovak:"It’s sunny."},
{german:"windig",slovak:"windy."},
{german:"bewölkt",slovak:"cloudy"},
{german:"Es sind 20 Grad.",slovak:"It’s 20 degrees."},
{german:"Wie ist das Wetter in…?",slovak:"What’s the weather like in…?"},
{german:"die Jacke, -n",slovak:"jacket"},
{german:"der Mantel, -ä-",slovak:"coat"},
{german:"der Pullover / Pulli, -/s",slovak:"pullover"},
{german:"der Rock, -ö-e",slovak:"skirt"},
{german:"das T-Shirt, -s",slovak:"t-shirt"},
{german:"die Bluse, -n",slovak:"blouse"},
{german:"das Hemd, -en",slovak:"shirt"},
{german:"der Anzug, -ü-e",slovak:"suit"},
{german:"der Stiefel, -",slovak:"boot, -s"},
{german:"die Mütze, -n",slovak:"cap"},
{german:"der Handschuh, -e",slovak:"gloves"},
{german:"der Regenschirm, -e",slovak:"umbrella"},
{german:"wunderbar",slovak:"wonderful"},
{german:"nicht mehr",slovak:"not … anymore"},
{german:"Es ist nicht mehr so heiss.",slovak:"It’s not so hot anymore."},
{german:"noch",slovak:"still"},
{german:"Das Wetter ist noch warm.",slovak:"The weather’s still warm."},
{german:"auf keinen Fall",slovak:"in no case"},
{german:"die Farbe, -n",slovak:"color"},
{german:"weiss",slovak:"white"},
{german:"gelb",slovak:"yellow"},
{german:"orange",slovak:"orange"},
{german:"rot",slovak:"red"},
{german:"rosa",slovak:"rose (color)"},
{german:"lila",slovak:"purple"},
{german:"blau",slovak:"blue"},
{german:"hellblau",slovak:"bright blue"},
{german:"gün",slovak:"green"},
{german:"dunkelgrün",slovak:"dark green"},
{german:"braun",slovak:"brown"},
{german:"grau",slovak:"grey"},
{german:"schwarz",slovak:"black"},
{german:"anziehen, er/sie hat angezogen",slovak:"put on (clothes)"},
{german:"gefallen, er/sie gefähllt, er/sie hat gefallen",slovak:"“to be pleasing”"},
{german:"gehören",slovak:"to belong"},
{german:"danken",slovak:"to thank"},
{german:"Ich danke dir!",slovak:"(I) thank you!"},
{german:"schmecken",slovak:"to taste"},
{german:"passen",slovak:"to fit"},
{german:"Die Bluse passt dir nicht.",slovak:"The blouse doesn’t fit you."},
{german:"stehen, er/sie hat gestanden",slovak:"to suit"},
{german:"Die Hose steht dir gut. (Sie steht dir gut)",slovak:"The pants suit you well."},
{german:"zufrieden",slovak:"content (happy)"},
{german:"die Disko, -s / der Club",slovak:"club"},
{german:"bedeuten",slovak:"to mean"},
{german:"dorthin",slovak:"there"},
{german:"das Ostern (sg.)",slovak:"Easter"},
];