const listOfWords = [
{german:"Herzlichen Glückwunsch!",slovak:"(“heartfelt”) congratulations"},
{german:"der Ehepartner, -",slovak:"spouse (m.)"},
{german:"die Ehepartnerin, -nen",slovak:"spouse (f.)"},
{german:"die Geschwister (pl.)",slovak:"siblings"},
{german:"der Bruder, -ü-",slovak:"brother"},
{german:"die Schwester, -n",slovak:"sister"},
{german:"die Grosseltern (pl.)",slovak:"grandparents"},
{german:"die Grossmutter, -ü-",slovak:"grandmother"},
{german:"der Grossvater, -ä-",slovak:"grandfather"},
{german:"die Eltern (pl.)",slovak:"parents"},
{german:"die Mutter, -ü-",slovak:"mother"},
{german:"der Vater, -ä-",slovak:"father"},
{german:"das Kind, -er",slovak:"child"},
{german:"der Sohn, -ö-e",slovak:"son"},
{german:"die Tochter, -ö-",slovak:"daughter"},
{german:"verheiratet",slovak:"married"},
{german:"ledig",slovak:"single (not married)"},
{german:"das Ausland (sg.)",slovak:"foreign countries"},
{german:"aussehen, er/sie sieht aus",slovak:"to look (e.g. to look good)"},
{german:"nett",slovak:"kind"},
{german:"von (+ Name)",slovak:"of, from"},
{german:"Das ist der Sohn von Mia.",slovak:"That’s the son of Mia = Mia’s son"},
{german:"die Familie, -n",slovak:"family"},
{german:"der Brief, -e",slovak:"letter (written message)"},
{german:"die Party, -s",slovak:"party"},
{german:"mitbringen",slovak:"to bring (with you)"},
{german:"die Feier, -n",slovak:"celebration"},
{german:"feiern",slovak:"celebrate"},
{german:"die Sprache, -n",slovak:"language"},
{german:"Ich spreche Deutsch.",slovak:"I speak German."},
{german:"Ich bin Deutscher/Deutsche.",slovak:"I’m German (m./f.)."},
{german:"der Deutsche, -n",slovak:"German (m.)"},
{german:"der Österreicher, -",slovak:"Austrian (m.)"},
{german:"die Österreicherin, -nen",slovak:"Austrian (f.)"},
{german:"der Schweizer, -",slovak:"Swiss (m.)"},
{german:"die Schweizerin, -nen",slovak:"Swiss (f.)"},
{german:"schon",slovak:"already"},
{german:"Ich war schon in Spanien.",slovak:"I was already in Spain."},
{german:"Wir können gern “du” sagen.",slovak:"“We can say informal you to each other.”"},
{german:"der Geburtstag, -e",slovak:"birthday"},
{german:"das Geschenk, -e",slovak:"present, gift"},
{german:"der Arbeitsplatz, -ä-e",slovak:"workplace"},
{german:"am Arbeitsplatz",slovak:"at the workplace"},
{german:"der Chef, -s",slovak:"boss, m."},
{german:"die Chefin, -nen",slovak:"boss, f."},
{german:"das Geld (sg.)",slovak:"money"},
{german:"der Kollege, -n",slovak:"colleague, m."},
{german:"die Kollegin, -nen",slovak:"“ f."},
{german:"der Kuchen, -",slovak:"cake"},
{german:"die Pause, -n",slovak:"break (noun)"},
{german:"Das geht (auch/nicht).",slovak:"That works (as well/not)."},
{german:"noch nie",slovak:"never before"},
{german:"das Haus, -äu-er",slovak:"house"},
{german:"der Schnee (sg.)",slovak:"snow"},
{german:"der Berg, -e",slovak:"mountain"},
{german:"oben",slovak:"on top"},
{german:"unten",slovak:"bottom"},
{german:"hinten",slovak:"behind"},
{german:"vorn",slovak:"in front"},
{german:"links",slovak:"left"},
{german:"rechts",slovak:"right"},
];