const listOfWords = [
	{german:"die Essgewohnheit, -en",slovak:"eating habit"},
{german:"die Kantine, -n",slovak:"canteen"},
{german:"authentisch",slovak:"authentic"},
{german:"das Motto, -s",slovak:"motto"},
{german:"frisch",slovak:"fresh"},
{german:"das Gericht, -e",slovak:"dish [food]"},
{german:"verwenden",slovak:"to use"},
{german:"die Zutat, -en",slovak:"ingredient"},
{german:"scharf",slovak:"spicy"},
{german:"das Gewürz, -e",slovak:"spice"},
{german:"die Nuss, -ü-e",slovak:"nut"},
{german:"das Fruchteis",slovak:"fruit sorbet"},
{german:"vegan",slovak:"vegan"},
{german:"vegetarisch",slovak:"vegetarian"},
{german:"die Suppe, -n",slovak:"soup"},
{german:"bitter",slovak:"bitter"},
{german:"salzig",slovak:"salty"},
{german:"die Altstadt, -ä-e",slovak:"old town"},
{german:"das Hähnchencurry, -s",slovak:"chicken curry"},
{german:"perfekt",slovak:"perfect"},
{german:"mild",slovak:"mild (in taste)"},
{german:"aromatisch",slovak:"aromatic"},
{german:"der Nachtisch",slovak:"dessert"},
{german:"die Erdnuss, -ü-e",slovak:"peanut"},
{german:"ab|lehnen",slovak:"to decline"},
{german:"das Hauptgericht, -e",slovak:"main course"},
{german:"die Beilage, -n",slovak:"side dish, garnish"},
{german:"die Serviette, -n",slovak:"napkin"},
{german:"das Messer, -",slovak:"knife"},
{german:"die Gabel, -n",slovak:"fork"},
{german:"der Löffel, -",slovak:"spoon"},
{german:"der Pfeffer",slovak:"pepper"},
{german:"der Essig",slovak:"vinegar"},
{german:"die Vorspeise, -n",slovak:"appetizer"},
{german:"die Garnele, -n",slovak:"shrimp"},
{german:"der Knoblauch",slovak:"garlic"},
{german:"die Olive, -n",slovak:"olive"},
{german:"die Forelle, -n",slovak:"trout"},
{german:"der Grill, -s",slovak:"grill"},
{german:"das Lammkotelett, -s",slovak:"lamb chop"},
{german:"die Bohne, -n",slovak:"bean"},
{german:"der Champignon, -s",slovak:"mushroom (champignon)"},
{german:"das Steak, -s",slovak:"steak"},
{german:"die Kirsche, -n",slovak:"cherry"},
{german:"der Rotwein, -e",slovak:"red wine"},
{german:"das Kartoffelpüree, -s",slovak:"mashed potatoes"},
{german:"das Schnitzel, -",slovak:"schnitzel"},
{german:"der regional",slovak:"regional"},
{german:"der Feinschmecker, -",slovak:"gourmet"},
{german:"die Identität, -en",slovak:"identity"},
{german:"die Monarchie, -n",slovak:"monarchy"},
{german:"der Gulasch, -e",slovak:"goulash"},
{german:"der Knödel, -",slovak:"dumpling [large dumpling made from potato or semolina]"},
{german:"die Palatschinke, -n",slovak:"pancake"},
{german:"der Pfannkuchen, -",slovak:"pancake"},
{german:"der Eierkuchen, -",slovak:"pancake"},
{german:"die Marille, -n",slovak:"apricot"},
{german:"die Aprikose, -n",slovak:"apricot"},
{german:"der Erdapfel, -ä-",slovak:"potato"},
{german:"ursprünglich",slovak:"originally"},
{german:"der Betrieb, -e",slovak:"business"},
{german:"das Gebäck, -e",slovak:"cookies, pastries"},
]