const listOfWords = [
{german:"Wie geht’s (dir)?",slovak:"How are you? (informal)"},
{german:"Es geht.",slovak:"Okay."},
{german:"danke",slovak:"thanks"},
{german:"ganz gut",slovak:"quite good"},
{german:"endlich",slovak:"finally"},
{german:"warm",slovak:"warm"},
{german:"Wie geht es Ihnen?",slovak:"How are you? (formal, sg./pl.)"},
{german:"gut",slovak:"good"},
{german:"sehr gut",slovak:"very good"},
{german:"heute",slovak:"today"},
{german:"heiss",slovak:"hot"},
{german:"super",slovak:"super, awesome"},
{german:"der Lehrer, -",slovak:"teacher m."},
{german:"die Lehrerin, -nen",slovak:"teacher f."},
{german:"der Verkäufer, -",slovak:"salesperson m."},
{german:"die Verkäuferin, -nen",slovak:"salesperson f."},
{german:"der Elektriker, -",slovak:"electrician m."},
{german:"die Elektrikerin, -nen",slovak:"electrician f."},
{german:"der Ingenieur, -e",slovak:"engineer m."},
{german:"die Ingenieurin, -nen",slovak:"engineer f."},
{german:"der Musiker, -",slovak:"musician m."},
{german:"die Musikerin, -nen",slovak:"musician f."},
{german:"der Arzt, Ä-e",slovak:"doctor, physician"},
{german:"die Ärztin, -nen",slovak:"doctor, physician f."},
{german:"der Busfahrer, -",slovak:"busdriver m."},
{german:"die Busfahrerin, -nen",slovak:"busdriver f."},
{german:"der Student, -en",slovak:"student m."},
{german:"die Studentin, -nen",slovak:"student f."},
{german:"der Programmierer, -",slovak:"programmer m."},
{german:"die Programmiererin, -nen",slovak:"programmer f."},
{german:"die Reinigungskraft, -ä-e",slovak:"cleaner (job) m./f."},
{german:"die Schweiz",slovak:"Switzerland"},
{german:"Das stimmt.",slovak:"That’s correct."},
{german:"machen",slovak:"to do"},
{german:"Was macht ihr?",slovak:"What are you doing?"},
{german:"arbeiten",slovak:"to work"},
{german:"neu",slovak:"new"},
{german:"interessant",slovak:"interesting"},
{german:"der Beruf, -e",slovak:"job, profession"},
{german:"die Firma, Firmen",slovak:"company"},
{german:"Was sind Sie von Beruf?",slovak:"What’s your job?"},
{german:"als (+Beruf)",slovak:"as (+profession)"},
{german:"Er arbeitet als Ingenieur.",slovak:"He works as an engineer."},
{german:"bei (+Firma)",slovak:"at (+ company)"},
{german:"Wir arbeiten bei DesigNetz.",slovak:"We work at DesigNetz."},
{german:"richtig",slovak:"right, correct"},
{german:"falsch",slovak:"wrong"},
{german:"der Nachname, -n",slovak:"surname/family name"},
{german:"die Adresse, -n",slovak:"address"},
{german:"die E-Mail, -s",slovak:"e-mail"},
{german:"die E-Mail-Adressen, -n",slovak:"e-mail address"},
{german:"die Hausnummer, -n",slovak:"house number"},
{german:"die Postleitzahl (PLZ), -en",slovak:"postal code, zipcode"},
{german:"die Strasse, -n",slovak:"street"},
{german:"die Telefonnummer, -n",slovak:"phone number"},
{german:"die Nummer, -n",slovak:"number"},
{german:"Hier, bitte.",slovak:"Here you are. / There you go. (when sth. is given to you)"},
{german:"gern",slovak:"like doing (Verb needed)"},
{german:"gross",slovak:"big, tall"},
{german:"klein",slovak:"small, short"},
{german:"das Hobby, -s",slovak:"hobby"},
{german:"Österreich",slovak:"Austria"},
];