const listOfWords = [
{german:"das Sofa, -s",slovak:"couch"},
{german:"die Matratze, -n",slovak:"matress"},
{german:"anbieten, er/sie hat angeboten",slovak:"to offer"},
{german:"die WG / Wohngemeinschaft, -s/-en",slovak:"people living in one apartment (not family)"},
{german:"das Zentrum, die Zentren",slovak:"center"},
{german:"laut",slovak:"loud"},
{german:"zu (+ Adjektiv)",slovak:"too (e.g. too loud)"},
{german:"Liebe/r (+ Name)",slovak:"dear + name"},
{german:"die Küche, -n",slovak:"kitchen"},
{german:"hart",slovak:"hard"},
{german:"heute Abend",slovak:"this evening; tonight"},
{german:"warten",slovak:"to wait"},
{german:"danach",slovak:"afterwards"},
{german:"die Oma, -s",slovak:"grandma"},
{german:"besuchen",slovak:"to visit"},
{german:"weit",slovak:"far"},
{german:"Liebe Grüsse",slovak:"informal: love; kind regards"},
{german:"das Wohnzimmer, -",slovak:"living room"},
{german:"das Schlafzimmer, -",slovak:"bedroom"},
{german:"das Kinderzimmer, -",slovak:"child’s room / children’s room"},
{german:"das Arbeitszimmer, -",slovak:"workroom"},
{german:"das Bad/Badezimmer, -ä-er/ -",slovak:"bathroom"},
{german:"der Flur, -e",slovak:"hallway"},
{german:"der Balkon, -e",slovak:"balcony"},
{german:"das Erdgeschoss, -e",slovak:"ground floor"},
{german:"offen / auf sein",slovak:"to be open"},
{german:"geschlossen / zu sein",slovak:"to be closed"},
{german:"hell",slovak:"bright"},
{german:"dunkel",slovak:"dark"},
{german:"die Ankunft, -ü-e",slovak:"arrival"},
{german:"früher",slovak:"earlier"},
{german:"der Schlüssel, -",slovak:"key"},
{german:"liegen, er/sie hat gelegen",slovak:"to lie (certain position)"},
{german:"stehen, er/sie hat gestanden",slovak:"stand"},
{german:"hängen, er/sie hat gehangen",slovak:"hang"},
{german:"zu Hause",slovak:"at home"},
{german:"hinter (+ Ort)",slovak:"behind"},
{german:"unter (+ Ort)",slovak:"under; underneath"},
{german:"neben (+ Ort)",slovak:"next to"},
{german:"in (+ Ort)",slovak:"in"},
{german:"an (+ Ort)",slovak:"on"},
{german:"zwischen (+ Ort)",slovak:"between"},
{german:"auf (+ Ort)",slovak:"on top of"},
{german:"vor (+ Ort)",slovak:"in front"},
{german:"über (+ Ort)",slovak:"over"},
{german:"der Schrank, -ä-e",slovak:"cupboard"},
{german:"der Herd, -e",slovak:"stove"},
{german:"der Teller, -",slovak:"plate"},
{german:"die Wand, -ä-e",slovak:"wall"},
{german:"das Regal, -e",slovak:"shelf"},
{german:"finden, er/sie hat gefunden",slovak:"to find"},
{german:"das Angebot, -e",slovak:"the offer"},
{german:"wohnen",slovak:"to live"},
{german:"das Leben, -",slovak:"the life"},
{german:"als (+ Kind/Student/…)",slovak:"when (I was a child / student)"},
{german:"zuerst",slovak:"first"},
{german:"der Nachbar, -n",slovak:"neighbour, m."},
{german:"die Nachbarin, -nen",slovak:"neighbour, f."},
{german:"draussen",slovak:"outside"},
{german:"spielen",slovak:"play"},
{german:"umziehen, er/sie ist umgezogen",slovak:"move (to another place)"},
{german:"mit (+ Alter)",slovak:"with; here: in the age of…"},
{german:"heiraten",slovak:"marry"},
];