const listOfWords = [
{german:"der Platz, -ä-e",slovak:"square (or: space; place)"},
{german:"die Kreuzung, -en",slovak:"crossover"},
{german:"das Schild, -er",slovak:"sign"},
{german:"der Zebrastreifen, -",slovak:"cross-walk"},
{german:"der Bahnhof, -ö-e",slovak:"train station"},
{german:"die Fussgängerzone, -n",slovak:"pedestrian zone"},
{german:"der Radweg, -e",slovak:"bicycle trail"},
{german:"(nach) links",slovak:"(to the) left"},
{german:"(nach) rechts",slovak:"(to the) right"},
{german:"geradeaus",slovak:"straight on"},
{german:"sollen, er/sie soll",slovak:"to shall"},
{german:"Wie soll ich fahren?",slovak:"Where shall I go (drive)?"},
{german:"Ich bin nicht von hier.",slovak:"I’m not from here."},
{german:"Fahren Sie die erste Strasse nach links.",slovak:"The first street turn left."},
{german:"bis zu (+ Ort)",slovak:"(up) to (+ place)"},
{german:"An der Kreuzung fahren Sie links.",slovak:"At the crossover turn left."},
{german:"das Restaurant, -s",slovak:"restaurant"},
{german:"der Schalter, -",slovak:"desk, do you mean switcher?"},
{german:"der Kiosk, -e",slovak:"kiosk"},
{german:"das Gleis, -e",slovak:"track/platform"},
{german:"Der Zug fährt von Gleis 4 ab.",slovak:"The train leaves from track 4."},
{german:"abfahren, er/sie fährt ab, er/sie ist abgefahren",slovak:"to leave"},
{german:"die Anzeigetafel, -n",slovak:"destination board"},
{german:"die Fahrkarte, -n (CH: das Billet)",slovak:"ticket"},
{german:"die Information, -en",slovak:"information"},
{german:"die Raucherzone, -n",slovak:"smoking area"},
{german:"bar",slovak:"cash"},
{german:"Ich zahle bar.",slovak:"I pay cash."},
{german:"die Kreditkarte, -n",slovak:"credit card"},
{german:"mit Kreditkarte / mit Karte zahlen",slovak:"“with” card / pay by card"},
{german:"Gute Fahrt!",slovak:"Have a good trip!"},
{german:"werfen, er/sie wirft, er/sie hat geworfen",slovak:"throw"},
{german:"der Müll (sg.)",slovak:"trash"},
{german:"verboten",slovak:"prohibited"},
{german:"Hier ist Rauchen verboten.",slovak:"Smoking is prohibited here."},
{german:"dürfen, er/sie darf",slovak:"to may/might (meaning: you’re allowed)"},
{german:"Darf man hier rauchen?",slovak:"Is it allowed to smoke here?"},
{german:"schade",slovak:"a pity"},
{german:"schauen",slovak:"to look; to watch"},
{german:"kontrollieren",slovak:"to check"},
{german:"die Polizei (sg.)",slovak:"police"},
{german:"sicher",slovak:"safe"},
{german:"Ist der Schulweg sicher?",slovak:"Is the way to school safe?"},
{german:"stehen bleiben, er/sie ist stehen geblieben",slovak:"stand still"},
{german:"bremsen",slovak:"to brake"},
{german:"der Spielplatz, -ä-e",slovak:"play ground"},
{german:"die Bitte, -n",slovak:"request"},
{german:"eine Bitte haben",slovak:"to have a request"},
{german:"Recht haben",slovak:"to be right"},
{german:"Ich denke, du hast Recht.",slovak:"I think you’re right."},
];