const listOfWords = [
{german:"der Schuh, -e",slovak:"shoe"},
{german:"das Ladekabel, -",slovak:"charge cable"},
{german:"der USB-Stick, -s",slovak:"USB stick"},
{german:"der Hut, -ü-e",slovak:"hat"},
{german:"das Kleid, -er",slovak:"dress, pl: dresses / clothes"},
{german:"der Lippenstift, -e",slovak:"lipstick"},
{german:"die Sonnenbrille, -n",slovak:"sunglasses"},
{german:"gehen",slovak:"to go"},
{german:"shoppen gehen",slovak:"to go shopping"},
{german:"Gehen Sie gern shoppen?",slovak:"Do you like go shopping? (formal)"},
{german:"kaufen",slovak:"to buy"},
{german:"die Batterie, -n",slovak:"battery"},
{german:"die Hose, -n",slovak:"trousers, pants"},
{german:"der Koffer, -",slovak:"suitcase"},
{german:"alles",slovak:"everything, all"},
{german:"Ist das alles?",slovak:"Is that all?"},
{german:"brauchen",slovak:"to need"},
{german:"Gute Idee.",slovak:"good idea"},
{german:"nur",slovak:"only"},
{german:"vielleicht",slovak:"perhaps, maybe"},
{german:"die Handyhülle, -n",slovak:"cell phone case"},
{german:"die Kette, -n",slovak:"necklace, chain"},
{german:"der Ring, -e",slovak:"ring"},
{german:"Kann ich Ihnen helfen?",slovak:"Can I help you? (formal)"},
{german:"suchen",slovak:"to look for, search"},
{german:"die CD, -s",slovak:"CD"},
{german:"möchten, er/sie möchte",slovak:"to would like, he/she would like"},
{german:"glauben",slovak:"to believe"},
{german:"Ich glaube, Franzi sucht CDs.",slovak:"I believe Franzi’s looking for CDs."},
{german:"Schau mal, …",slovak:"Look, ..."},
{german:"Schau mal, das Bild!",slovak:"Look at the picture!"},
{german:"Das Bild ist schön!",slovak:"The picture is beautiful!"},
{german:"haben, er/sie hat",slovak:"to have, he/she has"},
{german:"günstig",slovak:"cheap"},
{german:"denken",slovak:"to think"},
{german:"Ich denke, ich kaufe den USB-Stick.",slovak:"I think I buy the USB stick."},
{german:"Nicht schlecht.",slovak:"not bad"},
{german:"wirklich",slovak:"really"},
{german:"Brauchst du das Handy wirklich?",slovak:"Do you really need the cell phone?"},
{german:"das Smartphone, -s",slovak:"smartphone"},
{german:"doch",slovak:"different meanings: “on the contrary”,"},
{german:"however",slovak:"yet"},
{german:"Tut mir leid.",slovak:"I’m sorry."},
{german:"Ja, klar.",slovak:"Yes, sure."},
{german:"leider",slovak:"unfortunately"},
{german:"Ich habe leider keinen Bleistift.",slovak:"Unfortunately, I don’t have a pencil."},
{german:"der Tipp, -s",slovak:"hint/tip"},
{german:"kennen",slovak:"to know"},
{german:"finden",slovak:"to find"},
{german:"Wie findet ihr die Uhr?",slovak:"How do you find the watch?"},
{german:"der Tee, -s",slovak:"tea"},
{german:"dort",slovak:"there"},
{german:"der Traum, -äu-e",slovak:"dream"},
{german:"Shoppen in Hamburg - ein Traum!",slovak:"Shopping in Hamburg (is) a dream!"},
{german:"der Haften, -ä-",slovak:"harbour"},
{german:"das Schiff, -e",slovak:"ship"},
{german:"das Theater, -",slovak:"theater"},
{german:"toll",slovak:"great"},
{german:"das Foto, -s",slovak:"photo"},
{german:"der Mann, -ä-er",slovak:"man, husband"},
];