const listOfWords = [
{german:"Guten Morgen.",slovak:"Good morning."},
{german:"Guten Tag.",slovak:"“Good day.” → Hello (formal and informal)"},
{german:"Hallo!",slovak:"Hello!"},
{german:"der Herr, -en Herr Meier",slovak:"Mister Meier"},
{german:"die Frau, -en Frau Meier",slovak:"Miss Meier"},
{german:"Guten Abend.",slovak:"Good evening."},
{german:"Angenehm.",slovak:"Nice to meet you (formal)"},
{german:"Vielen Dank.",slovak:"Thank you a lot."},
{german:"Gute Nacht.",slovak:"Good night."},
{german:"der Name, -n",slovak:"name"},
{german:"Mein Name ist…",slovak:"My name is..."},
{german:"Tschüs.",slovak:"Bye"},
{german:"Auf Wiedersehen.",slovak:"Good bye (formal)"},
{german:"Bis bald.",slovak:"See you soon."},
{german:"und",slovak:"and"},
{german:"Herzlich willkommen.",slovak:"Welcome."},
{german:"der Wohnort, -e",slovak:"place of residence"},
{german:"die Stadt, -ä-e",slovak:"city"},
{german:"das Land, -ä-er",slovak:"country"},
{german:"Deutschland",slovak:"Germany"},
{german:"woher",slovak:"where from"},
{german:"kommen",slovak:"to come"},
{german:"Woher kommst du?",slovak:"Where do you come from?"},
{german:"auch",slovak:"too / as well"},
{german:"jetzt",slovak:"now"},
{german:"sehr",slovak:"very"},
{german:"heissen",slovak:"to be called"},
{german:"Wie heisst du?",slovak:"What are you called? (What’s your name?)"},
{german:"wie",slovak:"how"},
{german:"sein, er/sie ist",slovak:"to be, he/she is"},
{german:"wo",slovak:"where"},
{german:"wohnen",slovak:"to live"},
{german:"Wo wohnst du?",slovak:"Where do you live?"},
{german:"in (+ Stadt/Land)",slovak:"in (+ city/country)"},
{german:"aus (+ Stadt/Land)",slovak:"from (+ city/country)"},
{german:"aber",slovak:"but"},
{german:"mögen, er/sie mag",slovak:"to like, he/she likes"},
{german:"wer",slovak:"who"},
{german:"was",slovak:"what"},
{german:"ja",slovak:"yes"},
{german:"nein",slovak:"no"},
{german:"lernen",slovak:"to learn"},
{german:"Ich lerne Deutsch.",slovak:"I learn German. / I’m learning German."},
{german:"studieren",slovak:"to study"},
{german:"nicht",slovak:"not"},
{german:"nichts",slovak:"nothing"},
{german:"der Fussball",slovak:"football, soccer"},
{german:"der Sport",slovak:"sports"},
{german:"der Kaffee, -s",slovak:"coffee"},
{german:"die Schokolade",slovak:"chocolate"},
{german:"die Pizza, -s/ Pizzen",slovak:"pizza"},
{german:"die Technik, -en",slovak:"technology; engeneering; technique"},
{german:"die Kunst, -ü-e",slovak:"art"},
{german:"die Mode, -n",slovak:"fashion"},
{german:"Entschuldigung, …",slovak:"Excuse me..."},
{german:"bitte",slovak:"please"},
{german:"Buchstabieren Sie, bitte.",slovak:"Spell, please. (formal)"},
{german:"schreiben",slovak:"to write"},
{german:"Wie schreibt man das?",slovak:"How is it written?"},
{german:"Moment, …",slovak:"One moment, ..."},
{german:"der Familienname, -n",slovak:"family name, surname"},
{german:"der Vorname, -n",slovak:"first name"},
];