const listOfWords = [
{german:"die Gesundheit (sg.)",slovak:"health"},
{german:"Das ist (nicht) gut für die Gesundheit!",slovak:"This is (not) good for health."},
{german:"dick",slovak:"fat"},
{german:"ein bisschen",slovak:"a little"},
{german:"abnehmen, er/sie nimmt ab, er/sie hat abgenommen",slovak:"lose weight"},
{german:"das Wetter (sg.)",slovak:"weather"},
{german:"die Kleidung (sg)",slovak:"clothing"},
{german:"vergessen, er/sie vergisst, er/sie hat vergessen",slovak:"to forget"},
{german:"lachen",slovak:"lough"},
{german:"gesund",slovak:"healthy"},
{german:"der Alkohol (sg.)",slovak:"alcohol"},
{german:"rauchen",slovak:"smoke"},
{german:"der Spaziergang, -ä-e",slovak:"the walk"},
{german:"einen Spaziergang machen",slovak:"to go for a walk"},
{german:"der Körper, -",slovak:"body"},
{german:"das Gesicht, -er",slovak:"face"},
{german:"das Auge, -n",slovak:"eye"},
{german:"die Nase, -n",slovak:"nose"},
{german:"der Mund, -ü-er",slovak:"mouth"},
{german:"der Kopf, -ö-e",slovak:"head"},
{german:"das Ohr, -en",slovak:"ear"},
{german:"der Hals, -ä-e",slovak:"neck; throat"},
{german:"die Schulter, -n",slovak:"shoulder"},
{german:"der Arm, -e",slovak:"arm"},
{german:"die Hand, -ä-e",slovak:"hand"},
{german:"der Rücken, -",slovak:"back"},
{german:"der Bauch, -äu-e",slovak:"stomack; belly"},
{german:"das Bein, -e",slovak:"leg"},
{german:"der Fuss, -ü-e",slovak:"foot"},
{german:"der Zahn, -ä-e",slovak:"tooth"},
{german:"wahrscheinlich",slovak:"probably"},
{german:"die Bauchschmerzen (pl.)",slovak:"belly ache; belly pain"},
{german:"der Unfall, -ä-e",slovak:"accident"},
{german:"wehtun, er/es/sie hat wehgetan",slovak:"to ache"},
{german:"Der Kopf hat wehgetan.",slovak:"My head was aching."},
{german:"die Kopfschmerzen (pl.)",slovak:"headache"},
{german:"das Fieber (sg.)",slovak:"fever"},
{german:"Ich habe Fieber / Bauchschmerzen.",slovak:"I have a fever / belly pain."},
{german:"erkältet sein",slovak:"to have a cold"},
{german:"die Zahnschmerzen (pl.)",slovak:"toothache"},
{german:"Mein Zahn tut weh.",slovak:"My tooth is aching."},
{german:"die Tablette, -n",slovak:"pill"},
{german:"das Medikament, -e",slovak:"medecin"},
{german:"Gute Besserung!",slovak:"Get well!"},
{german:"der Hund, -e",slovak:"dog"},
{german:"fallen, er/sie fällt, er/sie ist gefallen",slovak:"to fall"},
{german:"anrufen, er/sie hat angerufen",slovak:"to call"},
{german:"sagen",slovak:"to say"},
{german:"bekannt",slovak:"wellknown"},
{german:"öffnen",slovak:"to open"},
{german:"deshalb",slovak:"therefore"},
{german:"da",slovak:"there; because"},
{german:"der Kühlschrank, -ä-e",slovak:"fridge"},
{german:"bei mir",slovak:"at my place"},
{german:"kalt",slovak:"cold"},
{german:"hoch",slovak:"high"},
{german:"niedrig",slovak:"low"},
{german:"hässlich",slovak:"ugly"},
{german:"nah",slovak:"near"},
{german:"der Stock, Stockwerke",slovak:"floor"},
];