const listOfWords = [
	{german:"das Ziel, -e",slovak:"goal"},
{german:"der Wunsch, -ü-e",slovak:"wish, desire"},
{german:"der Migrations­wunsch, -ü-e",slovak:"desire to migrate"},
{german:"begründen",slovak:"to justify"},
{german:"weil",slovak:"because"},
{german:"die Migration",slovak:"migration"},
{german:"das Jahrhundert, -e",slovak:"century"},
{german:"die Hoffnung, -en",slovak:"hope"},
{german:"der Umwelttechniker, -",slovak:"environmental technologist"},
{german:"die Umwelttechnikerin, -nen",slovak:"female environmental technologist"},
{german:"die Stelle, -n",slovak:"position (job)"},
{german:"die Umwelttechnik",slovak:"environmental technology"},
{german:"die Chance, -n",slovak:"opportunity"},
{german:"die Brücke, -n",slovak:"bridge"},
{german:"chatten",slovak:"to chat"},
{german:"akzeptieren",slovak:"to accept"},
{german:"der Übersetzer, -",slovak:"translator"},
{german:"die Übersetzerin, -nen",slovak:"female translator"},
{german:"skypen",slovak:"to talk via Skype"},
{german:"aus|wandern",slovak:"to emigrate"},
{german:"verlassen, er/sie verlässt, er/sie hat verlassen",slovak:"to leave, abandon"},
{german:"surfen",slovak:"to surf"},
{german:"die Surfschule, -n",slovak:"surfing school"},
{german:"auf|machen",slovak:"to open (a business)"},
{german:"verdienen",slovak:"to earn [income]"},
{german:"kommunizieren",slovak:"to communicate"},
{german:"führen",slovak:"[here] to conduct (a conversation)"},
{german:"der Sprachkurs, -e",slovak:"language course"},
{german:"die Sprachlernbiografie, -n",slovak:"language learning biography"},
{german:"könnte-",slovak:"could"},
{german:"das Sprachinstitut, -e",slovak:"language institute"},
{german:"die Übersetzung, -en",slovak:"translation"},
{german:"die Fremdsprache, -n",slovak:"foreign language"},
{german:"die Durchwahl, -en",slovak:"direct dial number"},
{german:"verbinden, er/sie verbindet, er/sie hat verbunden",slovak:"to connect"},
{german:"die Taste, -n",slovak:"button"},
{german:"drücken",slovak:"to press, push"},
{german:"besetzt (sein)",slovak:"to be busy"},
{german:"wählen",slovak:"to select (phone number)"},
{german:"die Rechnung, -en",slovak:"bill"},
{german:"der Intensivkurs, -e",slovak:"intensive class"},
{german:"Könnten Sie …",slovak:"Could you …"},
{german:"verschieden-",slovak:"various"},
{german:"der Einstufungstest, -s",slovak:"placement test"},
{german:"reagieren",slovak:"to react"},
{german:"das Tandem, -s",slovak:"tandem, pair"},
{german:"der Muttersprachler, -",slovak:"native speaker"},
{german:"die Muttersprachlerin, -nen",slovak:"female native speaker"},
{german:"der Kontakt, -e",slovak:"contact"},
{german:"die Volkshochschule (VHS), -n",slovak:"adult education center"},
{german:"die Politik",slovak:"politics"},
{german:"der Chor, -ö-e",slovak:"choir"},
{german:"der Schauspieler, -",slovak:"actor"},
{german:"die Schauspielerin, -nen",slovak:"actress"},
{german:"der Rhythmus, Rhythmen",slovak:"rhythm"},
{german:"der Schritt, -e",slovak:"step"},
{german:"der Tanz, -ä-e",slovak:"dance"},
{german:"der Anfänger, -",slovak:"beginner"},
{german:"die Anfängerin, -nen",slovak:"female beginner"},
{german:"die Farbberatung, -en",slovak:"color consulting"},
{german:"die Stilberatung, -en",slovak:"style consulting"},
{german:"diskutieren",slovak:"to discuss"},
{german:"in sein, er/sie ist in, er/sie war in",slovak:"to be fashionable"},
{german:"individuell",slovak:"personal"},
{german:"werden, er/sie wird, er/sie ist geworden",slovak:"to become"},
{german:"der Erwachsene, -n",slovak:"adult (male)"},
{german:"die Erwachsene, -n",slovak:"adult (female)"},
{german:"bestellen",slovak:"to order"},
{german:"das Einchecken",slovak:"to check in"},
{german:"das Pfahlhaus, -äu-er",slovak:"stilt house"},
{german:"das Schloss, -ö-er",slovak:"castle, palace"},
{german:"der Wasserfall, -ä-e",slovak:"waterfall"},
{german:"die Bühne, -n",slovak:"stage (theater)"},
{german:"die Seebühne, -n",slovak:"lakeside stage, theater by the lake"},
{german:"der Norden",slovak:"north"},
{german:"der Osten",slovak:"east"},
{german:"der Süden",slovak:"south"},
{german:"der Westen",slovak:"west"},
{german:"nördlich",slovak:"in the north"},
{german:"östlich",slovak:"in the east"},
{german:"südlich",slovak:"in the south"},
{german:"westlich",slovak:"in the west"},
]