const listOfWords = [
{german:"der Bleistift, -e",slovak:"pencil"},
{german:"das Buch, -ü-er",slovak:"book"},
{german:"das Handy, -s",slovak:"cellphone"},
{german:"das Heft, -e",slovak:"notebook"},
{german:"der Kuli, -s / Kugelschreiber, -s",slovak:"ballpen"},
{german:"die Lampe, -n",slovak:"lamp"},
{german:"der Radiergummi, -s",slovak:"eraser"},
{german:"die Tasche, -n",slovak:"bag"},
{german:"der Tisch, -e",slovak:"table"},
{german:"auf Deutsch",slovak:"in German"},
{german:"Wie heisst das auf Deutsch?",slovak:"What is it called in German?"},
{german:"Keine Ahnung.",slovak:"No idea."},
{german:"Ich weiss (nicht).",slovak:"I (don’t) know."},
{german:"verstehen",slovak:"to understand"},
{german:"das Fenster, -",slovak:"window"},
{german:"die Flasche, -n",slovak:"bottle"},
{german:"der Papierkorb, -ö-e",slovak:"wastepaper basket"},
{german:"der Stuhl, -ü-e",slovak:"chair"},
{german:"die Tafel, -n",slovak:"(black-)board"},
{german:"die Tasse, -n",slovak:"cup"},
{german:"das Tablet, -s",slovak:"tablet"},
{german:"die Jacke, -n",slovak:"jacket"},
{german:"die Tür, -en",slovak:"door"},
{german:"wiederholen",slovak:"repeat"},
{german:"Wiederholen Sie, bitte. / Noch einmal, bitte.",slovak:"Could you repeat that, please? / Once"},
{german:"again",slovak:"please."},
{german:"oder",slovak:"or"},
{german:"das Ding, -e",slovak:"thing"},
{german:"der Zettel, -",slovak:"note"},
{german:"die Brille, -n",slovak:"glasses"},
{german:"der Stift, -e",slovak:"pen"},
{german:"die Uhr, -en",slovak:"watch"},
{german:"das Bild, -er",slovak:"picture"},
{german:"der Computer, -",slovak:"computer"},
{german:"der Laptop, -s",slovak:"laptop"},
{german:"die Maus, -äu-e",slovak:"mouse"},
{german:"wie viele",slovak:"how many"},
{german:"kosten",slovak:"to cost"},
{german:"Er/sie/es kostet 3 Franken.",slovak:"It costs 3 Swiss francs."},
{german:"die Süssigkeit, -en",slovak:"sweets"},
{german:"teuer",slovak:"expensive"},
{german:"das Auto, -s",slovak:"car"},
{german:"schnell",slovak:"fast"},
{german:"circa (ca.)",slovak:"about"},
{german:"modern",slovak:"modern"},
{german:"billig",slovak:"cheap"},
{german:"alt",slovak:"old"},
{german:"Wie alt ist der Computer?",slovak:"How old is the computer?"},
{german:"das Jahr, -e",slovak:"year"},
{german:"über",slovak:"over (more than)"},
{german:"Die Geige ist über 300 Jahre alt.",slovak:"The violin is over 300 years old."},
{german:"fragen",slovak:"ask"},
{german:"funktionieren",slovak:"function"},
{german:"langsam",slovak:"slow"},
{german:"der Füller, -",slovak:"fountain pen (with ink)"},
{german:"die Kamera, -s",slovak:"camera"},
{german:"bunt",slovak:"colorful"},
{german:"langweilig",slovak:"boring"},
{german:"lustig",slovak:"funny"},
{german:"schön",slovak:"beautiful"},
];