const listOfWords = [
	{german:"das Vorurteil, -e",slovak:"prejudice"},
{german:"beobachten",slovak:"to observe"},
{german:"der Käufer, -",slovak:"buyer"},
{german:"die Käuferin, -nen",slovak:"female buyer"},
{german:"das Parkhaus, -äu-er",slovak:"parking garage"},
{german:"die Kasse, -n",slovak:"checkout"},
{german:"der Shopper, -",slovak:"shopper"},
{german:"die Shopperin, -nen",slovak:"female shopper"},
{german:"persönlich",slovak:"personally"},
{german:"zielorientiert",slovak:"goal-oriented"},
{german:"rational",slovak:"rational"},
{german:"emotional",slovak:"emotional"},
{german:"aus|geben, er/sie gibt aus, er/sie hat ausgegeben",slovak:"to spend"},
{german:"sinnlos",slovak:"pointless"},
{german:"das Verhalten",slovak:"behavior"},
{german:"beschreiben, er/sie beschreibt, er/sie hat beschrieben",slovak:"to describe"},
{german:"der Baumarkt, -ä-e",slovak:"hardware store"},
{german:"der Elektromarkt, -ä-e",slovak:"electronics store"},
{german:"sich orientieren",slovak:"to orient oneself"},
{german:"die Empfehlung, -en",slovak:"recommendation"},
{german:"der Konsumartikel, -",slovak:"consumer product"},
{german:"das Parfüm, -s",slovak:"perfume"},
{german:"der Reiseführer, -",slovak:"travel guide"},
{german:"die Creme, -s",slovak:"cream"},
{german:"die Krawatte, -n",slovak:"tie"},
{german:"die Schere, -n",slovak:"scissors"},
{german:"der Drucker, -",slovak:"printer"},
{german:"die Seife, -n",slovak:"soap"},
{german:"der Spielzeugladen, -ä-",slovak:"toy store"},
{german:"die Drogerie, -n",slovak:"drugstore"},
{german:"die Weinhandlung, -en",slovak:"wine shop"},
{german:"der Optiker, -",slovak:"optician"},
{german:"das Souvenir, -s",slovak:"souvenir"},
{german:"preiswert",slovak:"inexpensive"},
{german:"erfüllen",slovak:"to fulfill (a wish)"},
{german:"nennen, er/sie nennt, er/sie hat genannt",slovak:"to name"},
{german:"liebevoll",slovak:"lovingly"},
{german:"(sich) versammeln",slovak:"to gather"},
{german:"breit",slovak:"wide"},
{german:"die Kuckucksuhr, -en",slovak:"cuckoo clock"},
{german:"das Weinlokal, -e",slovak:"wine bar"},
{german:"die Speisekarte, -n",slovak:"menu"},
{german:"das Such-Spiel, -e",slovak:"search game, \"spot the differences\""},
{german:"schick",slovak:"chic, stylish"},
{german:"die Kneipe, -n",slovak:"pub"},
{german:"das Detektivspiel, -e",slovak:"detective game"},
{german:"stehlen, er/sie stiehlt, er/sie hat gestohlen",slovak:"to steal"},
{german:"die Currywurst, -ü-e",slovak:"currywurst"},
{german:"der Dieb, -e",slovak:"thief"},
{german:"die Diebin, -nen",slovak:"female thief"},
{german:"überlegen",slovak:"to think"},
{german:"die Scheibe, -n",slovak:"slice"},
{german:"das Matjesbrötchen, -",slovak:"roll with herring"},
{german:"das Matjesfilet, -s",slovak:"salted herring fillet"},
{german:"backen, er/sie backt, er/sie hat gebacken",slovak:"to bake"},
{german:"das Kurs-Kochbuch, -ü-er",slovak:"course cookbook"},
{german:"das Fischfilet, -s",slovak:"fish fillet"},
{german:"die Chilisoße, -n",slovak:"chili sauce"},
{german:"die Form, -en",slovak:"form"},
{german:"legen",slovak:"to place"},
{german:"der Ofen, Ö-",slovak:"oven"},
]