const listOfWords = [
{german:"der Apfel, Ä-",slovak:"apple"},
{german:"die Butter (sg.)",slovak:"butter"},
{german:"das Ei, -er",slovak:"egg"},
{german:"das Fleisch (sg.)",slovak:"meat"},
{german:"die Gurke, -n",slovak:"cucumber"},
{german:"der Joghurt, -s",slovak:"yoghurt"},
{german:"die Milch (sg.)",slovak:"milk"},
{german:"das Wasser (sg.)",slovak:"water"},
{german:"die Wurst, -ü-e",slovak:"sausage"},
{german:"die Banane, -n",slovak:"banana"},
{german:"der Käse (sg.)",slovak:"cheese"},
{german:"die Marmelade, -n",slovak:"jam"},
{german:"der Saft, -ä-e",slovak:"juice"},
{german:"der Salat, -e",slovak:"salad"},
{german:"die Tomate, -n",slovak:"tomato"},
{german:"der Wein (sg.)",slovak:"wine"},
{german:"essen, er/sie isst",slovak:"eat, he/she eats"},
{german:"das Obst (sg.)",slovak:"fruits"},
{german:"gern, lieber, am liebsten",slovak:"gladly, more, the most"},
{german:"die Kartoffel, -n",slovak:"potato"},
{german:"die Nudeln (pl.)",slovak:"pasta"},
{german:"der Reis (sg.)",slovak:"rice"},
{german:"das Brot, -e",slovak:"bread"},
{german:"die Tafel, -n",slovak:"bar (of chocolate)"},
{german:"eine Tafel Schokolade",slovak:"a bar of chocolate"},
{german:"der Becher, -",slovak:"jar (or a mug)"},
{german:"die Dose, -n",slovak:"can"},
{german:"das Glas, -ä-er",slovak:"glass"},
{german:"das Netz, -e",slovak:"net"},
{german:"die Orange, -n",slovak:"orange"},
{german:"die Packung, -en",slovak:"packet, bag"},
{german:"das Stück, -e",slovak:"piece"},
{german:"die Tüte, -n",slovak:"bag"},
{german:"das Frühstück, -e",slovak:"breakfast"},
{german:"wollen, er/sie will",slovak:"to want"},
{german:"für (+ Name)",slovak:"for (somebody)"},
{german:"Wollen wir etwas für Astrid kochen?",slovak:"Do we want to cook something for Astrid?"},
{german:"etwas",slovak:"something"},
{german:"der Fisch, -e",slovak:"fish"},
{german:"das Gemüse (sg.)",slovak:"vegetables"},
{german:"müssen, er/sie muss",slovak:"to have to"},
{german:"mitkommen",slovak:"to come (with somebody)"},
{german:"das Café, -s",slovak:"café"},
{german:"trinken",slovak:"drink"},
{german:"grillen",slovak:"to grill, barbecue"},
{german:"das Essen",slovak:"food"},
{german:"frühstücken",slovak:"to breakfast"},
{german:"Was darf es sein?",slovak:"How can I help you? (“What may it be?”)"},
{german:"Ich hätte gern…",slovak:"I’d like to have..."},
{german:"Kein Problem!",slovak:"no problem"},
{german:"Das macht 5 Euro.",slovak:"It costs 5€. (“It makes 5€)"},
{german:"das Gramm (g), -",slovak:"gramm"},
{german:"der Liter (l), -",slovak:"liter"},
{german:"das Pfund, -e",slovak:"pound"},
{german:"das Kilo/Kilogramm (kg), -s/-",slovak:"kilogram"},
{german:"das Brötchen, -",slovak:"small bread"},
{german:"die Sahne/Schlagsahne (sg.)",slovak:"cream / whipped cream"},
{german:"der Zucker (sg.)",slovak:"sugar"},
{german:"die Karte, -n",slovak:"card, map, menue"},
{german:"nehmen, er/sie nimmt",slovak:"to take"},
{german:"Ich nehme einen Kaffee.",slovak:"I take a coffee."},
{german:"ohne",slovak:"without"},
{german:"ohne Zucker",slovak:"without sugar"},
];