const listOfWords = [
	{german:"aus|sprechen, er/sie spricht aus, er/sie hat ausgesprochen",slovak:"to express"},
{german:"(sich) bedanken",slovak:"to thank, express gratitude"},
{german:"Ihr Lieben!",slovak:"Dear ones!"},
{german:"rund",slovak:"round"},
{german:"schwanger",slovak:"pregnant"},
{german:"die Überraschung, -en",slovak:"surprise"},
{german:"basteln",slovak:"to craft"},
{german:"die Windeltorte, -n",slovak:"diaper cake"},
{german:"Bescheid sagen",slovak:"to inform"},
{german:"die Zusage, -n",slovak:"acceptance"},
{german:"zurück|kommen, er/sie kommt zurück, er/sie ist zurückgekommen",slovak:"to return"},
{german:"zu dritt",slovak:"three together"},
{german:"gratulieren",slovak:"to congratulate"},
{german:"auf|nehmen, er/sie nimmt auf, er/sie hat aufgenommen",slovak:"to record"},
{german:"das Bowling",slovak:"bowling"},
{german:"das Picknick, -e",slovak:"picnic"},
{german:"die Musikanlage, -n",slovak:"sound system"},
{german:"der DJ, -s",slovak:"DJ"},
{german:"das Geschirr",slovak:"dishes"},
{german:"das Besteck",slovak:"cutlery"},
{german:"das Geburtstagsmuffel-Lied, -er",slovak:"birthday grouch song"},
{german:"den Rest geben, er/sie gibt den Rest, er/sie hat den Rest gegeben",slovak:"to finish off"},
{german:"schrecklich",slovak:"terrible"},
{german:"öde",slovak:"boring"},
{german:"die Strophe, -n",slovak:"verse (of a song)"},
{german:"träumen",slovak:"to dream"},
{german:"(sich) langweilen",slovak:"to be bored"},
{german:"der Profi, -s",slovak:"professional"},
{german:"der Hochzeitsplaner, -",slovak:"wedding planner"},
{german:"die Hochzeitsplanerin, -nen",slovak:"female wedding planner"},
{german:"der Luftballon, -s",slovak:"balloon"},
{german:"der Brautstrauß, -äu-e",slovak:"bridal bouquet"},
{german:"die Limousine, -n",slovak:"limousine"},
{german:"das Standesamt, -ä-er",slovak:"registry office"},
{german:"das Herz, -en",slovak:"heart"},
{german:"das Brautpaar, -e",slovak:"bridal couple"},
{german:"übernehmen, er/sie übernimmt, er/sie hat übernommen",slovak:"to take over"},
{german:"die Dekoration, -en",slovak:"decoration"},
{german:"der Vorschlag, -ä-e",slovak:"suggestion"},
{german:"die Braut, -äu-e",slovak:"bride"},
{german:"der Bräutigam, -e",slovak:"groom"},
{german:"die Möglichkeit, -en",slovak:"possibility"},
{german:"schief|gehen, er/sie geht schief, er/sie ist schiefgegangen",slovak:"to go wrong"},
{german:"die Panne, -n",slovak:"mishap"},
{german:"aus|fallen, er/sie fällt aus, er/sie ist ausgefallen",slovak:"to fail [power]"},
{german:"das Gewitter, -",slovak:"thunderstorm"},
{german:"kaputt|machen",slovak:"to destroy"},
{german:"verantwortlich",slovak:"responsible"},
{german:"die Behörde, -n",slovak:"public authority"},
]