const listOfWords = [
	{german:"bewerten",slovak:"to evaluate"},
{german:"dass",slovak:"that"},
{german:"der Papagei, -en",slovak:"parrot"},
{german:"das Haustier, -e",slovak:"pet"},
{german:"das Tischtennis",slovak:"table tennis"},
{german:"das Turmspringen",slovak:"platform diving"},
{german:"die Luftgitarre, -n",slovak:"air guitar"},
{german:"das Märchen, -",slovak:"fairy tale"},
{german:"die Tante, -n",slovak:"aunt"},
{german:"schneiden, er/sie schneidet, er/sie hat geschnitten",slovak:"to cut"},
{german:"springen, er/sie springt, er/sie ist gesprungen",slovak:"to jump"},
{german:"vor|lesen, er/sie liest vor, er/sie hat vorgelesen",slovak:"to read aloud (to someone)"},
{german:"der Onkel, -",slovak:"uncle"},
{german:"der Sushi-Kurs, -e",slovak:"sushi making class"},
{german:"der Wettbewerb, -e",slovak:"competition"},
{german:"aus|probieren",slovak:"to try out"},
{german:"Das ist nichts für mich.",slovak:"That's not for me / I'm not interested."},
{german:"intelligent",slovak:"intelligent, smart"},
{german:"Oje!",slovak:"Oh dear!"},
{german:"So ein Quatsch!",slovak:"Nonsense!"},
{german:"das Kochen",slovak:"cooking"},
{german:"das Luftgitarrespielen",slovak:"playing air guitar"},
{german:"das Vorlesen",slovak:"reading aloud, recitation"},
{german:"das Angeln",slovak:"fishing"},
{german:"das Briefmarkensammeln",slovak:"stamp collecting"},
{german:"das Chatten",slovak:"chatting online"},
{german:"das Fußballspielen",slovak:"playing football"},
{german:"das Klettern",slovak:"climbing"},
{german:"klettern",slovak:"to climb"},
{german:"das Tanzen",slovak:"dancing"},
{german:"anstrengend",slovak:"exhausting"},
{german:"blöd",slovak:"stupid"},
{german:"spannend",slovak:"exciting"},
{german:"die Reportage, -n",slovak:"report"},
{german:"nervös",slovak:"nervous"},
{german:"der Spieler, -",slovak:"player"},
{german:"die Spielerin, -nen",slovak:"female player"},
{german:"der Zeitungsbericht, -e",slovak:"newspaper report"},
{german:"das Becherstapeln",slovak:"cup stacking"},
{german:"die Meisterschaft, -en",slovak:"championship"},
{german:"dabei sein, er/sie ist dabei, er/sie war dabei",slovak:"to participate"},
{german:"der Becher, -",slovak:"cup"},
{german:"der Pfiff, -e",slovak:"whistle"},
{german:"stapeln",slovak:"to stack, build a tower"},
{german:"genauso",slovak:"the same"},
{german:"die Stoppuhr, -en",slovak:"stopwatch"},
{german:"die Sekunde, -n",slovak:"second"},
{german:"nächst-",slovak:"next"},
{german:"das Mal, -e",slovak:"time"},
{german:"schaffen",slovak:"to manage"},
{german:"üben",slovak:"to practice"},
{german:"das Fernsehen",slovak:"television"},
{german:"vor allem",slovak:"above all"},
{german:"der Erwachsene, -n",slovak:"adult (male)"},
{german:"die Erwachsene, -n",slovak:"adult (female)"},
{german:"mit|machen",slovak:"to participate"},
{german:"die Hand-Augen-Koordination",slovak:"hand-eye coordination"},
{german:"die Reaktion, -en",slovak:"reaction"},
{german:"das Lernen",slovak:"learning"},
{german:"merken",slovak:"to notice"},
{german:"denn",slovak:"because"},
{german:"Spaß bringen, er/sie bringt Spaß, er/sie hat Spaß gebracht",slovak:"to be fun"},
{german:"die Mathematik (Mathe)",slovak:"mathematics"},
{german:"häufig",slovak:"frequently"},
{german:"gewinnen, er/sie gewinnt, er/sie hat gewonnen",slovak:"to win"},
{german:"der Weitsprung",slovak:"long jump"},
{german:"pfeifen, er/sie pfeift, er/sie hat gepfiffen",slovak:"to whistle"},
{german:"malen",slovak:"to paint"},
{german:"an|halten, er/sie hält an, er/sie hat angehalten",slovak:"to hold (breath)"},
{german:"das Gedicht, -e",slovak:"poem"},
{german:"die Veranstaltung, -en",slovak:"event"},
{german:"der Poetry Slam, -s",slovak:"poetry slam"},
{german:"der Slam, -s",slovak:"slam, competition"},
{german:"die Stadthalle, -n",slovak:"civic hall"},
{german:"die Liste, -n",slovak:"list"},
{german:"der Poeten-Wettbewerb, -e",slovak:"poetry competition"},
{german:"statt|finden, er/sie findet statt, er/sie hat stattgefunden",slovak:"to take place"},
{german:"das Wort, -ö-er",slovak:"word"},
{german:"schlagen, er/sie schlägt, er/sie hat geschlagen",slovak:"[here] to beat, win"},
{german:"kämpfen",slovak:"to fight"},
{german:"eigen-",slovak:"own"},
{german:"vor|sprechen, er/sie spricht vor, er/sie hat vorgesprochen",slovak:"to recite"},
{german:"auswendig",slovak:"by heart"},
{german:"das Publikum",slovak:"audience"},
{german:"wählen",slovak:"to choose, select"},
{german:"der Sieger, -",slovak:"winner"},
{german:"die Siegerin, -nen",slovak:"female winner"},
{german:"der Inhalt, -e",slovak:"content"},
{german:"die Show, -s",slovak:"show"},
{german:"furchtbar",slovak:"terrible, awful"},
{german:"los geht's",slovak:"let's start"},
]