const listOfWords = [
{german:"das Fest, -e",slovak:"party"},
{german:"manch-",slovak:"some-"},
{german:"verdienen",slovak:"earn"},
{german:"der Fotograf, -en",slovak:"photographer, m."},
{german:"die Fotografin, -nen",slovak:"photographer, f."},
{german:"die Hochzeit, -en",slovak:"wedding"},
{german:"die Aufgabe, -n",slovak:"task"},
{german:"der Kunde, -n",slovak:"customer, m."},
{german:"die Kundin, -nen",slovak:"customer, f."},
{german:"freundlich",slovak:"kind"},
{german:"der Weihnachtsmann, -ä-er",slovak:"Santa Claus"},
{german:"das Kostüm, -e",slovak:"costume"},
{german:"vorbereiten",slovak:"prepare"},
{german:"geben, er/sie gibt, er/sie hat gegeben",slovak:"to give"},
{german:"tragen (+Kleidung), er/sie trägt/hat getragen",slovak:"to wear"},
{german:"bekommen, er/sie hat bekommen",slovak:"to get"},
{german:"Geschenke bekommen",slovak:"to get presents"},
{german:"einmal",slovak:"once"},
{german:"der Junge, -en",slovak:"boy"},
{german:"das Gespräch, -e",slovak:"conversation"},
{german:"das Weihnachten (sg.)",slovak:"Christmas"},
{german:"schmücken",slovak:"decorate"},
{german:"Ringe tauschen",slovak:"exchange rings"},
{german:"der Karneval / CH: die Fasnacht",slovak:"carnival"},
{german:"(der) Silvester (sg.)",slovak:"new year’s eve"},
{german:"das Feuerwerk, -e",slovak:"firework"},
{german:"anstossen, er/sie stösst an, hat angestossen",slovak:"to cling the glasses"},
{german:"das Oktoberfest, -e",slovak:"Oktoberfest (annual festival in Munich)"},
{german:"Karussell fahren",slovak:"be (ride) on the carrousel"},
{german:"das Datum, Daten",slovak:"the date"},
{german:"der Feiertag, -e",slovak:"holiday"},
{german:"die Einweihungsparty, -s",slovak:"houswarming party"},
{german:"die Antwort, -en",slovak:"answer"},
{german:"bis zu (+ Tag/Uhrzeit)",slovak:"until"},
{german:"Bitte gebt uns bis zum 4. Mai eine Antwort.",slovak:"Please give us an answer until 5th of May."},
{german:"die Karte (Einladungskarte), -en",slovak:"card (invitation); also: map"},
{german:"zeigen",slovak:"show"},
{german:"das Salz",slovak:"salt"},
{german:"das Glück",slovak:"luck"},
{german:"schenken",slovak:"give (as a present)"},
{german:"die Pflanze, -n",slovak:"plant"},
{german:"die Sache, -n",slovak:"thing; issue"},
{german:"das Mädchen, -",slovak:"girl"},
{german:"der Kuss, -ü-e",slovak:"kiss"},
{german:"einen Kuss geben",slovak:"to give a kiss = to kiss"},
{german:"die Unterschrift, -en",slovak:"signature"},
{german:"die Anrede, -n",slovak:"salutation"},
{german:"singen, er/sie hat gesungen",slovak:"to sing"},
{german:"lang",slovak:"long"},
{german:"Die Strasse ist zwei Kilometer lang. The street is two kilometers long.",slovak:""},
{german:"beginnen, er/sie hat begonnen",slovak:"to begin"},
{german:"der Teilnehmer, -",slovak:"participant, m."},
{german:"die Teilnehmerin, -nen",slovak:"participant, f."},
{german:"der Besucher, -",slovak:"visitor, m."},
{german:"die Besucherin, -nen",slovak:"visitor, f."},
{german:"enden",slovak:"to end"},
{german:"das Ende, -n",slovak:"the end"},
];