const listOfWords = [
{german:"der Morgen, -",slovak:"the morning"},
{german:"am (+ Tageszeit)",slovak:"in the (+ daytime)"},
{german:"am Morgen",slovak:"in the morning"},
{german:"morgens",slovak:"(every) morning"},
{german:"der Vormittag, -e",slovak:"morning (“before noon”)"},
{german:"der Mittag, -e",slovak:"noon"},
{german:"der Nachmittag, -e",slovak:"afternoon"},
{german:"der Abend, -e",slovak:"evening"},
{german:"die Nacht, -ä-e",slovak:"night"},
{german:"in der Nacht",slovak:"at night"},
{german:"nachts",slovak:"“"},
{german:"freihaben",slovak:"to have … (Monday) off"},
{german:"Wie spät ist es?",slovak:"What time is it? (“How late is it?”)"},
{german:"Es ist zehn Uhr.",slovak:"It’s ten o’clock."},
{german:"nach/vor (+ Uhrzeit)",slovak:"past/to (+time)"},
{german:"Es ist fünf nach sechs.",slovak:"It’s five past six."},
{german:"halb / Viertel vor / Viertel nach (+ Uhrzeit)",slovak:"half (to!) / quarter to / quarter past (+ time)"},
{german:"aufstehen",slovak:"to get up"},
{german:"ausschlafen, er/sie schläft aus",slovak:"to sleep in"},
{german:"von (+ Uhrzeit) bis (+ Uhrzeit)",slovak:"from… until..."},
{german:"der Termin, -e",slovak:"appointment"},
{german:"einen Termin haben",slovak:"to have an appointment"},
{german:"können, er/sie kann",slovak:"to can"},
{german:"Ich kann für dich arbeiten.",slovak:"I can work for you."},
{german:"ruhig",slovak:"quiet"},
{german:"Pause machen",slovak:"to have (“make”) a break"},
{german:"die Post (sg.)",slovak:"mail"},
{german:"holen",slovak:"to get (something)"},
{german:"morgen",slovak:"tomorrow"},
{german:"abholen",slovak:"to pick up somebody"},
{german:"der Deutschkurs, -e",slovak:"German class"},
{german:"telefonieren",slovak:"to be on the phone"},
{german:"Auf Wiederhören.",slovak:"Goodbye (“hear you again”)"},
{german:"bis (+ Tag)",slovak:"until"},
{german:"Bis Dienstag!",slovak:"till Tuesday!"},
{german:"bringen",slovak:"bring"},
{german:"der Monat, -e",slovak:"month"},
{german:"im (+ Monat)",slovak:"in (+ month)"},
{german:"der Januar",slovak:"January"},
{german:"der Februar",slovak:"February"},
{german:"der März",slovak:"March"},
{german:"der April",slovak:"April"},
{german:"der Mai",slovak:"May"},
{german:"der Juni",slovak:"June"},
{german:"der Juni",slovak:"July"},
{german:"der August",slovak:"August"},
{german:"der September",slovak:"September"},
{german:"der Oktober",slovak:"October"},
{german:"der November",slovak:"November"},
{german:"der Dezember",slovak:"December"},
{german:"der Besuch, -e",slovak:"visit"},
{german:"Lust haben",slovak:"to feel like"},
{german:"wenig",slovak:"little"},
{german:"viel, -e",slovak:"much, many"},
{german:"das Bett, -en",slovak:"bed"},
{german:"ins Bett gehen",slovak:"to go to bed"},
{german:"bleiben",slovak:"to stay"},
{german:"Ich bleibe nicht lange.",slovak:"I stay not for long."},
{german:"zwischen (+ Uhrzeit) und (+ Uhrzeit)",slovak:"between (+time) and (+time)"},
{german:"früh",slovak:"early"},
{german:"spät",slovak:"late"},
{german:"bezahlen",slovak:"pay"},
{german:"verkaufen",slovak:"sell"},
];