const listOfWords = [
	{german:"gut|tun, er/sie tut gut, er/sie hat gutgetan",slovak:"to do good"},
{german:"die Freundschaft, -en",slovak:"friendship"},
{german:"woran (denken Sie)",slovak:"what (are you thinking of)"},
{german:"das Wörternetz, -e",slovak:"word web"},
{german:"ehrlich",slovak:"honest"},
{german:"Spaß haben, er/sie hat Spaß, er/sie hatte Spaß",slovak:"to have fun"},
{german:"das Zitat, -e",slovak:"quote"},
{german:"der Applaus",slovak:"applause, cheers"},
{german:"gleich-",slovak:"same"},
{german:"der Industrielle, -n",slovak:"industrialist"},
{german:"das Unglück",slovak:"misfortune"},
{german:"der Philosoph, -en",slovak:"philosopher"},
{german:"die Philosophin, -nen",slovak:"female philosopher"},
{german:"die Zeitschrift, -en",slovak:"magazine"},
{german:"das Magazin, -e",slovak:"magazine (various content)"},
{german:"das Beste",slovak:"the best"},
{german:"klug",slovak:"smart"},
{german:"die Biene, -n",slovak:"bee"},
{german:"verliebt (sein), er/sie ist verliebt, er/sie war verliebt",slovak:"to be in love"},
{german:"neugierig",slovak:"curious (to learn something)"},
{german:"ängstlich",slovak:"fearful"},
{german:"stark",slovak:"strong"},
{german:"dick",slovak:"fat"},
{german:"das Wildschwein, -e",slovak:"wild boar"},
{german:"mutig",slovak:"brave"},
{german:"schwach",slovak:"weak"},
{german:"das Abenteuer, -",slovak:"adventure"},
{german:"weinen",slovak:"to cry"},
{german:"der Unsinn",slovak:"nonsense"},
{german:"das Huhn, -ü-er",slovak:"chicken"},
{german:"zusammen|halten, sie halten zusammen, sie haben zusammengehalten",slovak:"to stay united"},
{german:"übersetzen",slovak:"to translate"},
{german:"dünn",slovak:"thin"},
{german:"böse",slovak:"[here] angry"},
{german:"dumm",slovak:"stupid, silly"},
{german:"blond",slovak:"blonde"},
{german:"der Indianer, -",slovak:"Native American"},
{german:"das Feuer",slovak:"fire"},
{german:"als",slovak:"when"},
{german:"brennen, er/sie brennt, er/sie hat gebrannt",slovak:"to burn"},
{german:"der Rauch",slovak:"smoke"},
{german:"sich verlieben",slovak:"to fall in love"},
{german:"der Ärger",slovak:"trouble, problems"},
{german:"die Zigarette, -n",slovak:"cigarette"},
{german:"eifersüchtig",slovak:"jealous"},
{german:"weiter|gehen, er/sie geht weiter, er/sie ist weitergegangen",slovak:"to continue (on one's way)"},
{german:"der Sandkasten, -ä-",slovak:"sandbox"},
{german:"nach|erzählen",slovak:"to retell, narrate"},
{german:"das Thema, Themen",slovak:"topic"},
{german:"das Vermischte",slovak:"miscellaneous"},
{german:"tierisch",slovak:"[here metaph.] incredible"},
{german:"ungewöhnlich",slovak:"unusual"},
{german:"zum … bringen, er/sie bringt, er/sie hat gebracht",slovak:"to make (someone) ..."},
{german:"der Bär, -en",slovak:"male bear"},
{german:"die Bärin, -nen",slovak:"female bear"},
{german:"lieb",slovak:"loving"},
{german:"das Zuhause",slovak:"home"},
{german:"der Käfig, -e",slovak:"cage"},
{german:"schreien, er/sie schreit, er/sie hat geschrien",slovak:"to scream"},
{german:"leid|tun, er/sie tut leid, er/sie hat leidgetan",slovak:"to regret, feel sorry"},
{german:"das Alter",slovak:"age"},
{german:"berichten",slovak:"[here] to report on the topic [media]"},
{german:"offiziell",slovak:"official"},
{german:"zusammen|leben",slovak:"to live together"},
{german:"teilen",slovak:"to share"},
]