const listOfWords = [
	{german:"wenn",slovak:"if"},
{german:"der Selbsttest, -s",slovak:"self-diagnosis"},
{german:"unfreundlich",slovak:"unfriendly"},
{german:"sich verhalten, er/sie verhält sich, er/sie hat sich verhalten",slovak:"to behave"},
{german:"die Situation, -en",slovak:"situation"},
{german:"einig-",slovak:"some"},
{german:"komplett",slovak:"completely"},
{german:"ab|stürzen",slovak:"[here] to crash"},
{german:"der IT-Support",slovak:"IT support"},
{german:"der IT-Experte, -n",slovak:"IT expert"},
{german:"die IT-Expertin, -nen",slovak:"female IT expert"},
{german:"beantworten",slovak:"to answer"},
{german:"aktuell",slovak:"current"},
{german:"außerdem",slovak:"besides"},
{german:"der Aufzug, -ü-e",slovak:"elevator"},
{german:"die Treppe, -n",slovak:"stairs [staircase]"},
{german:"peinlich",slovak:"embarrassing"},
{german:"jemand",slovak:"someone"},
{german:"grüßen",slovak:"to greet"},
{german:"vorsichtig",slovak:"careful"},
{german:"das Team, -s",slovak:"team"},
{german:"gründen",slovak:"to establish"},
{german:"sich beschweren",slovak:"to complain"},
{german:"die Hilfe, -n",slovak:"help"},
{german:"das Gehalt, -ä-er",slovak:"salary"},
{german:"doppelt-",slovak:"double"},
{german:"reagieren",slovak:"to react"},
{german:"der Psychologe, -n",slovak:"psychologist"},
{german:"die Psychologin, -nen",slovak:"female psychologist"},
{german:"sich wundern",slovak:"to wonder"},
{german:"raus|gehen, er/sie geht raus, er/sie ist rausgegangen",slovak:"to go out"},
{german:"geschäftlich",slovak:"business-related"},
{german:"der Anhang, -ä-e",slovak:"attachment"},
{german:"das Postfach, -ä-er",slovak:"post office box"},
{german:"das Protokoll, -e",slovak:"protocol"},
{german:"löschen",slovak:"to delete"},
{german:"speichern",slovak:"to save"},
{german:"senden",slovak:"to send"},
{german:"weiter|leiten",slovak:"to forward"},
{german:"beenden",slovak:"to end"},
{german:"aus|drucken",slovak:"to print"},
{german:"die Datei, -en",slovak:"(digital) file"},
{german:"der Ordner, -",slovak:"folder"},
{german:"beenden",slovak:"to end"},
{german:"aus|drucken",slovak:"to print"},
{german:"die Besprechung, -en",slovak:"discussion, meeting"},
{german:"ein|schalten",slovak:"to switch on (electrical/ electronic device)"},
{german:"die Terminanfrage, -n",slovak:"appointment request"},
{german:"die Daten (Pl.)",slovak:"data"},
{german:"Sehr geehrte/r …",slovak:"Dear Sir/Madam..."},
{german:"vor|schlagen, er/sie schlägt vor, er/sie hat vorgeschlagen",slovak:"to suggest"},
{german:"Bescheid geben, er/sie gibt Bescheid, er/sie hat Bescheid gegeben",slovak:"to notify"},
{german:"technisch",slovak:"technical"},
{german:"Mit freundlichen Grüßen",slovak:"Kind regards"},
{german:"bestätigen",slovak:"to confirm"},
{german:"verschieben, er/sie verschiebt, er/sie hat verschoben",slovak:"to postpone"},
{german:"ab|sagen",slovak:"to cancel (appointment)"},
{german:"Sehr geehrte Damen und Herren, …",slovak:"Dear Ladies and Gentlemen, ..."},
{german:"die Absage, -n",slovak:"cancellation of scheduled appointment"},
{german:"privat",slovak:"personal, private"},
{german:"die Sicherheit",slovak:"security"},
{german:"die Studie, -n",slovak:"study"},
{german:"die Fachhochschule, -n",slovak:"University of Applied Sciences"},
{german:"d.h. (das heißt)",slovak:"i.e."},
{german:"sinnvoll",slovak:"meaningful"},
{german:"abwechslungsreich",slovak:"varied, interesting"},
{german:"ein Drittel",slovak:"one third"},
]