const listOfWords = [
	{german:"die Lage, -n",slovak:"location, position"},
{german:"die Wohnsituation",slovak:"housing situation"},
{german:"die Wohnungsanzeige, -n",slovak:"housing advertisement"},
{german:"der Besichtigungstermin, -e",slovak:"viewing appointment"},
{german:"vereinbaren",slovak:"to agree (on something)"},
{german:"der Dom, -e",slovak:"cathedral"},
{german:"der Zoo, -s",slovak:"zoo"},
{german:"das Bankenviertel, -",slovak:"banking district"},
{german:"verkehrsgünstig",slovak:"with good transport connections"},
{german:"die Altbauwohnung, -en",slovak:"apartment in an old building"},
{german:"die Miete, -n",slovak:"rent"},
{german:"außerhalb",slovak:"[here] outside the city"},
{german:"los sein, es ist … los, es war … los",slovak:"[here] there is life"},
{german:"der Fluglärm",slovak:"aircraft noise"},
{german:"stören",slovak:"to disturb"},
{german:"das Stichwort, -ö-er",slovak:"keyword"},
{german:"die Abkürzung, -en",slovak:"abbreviation"},
{german:"die Einbauküche (EBK), -n",slovak:"fitted kitchen"},
{german:"die Nebenkosten (NK) (Pl.)",slovak:"additional costs, utilities"},
{german:"das Obergeschoss (OG), -e",slovak:"upper floor"},
{german:"das Dachgeschoss (DG), -e",slovak:"attic"},
{german:"das Erdgeschoss (EG), -e",slovak:"ground floor"},
{german:"der Vermieter, -",slovak:"landlord"},
{german:"die Vermieterin, -nen",slovak:"female landlord"},
{german:"der Mieter, -",slovak:"tenant"},
{german:"die Mieterin, -nen",slovak:"female tenant"},
{german:"der Strom",slovak:"electricity"},
{german:"die Anzeige, -n",slovak:"advertisement"},
{german:"sich interessieren",slovak:"to be interested"},
{german:"jetzig-",slovak:"current"},
{german:"monatlich",slovak:"monthly"},
{german:"in Ordnung (sein)",slovak:"to be okay"},
{german:"das Spielzeug",slovak:"toys"},
{german:"die Kiste, -n",slovak:"box"},
{german:"die Katzenbox, -en",slovak:"cat carrier"},
{german:"der Sessel, -",slovak:"armchair"},
{german:"der Keller, -",slovak:"basement"},
{german:"ein|richten",slovak:"to furnish"},
{german:"die Vorbereitung, -en",slovak:"preparation"},
{german:"die Einzelarbeit",slovak:"individual work"},
{german:"die Gruppendiskussion, -en",slovak:"group discussion"},
{german:"die Kleinanzeige, -n",slovak:"classified ad"},
{german:"der Hof, -ö-e",slovak:"courtyard"},
{german:"besorgen",slovak:"to get"},
{german:"das Würstchen, -",slovak:"small sausage"},
{german:"Achtung!",slovak:"Attention!"},
{german:"die Bauarbeiten (Pl.)",slovak:"construction work"},
{german:"bitten, er/sie bittet, er/sie hat gebeten",slovak:"to ask"},
{german:"das Verständnis",slovak:"understanding"},
{german:"das Meerschweinchen, -",slovak:"guinea pig"},
{german:"weg|laufen, er/sie läuft weg, er/sie ist weggelaufen",slovak:"to run away"},
{german:"der Finderlohn, -ö-e",slovak:"finder's reward"},
{german:"verschenken",slovak:"to give away"},
{german:"das Mountainbike, -s",slovak:"mountain bike"},
{german:"der Mitbewohner, -",slovak:"roommate"},
{german:"die Mitbewohnerin, -nen",slovak:"female roommate"},
{german:"stellen",slovak:"to place, put"},
{german:"der Kinderwagen, -",slovak:"baby carriage"},
{german:"vorbei|kommen, er/sie kommt vorbei, er/sie ist vorbeigekommen",slovak:"[here] to fit (to pass)"},
{german:"weg|fliegen, er/sie fliegt weg, er/sie ist weggeflogen",slovak:"to fly away"},
{german:"schließen, er/sie schließt, er/sie hat geschlossen",slovak:"to close"},
{german:"fremd",slovak:"foreign"},
]