const listOfWords = [
	{german:"die Burg, -en",slovak:"castle, fortress"},
{german:"die Produktion, -en",slovak:"production"},
{german:"das Käsefondue, -s",slovak:"cheese fondue"},
{german:"das Denkmal, -ä-er",slovak:"monument"},
{german:"der Strandkorb, -ö-e",slovak:"beach basket chair"},
{german:"die Bank, -en",slovak:"bank"},
{german:"die Messe, -n",slovak:"exhibition"},
{german:"der Autosalon, -s",slovak:"motor show"},
{german:"das Geburtshaus, -äu-er",slovak:"birthplace (of a notable person)"},
{german:"der Gartenzwerg, -e",slovak:"garden gnome"},
{german:"das Stadion, Stadien",slovak:"stadium"},
{german:"das Uhrwerk, -e",slovak:"clockwork mechanism"},
{german:"der Umschlag, -ä-e",slovak:"[here] cover"},
{german:"grüßen",slovak:"to greet"},
{german:"Moin!",slovak:"Good morning! [in Northern Germany]"},
{german:"der Dialekt, -e",slovak:"dialect"},
{german:"auf Reisen (sein)",slovak:"to travel"},
{german:"das Vergangene",slovak:"past, bygone"},
{german:"das Reisen",slovak:"traveling"},
{german:"das Flugticket, -s",slovak:"flight ticket"},
{german:"der Flughafen, -ä-",slovak:"airport"},
{german:"der Abflug, -ü-e",slovak:"departure (flight)"},
{german:"ab|fliegen, er/sie fliegt ab, er/sie ist abgeflogen",slovak:"to depart [plane]"},
{german:"die Ankunft",slovak:"arrival"},
{german:"an|kommen, er/sie kommt an, er/sie ist angekommen",slovak:"to arrive"},
{german:"die Eintrittskarte, -n",slovak:"entrance ticket"},
{german:"das Gepäck",slovak:"luggage"},
{german:"die Postkarte, -n",slovak:"postcard"},
{german:"die Briefmarke, -n",slovak:"stamp"},
{german:"das Musikfestival, -s",slovak:"music festival"},
{german:"die Veranstaltung, -en",slovak:"event"},
{german:"die Semesterferien (Pl.)",slovak:"semester break"},
{german:"die Entscheidung, -en",slovak:"decision"},
{german:"da sein, er/sie ist da, er/sie war da",slovak:"[here] to be made [decision]"},
{german:"gleich",slovak:"immediately"},
{german:"der Flug, -ü-e",slovak:"flight"},
{german:"buchen",slovak:"to book (a seat, ticket)"},
{german:"der Rucksack, -ä-e",slovak:"backpack"},
{german:"Hurra!",slovak:"Hooray!"},
{german:"der Anfang, -ä-e",slovak:"beginning"},
{german:"stressig",slovak:"stressful"},
{german:"der Reisepass, -ä-e",slovak:"passport"},
{german:"zum Glück",slovak:"fortunately"},
{german:"verlieren, er/sie verliert, er/sie hat verloren",slovak:"to lose"},
{german:"deshalb",slovak:"therefore"},
{german:"empfehlen, er/sie empfiehlt, er/sie hat empfohlen",slovak:"to recommend"},
{german:"besichtigen",slovak:"to visit (a sight)"},
{german:"das Wohnhaus, -äu-er",slovak:"residence (where a personality lived)"},
{german:"überall",slovak:"everywhere"},
{german:"der Sitzplatz, -ä-e",slovak:"seat"},
{german:"erklären",slovak:"to explain"},
{german:"hoffentlich",slovak:"hopefully"},
{german:"sofort",slovak:"immediately"},
{german:"die Verlustanzeige, -n",slovak:"lost property report"},
{german:"die Eisdiele, -n",slovak:"ice cream parlor"},
{german:"die Boutique, -n",slovak:"boutique"},
{german:"die Buchhandlung, -en",slovak:"bookstore"},
{german:"das Tor, -e",slovak:"gate"},
{german:"durch … gehen",slovak:"to pass through (a point)"},
{german:"gegen … laufen",slovak:"to bump into (someone)"},
{german:"an … vorbei",slovak:"to pass in front of"},
{german:"gegenüber",slovak:"opposite"},
{german:"die Handtasche, -n",slovak:"handbag"},
{german:"weg sein, er/sie ist weg, er/sie war weg",slovak:"[here] to be lost"},
{german:"zurück|gehen, er/sie geht zurück, er/sie ist zurückgegangen",slovak:"to return"},
{german:"der Park, -s",slovak:"park"},
{german:"die Geldbörse, -n",slovak:"wallet"},
{german:"der Parkplatz, -ä-e",slovak:"parking lot"},
{german:"der Bundespräsident, -en",slovak:"federal president"},
{german:"die Bundespräsidentin, -nen",slovak:"female federal president"},
{german:"der Kaiser, -",slovak:"emperor"},
{german:"die Kaiserin, -nen",slovak:"empress"},
{german:"der Sisi-Fan, -s",slovak:"fan of (Empress) Sisi"},
{german:"die Architektur, -en",slovak:"architecture"},
{german:"die Bar, -s",slovak:"bar"},
{german:"die Brasserie, -n",slovak:"brasserie [restaurant]"},
{german:"die Natur",slovak:"nature"},
{german:"die Entspannung",slovak:"relaxation"},
{german:"die Kultur, -en",slovak:"culture"},
{german:"die Öffnungszeit, -en",slovak:"opening hours"},
{german:"bieten, er/sie bietet, er/sie hat geboten",slovak:"to offer"},
{german:"exotisch",slovak:"exotic"},
{german:"genießen, er/sie genießt, er/sie hat genossen",slovak:"to enjoy"},
{german:"mehrere",slovak:"several"},
{german:"sitzen, er/sie sitzt, er/sie hat gesessen",slovak:"to sit"},
{german:"z.B. (zum Beispiel)",slovak:"e.g."},
{german:"die Heimatstadt, -ä-e",slovak:"hometown"},
{german:"unbedingt",slovak:"absolutely"},
]