const listOfWords = [
	{german:"der Alltag",slovak:"everyday life"},
{german:"der Wahnsinn",slovak:"madness, insanity"},
{german:"das Medium, Medien",slovak:"media"},
{german:"ab",slovak:"from, after (a point in time)"},
{german:"der App-Store, -s",slovak:"app store"},
{german:"die App, -s",slovak:"application"},
{german:"der Einkauf, -äu-e",slovak:"purchase"},
{german:"der Supermarkt, -ä-e",slovak:"supermarket"},
{german:"die Apotheke, -n",slovak:"pharmacy"},
{german:"in der Nähe",slovak:"nearby"},
{german:"planen",slovak:"to plan"},
{german:"aus|wählen",slovak:"to select"},
{german:"gemeinsam-",slovak:"common"},
{german:"sparen",slovak:"to save"},
{german:"unterwegs",slovak:"on the way"},
{german:"der Fahrplan, -ä-e",slovak:"timetable"},
{german:"öffentlich",slovak:"public"},
{german:"die Organisation, -en",slovak:"organization"},
{german:"informieren",slovak:"to inform"},
{german:"koordinieren",slovak:"to coordinate"},
{german:"(sich) an|ziehen, er/sie zieht an, er/sie hat angezogen",slovak:"to dress, to wear"},
{german:"(sich) aus|ziehen, er/sie zieht aus, er/sie hat ausgezogen",slovak:"to undress"},
{german:"(sich) waschen, er/sie wäscht, er/sie hat gewaschen",slovak:"to wash oneself"},
{german:"(sich) kämmen",slovak:"to comb oneself"},
{german:"(sich) rasieren",slovak:"to shave"},
{german:"(sich) schminken",slovak:"to put on makeup"},
{german:"(sich) an|sehen, er/sie sieht an, er/sie hat angesehen",slovak:"to look at, observe"},
{german:"der Spiegel, -",slovak:"mirror"},
{german:"nie wieder",slovak:"never again"},
{german:"verschlafen, er/sie verschläft, er/sie hat verschlafen",slovak:"to oversleep"},
{german:"(sich) duschen",slovak:"to shower"},
{german:"es eilig haben",slovak:"to be in a hurry"},
{german:"die Wäsche (Pl.)",slovak:"laundry"},
{german:"auf|hängen",slovak:"to hang up"},
{german:"(sich) streiten, er/sie streitet, er/sie hat gestritten",slovak:"to argue"},
{german:"der Stress",slovak:"stress"},
{german:"pünktlich",slovak:"punctual"},
{german:"sauer",slovak:"[here] angry"},
{german:"froh",slovak:"happy"},
{german:"(sich) ärgern",slovak:"to get angry"},
{german:"sich beeilen",slovak:"to hurry"},
{german:"(sich) entschuldigen",slovak:"to apologize"},
{german:"sich freuen",slovak:"to be happy"},
{german:"(sich) fühlen",slovak:"to feel"},
{german:"(sich) treffen, er/sie trifft, er/sie hat getroffen",slovak:"to meet"},
{german:"total",slovak:"totally"},
{german:"es ist hektisch",slovak:"there is stress"},
{german:"der Kindergarten, -ä-",slovak:"kindergarten"},
{german:"der Haushalt, -e",slovak:"household"},
{german:"die Schuld",slovak:"blame"},
{german:"gerade",slovak:"[here] currently"},
{german:"die Wellness",slovak:"wellness"},
{german:"der Werbetext, -e",slovak:"advertising text"},
{german:"positiv",slovak:"positive"},
{german:"raus",slovak:"out"},
{german:"die Übersicht, -en",slovak:"overview"},
{german:"das Seminar, -e",slovak:"seminar"},
{german:"das Hostel, -s",slovak:"hostel"},
{german:"das Holz-Haus, -äu-er",slovak:"wooden house"},
{german:"der Wellness-Bereich, -e",slovak:"wellness area"},
{german:"die Jugendherberge, -n",slovak:"youth hostel"},
{german:"der Quadratmeter (m²), -",slovak:"square meter"},
{german:"die Erholung",slovak:"relaxation"},
{german:"finnisch",slovak:"Finnish"},
{german:"Bio-",slovak:"organic"},
{german:"das Kräuter-Dampfbad, -ä-er",slovak:"herbal steam bath"},
{german:"der Ruheraum, -äu-e",slovak:"relaxation room"},
{german:"der Blick",slovak:"[here] view"},
{german:"das Alpenpanorama, -panoramen",slovak:"panoramic view of the Alps"},
{german:"das Hallenbad, -ä-er",slovak:"indoor swimming pool"},
{german:"der Whirlpool, -s",slovak:"whirlpool"},
{german:"(sich) entspannen",slovak:"to relax"},
{german:"vielfältig",slovak:"diverse"},
{german:"der Mitarbeiter, -",slovak:"colleague"},
{german:"die Mitarbeiterin, -nen",slovak:"female colleague"},
{german:"wieder|kommen, er/sie kommt wieder, er/sie ist wiedergekommen",slovak:"to come back"},
{german:"Wow!",slovak:"Wow!"},
{german:"die Idee, -n",slovak:"idea"},
{german:"sich erholen",slovak:"to rest"},
]