const listOfWords = [
	{german:"das Fernsehprogramm, -e",slovak:"TV program"},
{german:"die Sendung, -en",slovak:"broadcast"},
{german:"was für ein-",slovak:"what kind of"},
{german:"das Finale, -",slovak:"finale"},
{german:"der Animationsfilm, -e",slovak:"animated film"},
{german:"das Boulevard-Magazin, -e",slovak:"magazine [program with various topics]"},
{german:"der Krimi, -s",slovak:"detective film"},
{german:"die Animationsserie, -n",slovak:"animated series"},
{german:"die Castingshow, -s",slovak:"talent competition"},
{german:"die Doku(mentation)",slovak:"documentary"},
{german:"die Doku-Serie, -n",slovak:"documentary series"},
{german:"die Familienserie, -n",slovak:"family series"},
{german:"die Komödie, -n",slovak:"comedy"},
{german:"die Nachrichten (Pl.)",slovak:"news"},
{german:"die Sci-Fi-Action",slovak:"science fiction action"},
{german:"romantisch",slovak:"romantic"},
{german:"die Sendung, -en",slovak:"broadcast"},
{german:"das Quiz, -",slovak:"quiz, contest"},
{german:"die Serie, -n",slovak:"series"},
{german:"der Liebesfilm, -e",slovak:"romance film"},
{german:"hübsch",slovak:"pretty"},
{german:"sportlich",slovak:"athletic"},
{german:"der Kandidat, -en",slovak:"candidate"},
{german:"die Kandidatin, -nen",slovak:"female candidate"},
{german:"auf|treten, er/sie tritt auf, er/sie ist aufgetreten",slovak:"to appear"},
{german:"letzt-",slovak:"last"},
{german:"der Erfolg",slovak:"success"},
{german:"zurück|liegen, er/sie liegt zurück, er/sie hat zurückgelegen",slovak:"to be behind, to have happened"},
{german:"die Stimme, -n",slovak:"voice"},
{german:"vorher",slovak:"previously"},
{german:"begleiten",slovak:"to accompany"},
{german:"witzig",slovak:"witty"},
{german:"moderieren",slovak:"to host (a show)"},
{german:"deutschsprachig",slovak:"German-speaking"},
{german:"meist-",slovak:"most"},
{german:"der Sänger, -",slovak:"singer"},
{german:"die Sängerin, -nen",slovak:"female singer"},
{german:"die Stimme, -n",slovak:"[here] vote"},
{german:"der Komiker, -",slovak:"comedian"},
{german:"die Komikerin, -nen",slovak:"female comedian"},
{german:"der Moderator, -en",slovak:"presenter"},
{german:"die Moderatorin, -nen",slovak:"female presenter"},
{german:"verrückt",slovak:"crazy"},
{german:"der Preis, -e",slovak:"[here] prize"},
{german:"plötzlich",slovak:"suddenly"},
{german:"berühmt",slovak:"famous"},
{german:"die Karriere, -n",slovak:"career"},
{german:"das Lied, -er",slovak:"song"},
{german:"der Absatz, -ä-e",slovak:"paragraph"},
{german:"vierköpfig",slovak:"four-member"},
{german:"einzeln",slovak:"individual"},
{german:"das Paar, -e",slovak:"pair"},
{german:"der Teil, -e",slovak:"part"},
{german:"live",slovak:"live"},
{german:"ab|geben, er/sie gibt ab, er/sie hat abgegeben",slovak:"to give (rating)"},
{german:"besonder-",slovak:"special"},
{german:"international",slovak:"international"},
{german:"das Fernsehverhalten",slovak:"TV viewing habits"},
{german:"das Medium, Medien",slovak:"media"},
{german:"aktuell",slovak:"current"},
{german:"das Archiv, -e",slovak:"archive"},
{german:"das Thema, Themen",slovak:"topic"},
{german:"ersetzen",slovak:"to replace"},
{german:"gelten, er/sie gilt, er/sie hat gegolten",slovak:"to apply"},
{german:"normal",slovak:"normal"},
{german:"entscheiden, er/sie entscheidet, er/sie hat entschieden",slovak:"to decide"},
{german:"nutzen",slovak:"to use"},
{german:"der Internetnutzer, -",slovak:"internet user"},
{german:"die Internetnutzerin, -nen",slovak:"female internet user"},
{german:"die Online-Videothek, -en",slovak:"online video library"},
{german:"der Sender, -",slovak:"transmitter, TV channel"},
{german:"das Livestreaming",slovak:"live streaming"},
{german:"die Mediathek, -en",slovak:"media library"},
{german:"halb-",slovak:"half"},
{german:"angemeldet sein, er/sie ist angemeldet, er/sie war angemeldet",slovak:"to be registered"},
{german:"die Pantomime",slovak:"pantomime"},
{german:"das Haar, -e",slovak:"hair"},
{german:"tief",slovak:"deep"},
{german:"das Mietshaus, -äu-er",slovak:"rental house"},
{german:"der Schrebergarten, -ä-",slovak:"allotment garden"},
{german:"die Satellitenschüssel, -n",slovak:"satellite dish"},
{german:"dekorieren",slovak:"to decorate"},
{german:"pflanzen",slovak:"to plant"},
{german:"gießen, er/sie gießt, er/sie hat gegossen",slovak:"to water"},
{german:"das Blatt, -ä-er",slovak:"leaf"},
{german:"das Papier, -e",slovak:"paper"},
{german:"auf|stellen",slovak:"to place"},
{german:"zusammen|fassen",slovak:"to summarize"},
]