const listOfWords = [
{german:"erfragen",slovak:"to ask for/request information"},
{german:"indirekt",slovak:"[here] indirect"},
{german:"das Smartphone-Modell, -e",slovak:"smartphone model"},
{german:"lieferbar",slovak:"available"},
{german:"das Display, -s",slovak:"display (electronic device / mobile)"},
{german:"der Akku, -s",slovak:"battery"},
{german:"der Speicherplatz",slovak:"storage space, memory"},
{german:"der Tarif, -e",slovak:"package/plan (mobile telephony)"},
{german:"der Vertrag, -ä-e",slovak:"contract"},
{german:"die Flatrate, -s",slovak:"flat (monthly) fee"},
{german:"die Prepaid-Karte, -n",slovak:"prepaid card"},
{german:"der Megapixel, -",slovak:"megapixel [image resolution]"},
{german:"der Zoll, -",slovak:"inch"},
{german:"die SMS, -",slovak:"SMS, message"},
{german:"bis zu … (+ Menge)",slovak:"up to ... (+ quantity)"},
{german:"GB (Gigabyte), -",slovak:"gigabyte"},
{german:"MB (Megabyte), -",slovak:"megabyte"},
{german:"silber",slovak:"silver"},
{german:"ob",slovak:"if"},
{german:"die Videofunktion, -en",slovak:"video function"},
{german:"halten, er/sie hält, er/sie hat gehalten",slovak:"to hold"},
{german:"die Audioaufnahme, -n",slovak:"audio recording"},
{german:"die GPS-App, -s",slovak:"GPS application"},
{german:"die Tastatur, -en",slovak:"keyboard"},
{german:"extern",slovak:"external"},
{german:"inklusive",slovak:"inclusive"},
{german:"die Smartwatch, -es",slovak:"smartwatch [\"smart\" watch]"},
{german:"der Stadtplan, -ä-e",slovak:"city map"},
{german:"erkennen",slovak:"to recognize"},
{german:"die Vogelstimme, -n",slovak:"bird's voice"},
{german:"navigieren",slovak:"to navigate, direct, guide"},
{german:"umsonst",slovak:"free"},
{german:"zeichnen",slovak:"to draw"},
{german:"dringend",slovak:"urgent"},
{german:"herunter|laden, er/sie lädt herunter, er/sie hat heruntergeladen",slovak:"to download (from the internet)"},
{german:"erfinden, er/sie erfindet, er/sie hat erfunden",slovak:"to invent"},
{german:"das Icon, -s",slovak:"icon"},
{german:"eigentlich",slovak:"actually"},
{german:"digital",slovak:"digital"},
{german:"die Entwicklung, -en",slovak:"development"},
{german:"die Lösung, -en",slovak:"solution"},
{german:"der E-Book-Reader, -",slovak:"e-book reader"},
{german:"die Bibliothek, -en",slovak:"library"},
{german:"enthalten, er/sie enthält, er/sie hat enthalten",slovak:"to contain"},
{german:"verbrauchen",slovak:"to consume"},
{german:"umweltfreundlich",slovak:"environmentally friendly"},
{german:"das Wunder, -",slovak:"miracle"},
{german:"zuverlässig",slovak:"reliable"},
{german:"der Computervirus, -viren",slovak:"computer virus"},
{german:"heutig-",slovak:"today's"},
{german:"elektronisch",slovak:"electronic"},
{german:"nutzlos",slovak:"useless"},
{german:"sogar",slovak:"even"},
{german:"an|fassen",slovak:"to touch"},
{german:"riechen, er/sie riecht, er/sie hat gerochen",slovak:"to smell"},
{german:"das Argument, -e",slovak:"argument"},
{german:"die Meinung, -en",slovak:"opinion, view"},
{german:"zu|stimmen",slovak:"to agree"},
{german:"widersprechen, er/sie widerspricht, er/sie hat widersprochen",slovak:"to contradict"},
{german:"unsicher",slovak:"uncertain, insecure"},
{german:"der Büroalltag",slovak:"everyday office life"},
{german:"die Spam-E-Mail, -s",slovak:"spam emails"},
{german:"die Visitenkarte, -n",slovak:"business card"},
{german:"beraten, er/sie berät, er/sie hat beraten",slovak:"to advise"},
{german:"zu|hören",slovak:"to listen carefully"},
{german:"aus|stellen",slovak:"to exhibit"},
{german:"besprechen, er/sie bespricht, er/sie hat besprochen",slovak:"to discuss"},
{german:"das Modell, -e",slovak:"model"},
{german:"der Messestand, -ä-e",slovak:"exhibition stand"},
{german:"(sich) setzen",slovak:"to sit, take a seat"},
]