const listOfWords = [
{german:"hören",slovak:"to listen"},
{german:"Musik hören",slovak:"listen to music"},
{german:"tanzen",slovak:"dance"},
{german:"fahren, er/sie fährt",slovak:"to ride, drive"},
{german:"Ski/Fahrrad fahren",slovak:"to skiing, ride a bicycle"},
{german:"sehen, er/sie sieht",slovak:"to see, he/she sees"},
{german:"der Film, -e",slovak:"movie"},
{german:"fotografieren",slovak:"to photograph"},
{german:"Volleyball/Fussball spielen",slovak:"to play volleyball / football, soccer"},
{german:"kochen",slovak:"to cook"},
{german:"treffen, er/sie trifft",slovak:"to meet, he/she meets"},
{german:"der Freund, -e",slovak:"friend, boyfriend"},
{german:"die Freundin, -nen",slovak:"friend (f.), girlfriend"},
{german:"lesen, er/sie liest",slovak:"to read, he/she reads"},
{german:"wandern",slovak:"to hike"},
{german:"schwimmen",slovak:"to swim"},
{german:"laufen, er/sie läuft",slovak:"to run, he/she runs (is running)"},
{german:"Schlittschuh laufen",slovak:"ice skating"},
{german:"schlafen, er/sie schläft",slovak:"to sleep"},
{german:"sprechen, er/sie spricht",slovak:"to speak, he/she speaks"},
{german:"lange",slovak:"long"},
{german:"im (+ Jahreszeit)",slovak:"in + season"},
{german:"der Frühling",slovak:"spring"},
{german:"der Sommer",slovak:"summer"},
{german:"der Herbst",slovak:"fall, autumn"},
{german:"der Winter",slovak:"winter"},
{german:"wann",slovak:"when (time)"},
{german:"anfangen, er/sie fängt an",slovak:"start"},
{german:"aufhören",slovak:"stop"},
{german:"der Tag, -e",slovak:"day"},
{german:"jeden Tag",slovak:"every day"},
{german:"die Woche, -n",slovak:"week"},
{german:"am (+ Wochentag)",slovak:"on + weekday"},
{german:"der Montag, -e",slovak:"Monday"},
{german:"der Dienstag, -e",slovak:"Tuesday"},
{german:"der Mittwoch, -e",slovak:"Wednesday"},
{german:"der Donnerstag, -e",slovak:"Thursday"},
{german:"der Freitag, -e",slovak:"Friday"},
{german:"der Samstag, -e",slovak:"Saturday"},
{german:"der Sonntag, -e",slovak:"Sunday"},
{german:"das Wochenende, -n",slovak:"weekend"},
{german:"oft",slovak:"often"},
{german:"wegfahren, er/sie fährt weg",slovak:"go away (on a trip)"},
{german:"manchmal",slovak:"sometimes"},
{german:"einladen, er/sie lädt ein",slovak:"to invite"},
{german:"selten",slovak:"rarely"},
{german:"anrufen",slovak:"to call somebody"},
{german:"leben",slovak:"to live"},
{german:"immer",slovak:"always"},
{german:"ausgehen",slovak:"to go out"},
{german:"einkaufen",slovak:"to go (grocery) shopping"},
{german:"aufräumen",slovak:"to clean up, tidy"},
{german:"fernsehen, er/sie sieht fern",slovak:"to watch TV"},
{german:"nie",slovak:"never"},
{german:"wie oft",slovak:"how often"},
{german:"sagen",slovak:"to say"},
{german:"die Zeit, -en",slovak:"time"},
{german:"Ich habe leider keine Zeit.",slovak:"Unfortunately, I don’t have time"},
{german:"alle",slovak:"every, everybody/everything"},
{german:"Was macht man in der Freizeit? (3rd person sg.)",slovak:" What does “one” do in his free time?"},
{german:"75 Prozent lesen gern Bücher. (3rd person pl.)",slovak:"75 percent like to read books."},
{german:"die Leute (pl.)",slovak:"people"},
];