const listOfWords = [
{german:"das Fahrrad, -ä-er / CH: das Velo, -s",slovak:"bicycle"},
{german:"der Zug, -ü-e",slovak:"train"},
{german:"die U-Bahn, -en",slovak:"metro"},
{german:"die Strassenbahn, -en / die Tram (CH: das Tram)",slovak:"tram"},
{german:"der Bus, -se",slovak:"bus"},
{german:"das Schiff, -e",slovak:"ship"},
{german:"das Flugzeug, -e",slovak:"airplane"},
{german:"fliegen",slovak:"fly"},
{german:"zu Fuss",slovak:"by foot"},
{german:"Er geht zu Fuss.",slovak:"He goes by foot = he walks."},
{german:"mit (+ Verkehrsmittel)",slovak:"by “with” (+ means of transport)"},
{german:"Ich fahre oft mit dem Bus.",slovak:"I often go by bus."},
{german:"meistens",slovak:"mostly"},
{german:"unterschreiben",slovak:"to sign"},
{german:"nach Hause",slovak:"at home"},
{german:"bei (+ Ort)",slovak:"at (+ place)"},
{german:"aus (+ Ort)",slovak:"from (+ place), from Zurich"},
{german:"von (+ Ort)",slovak:"from (+ place), from Home"},
{german:"zu (+ Ort)",slovak:"to (+ place), to university"},
{german:"die Universität",slovak:"university"},
{german:"die Fahrt, -en",slovak:"ride"},
{german:"dauern",slovak:"to take (time)"},
{german:"Die Fahrt zur Uni dauert 20 Minuten.",slovak:"the ride to the university takes 20 minutes."},
{german:"Ich brauche fünf Minuten zu Fuss zum Bäcker.",slovak:"I need five minutes by foot to (get to) the baker."},
{german:"zusammen",slovak:"together"},
{german:"wohin",slovak:"where to"},
{german:"seit wann",slovak:"since when"},
{german:"seit",slovak:"since"},
{german:"vor / nach (+ Zeitpunkt)",slovak:"before / after (+ point in time)"},
{german:"Nach dem Kurs gehe ich ins Kino.",slovak:"After the class I go to the cinema."},
{german:"der Urlaub, -e / CH: die Ferien (pl.)",slovak:"holidays"},
{german:"packen",slovak:"to pack"},
{german:"Er packt den Koffer.",slovak:"He packs his suitcase."},
{german:"auspacken",slovak:"to unpack"},
{german:"zu Mittag essen, er/sie isst zu Mittag",slovak:"to have (“eat”) lunch"},
{german:"Wie komme ich zum /zur …?",slovak:"How do I get to the …?"},
{german:"die Richtung, -en",slovak:"direction"},
{german:"die Station, -en",slovak:"stop (transportation)"},
{german:"Du musst noch drei Stationen fahren.",slovak:"You have to go three more stops."},
{german:"umsteigen",slovak:"to change (the train)"},
{german:"einsteigen",slovak:"to get on (a bus)"},
{german:"aussteigen",slovak:"to get off"},
{german:"der Kilometer, -",slovak:"kilometer"},
{german:"die Million, -en",slovak:"million"},
{german:"der Radfahrer, -",slovak:"cyclist, m."},
{german:"die Radfahrerin, -nen",slovak:"cyclist, f."},
{german:"der Durchschnitt, -e",slovak:"average"},
{german:"Man fährt im Durchschnitt 514 Kilometer.",slovak:"In average we ride 514 kilometers."},
{german:"der Weg, -e",slovak:"the way, path"},
{german:"jung",slovak:"young"},
{german:"zum Beispiel",slovak:"for example"},
{german:"das Mitglied, -er",slovak:"member"},
];