const listOfWords = [
	{german:"altmodisch",slovak:"old-fashioned"},
{german:"die Möbel (Pl.)",slovak:"furniture"},
{german:"egal",slovak:"indifferent"},
{german:"weg|werfen, er/sie wirft weg, er/sie hat weggeworfen",slovak:"to throw away"},
{german:"Ja schon",slovak:"Okay"},
{german:"der Teppich, -e",slovak:"carpet"},
{german:"das Gucken",slovak:"staring"},
{german:"behalten, er/sie behält, er/sie hat behalten",slovak:"to keep"},
{german:"im Angebot (sein)",slovak:"to be on sale"},
{german:"das Lernplakat, -e",slovak:"grammar/vocabulary poster"},
{german:"telefonisch",slovak:"by telephone"},
{german:"reklamieren",slovak:"to complain"},
{german:"der Reklamationsschein, -e",slovak:"complaint form"},
{german:"das Material, -ien",slovak:"material"},
{german:"die Tischleuchte, -n",slovak:"table lamp"},
{german:"der Lampenschirm, -e",slovak:"lampshade"},
{german:"aus (+ Material)",slovak:"made of (material)"},
{german:"das Metall",slovak:"metal"},
{german:"die LED-Leuchte, -n",slovak:"LED lamp"},
{german:"weich",slovak:"soft"},
{german:"die Größe, -n",slovak:"size"},
{german:"das Gewicht, -e",slovak:"weight"},
{german:"das Material, -ien",slovak:"material"},
{german:"pur",slovak:"pure, genuine"},
{german:"mediterran",slovak:"Mediterranean"},
{german:"der Stoff, -e",slovak:"fabric"},
{german:"die Keramik",slovak:"ceramic"},
{german:"lieferbar",slovak:"available"},
{german:"die Bestellung, -en",slovak:"order"},
{german:"der Lieferschein, -e",slovak:"delivery note"},
{german:"der Auftrag, -ä-e",slovak:"order number"},
{german:"die Bestellnummer, -n",slovak:"order reference number"},
{german:"der Artikel, -",slovak:"[here] item"},
{german:"die Menge, -n",slovak:"quantity"},
{german:"gesamt",slovak:"total"},
{german:"der Liefertermin, -e",slovak:"delivery date"},
{german:"beide",slovak:"both"},
{german:"zurück|schicken",slovak:"to return, send back"},
{german:"das Formular, -e",slovak:"form"},
{german:"aus|füllen",slovak:"to fill out"},
{german:"ergänzen",slovak:"to complete"},
{german:"der Absender, -",slovak:"sender"},
{german:"die Beschreibung, -en",slovak:"description"},
{german:"der Grund, -ü-e",slovak:"reason"},
{german:"fehlen",slovak:"to be missing"},
{german:"bestimmen",slovak:"to determine"},
{german:"das Paket, -e",slovak:"package"},
{german:"ab|schicken",slovak:"to send"},
{german:"das Möbelstück, -e",slovak:"piece of furniture"},
{german:"das Upcycling",slovak:"upcycling"},
{german:"der Flugbegleiter, -",slovak:"flight attendant"},
{german:"die Flugbegleiterin -nen",slovak:"female flight attendant"},
{german:"der Trolley, -s",slovak:"trolley"},
{german:"die Minibar, -s",slovak:"minibar"},
{german:"das Brett, -er",slovak:"board"},
{german:"das Holz",slovak:"wood"},
{german:"das Plastik",slovak:"plastic"},
{german:"stabil",slovak:"stable, solid"},
{german:"benutzen",slovak:"to use"},
{german:"kreativ",slovak:"creative"},
{german:"das Neue (etwas Neues)",slovak:"new (something new)"},
{german:"das Fass, -ä-er",slovak:"barrel"},
{german:"entstehen, er/sie entsteht, er/sie ist entstanden",slovak:"to be created"},
{german:"umweltbewusst",slovak:"environmentally conscious"},
{german:"der Online-Shop, -s",slovak:"online shop"},
{german:"kaputt|gehen, er/sie geht kaputt, er/sie ist kaputtgegangen",slovak:"to break down"},
{german:"sich wohl|fühlen",slovak:"to feel good"},
{german:"der Apparat, -e",slovak:"device"},
{german:"die Marktgasse",slovak:"market street"},
{german:"der Franken, -",slovak:"Swiss franc"},
{german:"das Einkaufszentrum, -zentren",slovak:"shopping center"},
{german:"das Warenhaus, -äu-er",slovak:"department store"},
{german:"das Parlament, -e",slovak:"parliament"},
{german:"der Politiker, -",slovak:"politician"},
{german:"die Politikerin, -nen",slovak:"female politician"},
{german:"die Münze, -n",slovak:"coin"},
{german:"der Brunnen, -",slovak:"fountain"},
{german:"wahrscheinlich",slovak:"probably"},
{german:"historisch",slovak:"historical"},
{german:"das Gebäude, -",slovak:"building"},
{german:"zurück|bekommen, er/sie bekommt zurück, er/sie hat zurückbekommen",slovak:"to get back"},
{german:"der Prospekt, -e",slovak:"brochure"},
{german:"recherchieren",slovak:"to research"},
{german:"gestalten",slovak:"to design"},
]