const listOfWords = [
{german:"die Kopie, -n",slovak:"copy"},
{german:"das Praktikum, Praktika",slovak:"traineeship"},
{german:"Er macht ein Praktikum bei DesigNetz.",slovak:"He’s “doing” a traineeship at DesigNetz."},
{german:"zusammenarbeiten",slovak:"work together"},
{german:"neugierig",slovak:"curious"},
{german:"kennenlernen",slovak:"get to know"},
{german:"die Grafik, -en",slovak:"the graphic"},
{german:"die Frage, -n",slovak:"the question"},
{german:"antworten",slovak:"to answer"},
{german:"allein",slovak:"alone"},
{german:"einfach",slovak:"easy"},
{german:"gar nicht",slovak:"not at all"},
{german:"Das war gar nicht so einfach.",slovak:"This wasn’t so easy at all."},
{german:"Die Arbeit hat Spass gemacht.",slovak:"The work was fun."},
{german:"fertig",slovak:"finished; done"},
{german:"Ich habe die Arbeit fertig gemacht.",slovak:"I’ve finished the work."},
{german:"organisieren",slovak:"organize"},
{german:"präsentieren",slovak:"present (have a presentation)"},
{german:"kopieren",slovak:"copy"},
{german:"studieren",slovak:"study"},
{german:"telefonieren",slovak:"to be on the phone"},
{german:"gestern",slovak:"yesterday"},
{german:"die Prüfung, -en",slovak:"exam"},
{german:"die Reise, -n",slovak:"the trip"},
{german:"krank",slovak:"sick"},
{german:"die Konferenz, -en",slovak:"conference"},
{german:"zu spät kommen",slovak:"er/sie ist zu spät gekommen to come too late"},
{german:"die Verspätung, -en",slovak:"delay"},
{german:"Das Flugzeug hatte Verspätung.",slovak:"the flight “had a delay” → the flight was"},
{german:"delayed",slovak:""},
{german:"die Präsentation, -en",slovak:"presentation"},
{german:"passieren, es ist passiert",slovak:"to happen"},
{german:"der Fehler, -",slovak:"mistake"},
{german:"voll",slovak:"full"},
{german:"das Hotel, -s",slovak:"hotel"},
{german:"Das Hotel war voll.",slovak:"The hotel was full (fully booked)."},
{german:"das Taxi, -s",slovak:"cab; taxi"},
{german:"warum",slovak:"why"},
{german:"Das macht (keinen) Spass!",slovak:"This isn’t fun."},
{german:"sammeln",slovak:"collect"},
{german:"der Redakteur, -e",slovak:"editor, m."},
{german:"die Redakteurin, -nen",slovak:"editor, f."},
{german:"das Internet (sg.)",slovak:"internet"},
{german:"erfolgreich",slovak:"successful"},
{german:"zurück",slovak:"back"},
{german:"die Briefmarke, -n",slovak:"stamp"},
{german:"die Post (Firma/Gebäude) (sg.)",slovak:"post office"},
{german:"die Ampel, -n",slovak:"signal (traffic)"},
{german:"die Haltestelle, -n",slovak:"stop (e.g.: bus stop)"},
{german:"eilig",slovak:"in a hurry"},
{german:"es eilig haben",slovak:"to be in a hurry"},
{german:"der Stau, -s",slovak:"traffic jam"},
{german:"im Stau stehen, er/sie hat im Stau gestanden",slovak:"be stuck in a traffic jam"},
{german:"der Fussgänger, -",slovak:"pedestrian, m."},
{german:"die Fussgängerin, -nen",slovak:"pedestrian, f."},
{german:"der Autofahrer, -",slovak:"car driver, m."},
{german:"die Autofahrerin, -nen",slovak:"car driver, f."},
];