const listOfWords = [
{german:"der Strand, -ä-e",slovak:"beach"},
{german:"das Meer, -e",slovak:"sea"},
{german:"die Insel, -n",slovak:"island"},
{german:"das Dorf, -ö-er",slovak:"village"},
{german:"der Wald, -ä-er",slovak:"forrest"},
{german:"die Kirche, -n",slovak:"church"},
{german:"der See, -n",slovak:"lake"},
{german:"das Boot, -e",slovak:"boat"},
{german:"baden",slovak:"to bath"},
{german:"In der Sonne liegen",slovak:"to sunbath"},
{german:"bummeln",slovak:"to stroll (walking around in a city)"},
{german:"tauchen",slovak:"dive"},
{german:"angeln",slovak:"to fish"},
{german:"der Fluss, -ü-e",slovak:"river"},
{german:"zelten",slovak:"to camp"},
{german:"segeln",slovak:"to sail"},
{german:"bald",slovak:"soon"},
{german:"mieten",slovak:"to rent"},
{german:"die Dusche, -n",slovak:"shower"},
{german:"würde (gern), er/sie würde",slovak:"to would"},
{german:"Ich würde gern nach Rom fahren.",slovak:"I would like to go to Rome."},
{german:"das Doppelzimmer, -",slovak:"double room"},
{german:"kostenlos",slovak:"for free"},
{german:"der Fernseher, -",slovak:"TV"},
{german:"der Internetanschluss, ü-e",slovak:"internet connection"},
{german:"die Heizung, -en",slovak:"heating"},
{german:"das Radio, -s",slovak:"radio"},
{german:"das Licht (sg.)",slovak:"light"},
{german:"die Toilette, -n",slovak:"restroom"},
{german:"die Badewanne, -n",slovak:"bathtub"},
{german:"Freitag haben Sie ein Zimmer frei?",slovak:"Do you have a (free) room on Friday?"},
{german:"mittwochs",slovak:"on Wednesdays"},
{german:"das Einzelzimmer, -",slovak:"single room"},
{german:"die Übernachtung, -en",slovak:"overnight stay"},
{german:"die Rezeption, -en",slovak:"reception"},
{german:"kaputt",slovak:"broken"},
{german:"schicken",slovak:"send"},
{german:"in (+ Zeit)",slovak:"in (+time)"},
{german:"Ich bringe den Schlüssel in fünf Minuten.",slovak:"I bring you the keys in five minutes."},
{german:"reparieren",slovak:"to repair"},
{german:"nass",slovak:"wet"},
{german:"reisen",slovak:"to travel"},
{german:"die Ferien (pl.)",slovak:"holidays"},
{german:"der Manager, -",slovak:"manager, m."},
{german:"die Managerin, -nen",slovak:"manager, f."},
{german:"Europa",slovak:"Europe"},
{german:"das Ergebnis, -se",slovak:"result"},
{german:"der Unterschied, -e",slovak:"difference"},
{german:"ähnlich",slovak:"similar"},
{german:"reservieren",slovak:"book"},
{german:"Ich möchte ein Zimmer reservieren.",slovak:"I’d like to book a room."},
{german:"gleich",slovak:"immediately"},
{german:"Ich gehe gleich einkaufen.",slovak:"I’m going to shop immediately."},
{german:"ausmachen",slovak:"to turn something off"},
{german:"Mach bitte das Radio aus.",slovak:"Please, turn the radio off."},
{german:"das Feuer, -",slovak:"fire"},
{german:"sauber",slovak:"clean"},
];