const listOfWords = [
	{german:"die Nation, -en",slovak:"nation"},
{german:"die Zirkusartistik",slovak:"circus arts"},
{german:"die Akrobatik",slovak:"acrobatics"},
{german:"die Vorstellung, -en",slovak:"performance"},
{german:"das Honorar, -e",slovak:"fee"},
{german:"klatschen",slovak:"to applaud"},
{german:"der Infostand, -ä-e",slovak:"information stand"},
{german:"der Akrobat, -en",slovak:"acrobat"},
{german:"die Akrobatin, -nen",slovak:"female acrobat"},
{german:"leer",slovak:"empty"},
{german:"der Zuschauer, -",slovak:"spectator"},
{german:"die Zuschauerin, -nen",slovak:"female spectator"},
{german:"der Blogeintrag, -ä-e",slovak:"blog entry"},
{german:"der Festivalguide, -s",slovak:"festival guide"},
{german:"das OpenAir, -s",slovak:"open air"},
{german:"der Philharmoniker, -",slovak:"philharmonic orchestra member"},
{german:"das Lieblingsorchester, -",slovak:"favorite orchestra"},
{german:"die Kühlschrank-Poesie",slovak:"refrigerator poetry"},
{german:"wachsen, er/sie wächst, er/sie ist gewachsen",slovak:"to grow"},
{german:"aus|schneiden, er/sie schneidet aus, er/sie hat ausgeschnitten",slovak:"to cut out"},
{german:"mindestens",slovak:"at least"},
{german:"weiter|erzählen",slovak:"to continue the story"},
{german:"verbrennen, er/sie verbrennt, er/sie hat verbrannt",slovak:"to burn"},
{german:"das Pferd, -e",slovak:"horse"},
{german:"reiten, er/sie reitet, er/sie ist geritten",slovak:"to ride"},
{german:"der Reiter, -",slovak:"rider"},
{german:"die Reiterin, -nen",slovak:"female rider"},
{german:"der Schneemann, -ä-er",slovak:"snowman"},
{german:"die Uniform, -en",slovak:"uniform"},
{german:"die Kutsche, -n",slovak:"carriage"},
{german:"die Fahne, -n",slovak:"flag"},
{german:"die Trommel, -n",slovak:"drum"},
{german:"(sich) verabschieden",slovak:"to say goodbye"},
{german:"die Holzwolle",slovak:"excelsior"},
{german:"das Symbol, -e",slovak:"symbol"},
{german:"die Glocke, -n",slovak:"bell"},
{german:"läuten",slovak:"to ring [bell]"},
{german:"an|machen",slovak:"to turn on"},
{german:"die Tracht, -en",slovak:"traditional costume"},
]