const listOfWords = [
	{german:"die Verletzung, -en",slovak:"injury"},
{german:"der Notruf, -e",slovak:"emergency call"},
{german:"der Notfall, -ä-e",slovak:"emergency"},
{german:"das Blut",slovak:"blood"},
{german:"das Krankenhaus",slovak:"hospital"},
{german:"der Krankenwagen, -",slovak:"ambulance (car)"},
{german:"der Patient, -en",slovak:"patient"},
{german:"die Patientin, -nen",slovak:"female patient"},
{german:"(sich) stoßen, er/sie stößt, er/sie hat gestoßen",slovak:"to hit, collide"},
{german:"(sich) verletzen",slovak:"to injure oneself"},
{german:"bluten",slovak:"to bleed"},
{german:"kühlen",slovak:"to cool"},
{german:"die Notaufnahme, -n",slovak:"emergency/urgent admission"},
{german:"putzen",slovak:"to clean"},
{german:"sich Sorgen machen",slovak:"to worry"},
{german:"der Finger, -",slovak:"finger"},
{german:"bewusstlos",slovak:"unconscious"},
{german:"stürzen",slovak:"to fall, crash"},
{german:"die Notruf-Regel, -n",slovak:"rule for emergency calls"},
{german:"erreichbar (sein)",slovak:"to be able to talk (to someone)"},
{german:"die Brust, -ü-e",slovak:"chest"},
{german:"der Verletzte, -n",slovak:"injured person (male)"},
{german:"die Verletzte, -n",slovak:"injured person (female)"},
{german:"auf|legen",slovak:"to hang up (the phone)"},
{german:"die Autobahn, -en",slovak:"highway"},
{german:"die Notrufzentrale, -n",slovak:"emergency call center"},
{german:"hilflos",slovak:"helpless"},
{german:"kaum",slovak:"hardly"},
{german:"ansprechbar (sein)",slovak:"to be conscious"},
{german:"das Bewusstsein",slovak:"consciousness"},
{german:"erreichen",slovak:"[here] to come into contact"},
{german:"die Anmeldung, -en",slovak:"registration"},
{german:"das Geburtsdatum, -daten",slovak:"date of birth"},
{german:"die Krankenkasse, -n",slovak:"health insurance"},
{german:"die Gesundheitskarte, -n",slovak:"health card"},
{german:"die Krankheit, -en",slovak:"illness"},
{german:"die Operation, -en",slovak:"operation"},
{german:"das Gehirn, -e",slovak:"brain"},
{german:"die Gehirnerschütterung, -en",slovak:"concussion"},
{german:"die Schmerztablette, -n",slovak:"painkiller (pill)"},
{german:"das Rezept, -e",slovak:"prescription"},
{german:"der Husten",slovak:"cough"},
{german:"der Schnupfen",slovak:"runny nose"},
{german:"die Grippe",slovak:"flu"},
{german:"schlecht (Mir wird/ ist schlecht.)",slovak:"bad (I feel bad/ nauseous.)"},
{german:"auf jeden Fall",slovak:"in any case, definitely"},
{german:"der Kamillentee, -s",slovak:"chamomile tea"},
{german:"ein|schlafen, er/sie schläft ein, er/sie ist eingeschlafen",slovak:"to fall asleep"},
{german:"der Verein, -e",slovak:"club"},
{german:"der Clown, -s",slovak:"clown"},
{german:"der Künstler, -",slovak:"artist"},
{german:"die Künstlerin, -nen",slovak:"female artist"},
{german:"speziell",slovak:"special"},
{german:"der Humor",slovak:"humor"},
{german:"der Krankenpfleger, -",slovak:"nurse (male)"},
{german:"die Krankenpflegerin, -nen",slovak:"nurse (female)"},
{german:"jonglieren",slovak:"to juggle"},
{german:"der Zaubertrick, -s",slovak:"magic trick"},
{german:"das Lächeln",slovak:"smile"},
{german:"leuchten",slovak:"to shine"},
{german:"die Stirn, -en",slovak:"forehead"},
{german:"der Lerner, -",slovak:"learner"},
{german:"die Lernerin, -nen",slovak:"female learner"},
{german:"der Zwilling, -e",slovak:"twin"},
{german:"die Doppelhochzeit, -en",slovak:"double wedding"},
{german:"die Arztpraxis, -praxen",slovak:"doctor's office"},
{german:"unternehmen, er/sie unternimmt, er/sie hat unternommen",slovak:"to do (something)"},
{german:"der Wettkampf, -ä-e",slovak:"competition"},
{german:"der Sprachclub, -s",slovak:"language club"},
{german:"der Wanderverein, -e",slovak:"hiking club"},
{german:"der Kegelverein, -e",slovak:"bowling club"},
{german:"die Lesegruppe, -n",slovak:"reading group, literary circle"},
{german:"der Kochverein, -e",slovak:"cooking club"},
{german:"reden",slovak:"to talk"},
]